#### 라이브러리

In [176]:
import pandas as pd
import numpy as np

#### 파일 로드

In [177]:
museum = pd.read_csv("data/KC_477_DMSTC_MCST_MUSEUM_2024.csv", encoding="utf-8-sig")
art = pd.read_csv("data/KC_478_DMSTC_MCST_ARTGR_2025.csv", encoding="utf-8-sig")

#### 01.1 기본 정보 확인

In [178]:
print("박물관:", museum.shape)
print("미술관:", art.shape)

박물관: (898, 94)
미술관: (294, 79)

In [179]:
display(museum.head())
museum.info()

,ID,LCLAS_NM,MLSFC_NM,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,LEGALDONG_CD,LEGALDONG_NM,ADSTRD_CD,ADSTRD_NM,...,ARTGR_EMP_CO,PRFSN_CO,ETC_GNRL_EMP_CO,ETC_INTN_EMP_CO,PRVATE_VLNTER_CO,RM_CN,LAST_CHG_DE,ORIGIN_NM,FILE_NM,BASE_DE
0,KCDMMUS23N000000001,문화시설,박물관,국립중앙박물관,서울,용산구,1.117014e+09,용산동6가,1.117062e+09,한강로동,...,NaN,NaN,NaN,NaN,NaN,NaN,20250327,문화데이터총람 2024,KC_477_DMSTC_MCST_MUSEUM_2024,20250327
1,KCDMMUS23N000000002,문화시설,박물관,국립민속박물관,서울,종로구,1.111012e+09,세종로,1.111052e+09,청운효자동,...,NaN,NaN,NaN,NaN,NaN,NaN,20250327,문화데이터총람 2024,KC_477_DMSTC_MCST_MUSEUM_2024,20250327
2,KCDMMUS23N000000003,문화시설,박물관,국립민속박물관 파주\n(개방형 수장고 및 정보센터),경기,파주시,4.148032e+09,탄현면 법흥리,4.148032e+09,탄현면,...,NaN,NaN,NaN,NaN,NaN,NaN,20250327,문화데이터총람 2024,KC_477_DMSTC_MCST_MUSEUM_2024,20250327
3,KCDMMUS23N000000004,문화시설,박물관,대한민국역사박물관,서울,종로구,1.111012e+09,세종로,1.111062e+09,종로1.2.3.4가동,...,NaN,NaN,NaN,NaN,NaN,NaN,20250327,문화데이터총람 2024,KC_477_DMSTC_MCST_MUSEUM_2024,20250327
4,KCDMMUS23N000000005,문화시설,박물관,국립한글박물관,서울,용산구,1.117014e+09,용산동6가,1.117069e+09,서빙고동,...,NaN,NaN,NaN,NaN,NaN,NaN,20250327,문화데이터총람 2024,KC_477_DMSTC_MCST_MUSEUM_2024,20250327

<class 'pandas.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 94 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   ID                             897 non-null    str
 1   LCLAS_NM                       897 non-null    str
 2   MLSFC_NM                       897 non-null    str
 3   FCLTY_NM                       897 non-null    str
 4   CTPRVN_NM                      897 non-null    str
 5   SIGNGU_NM                      897 non-null    str
 6   LEGALDONG_CD                   897 non-null    float64
 7   LEGALDONG_NM                   897 non-null    str
 8   ADSTRD_CD                      897 non-null    float64
 9   ADSTRD_NM                      897 non-null    str
 10  RDNMADR_CD                     881 non-null    float64
 11  RDNMADR_NM                     897 non-null    str
 12  ZIP_NO                         897 non-null    float64
 13  GID_CD                         897 non-null    str
 14  FCLTY_LO                       897 non-null    float64
 15  FCLTY_LA                       897 non-null    float64
 16  FLAG_NM                        897 non-null    str
 17  BASS_CRSTAT_SDIV_VALUE         897 non-null    str
 18  TEL_NO                         893 non-null    str
 19  OPNNG_DE                       897 non-null    str
 20  REGIST_CRSTAT_CN               895 non-null    str
 21  REGIST_DE                      894 non-null    str
 22  REGIST_NO                      894 non-null    str
 23  HMPG_ADDR                      821 non-null    str
 24  SOUND_PROVD_AT                 889 non-null    str
 25  SOUND_UTILIIZA_PRICE           180 non-null    str
 26  MOBILE_PROVD_AT                888 non-null    str
 27  LND_AR_VALUE                   886 non-null    float64
 28  TOTAR_VALUE                    885 non-null    float64
 29  DSPY_AR_CN                     889 non-null    float64
 30  DSPY_AR_CN.1                   878 non-null    float64
 31  DSPYRM_ARTFT_CHG_CO            758 non-null    str
 32  SPECL_DSPY_AR_VALUE            606 non-null    str
 33  AR_CN                          847 non-null    float64
 34  TP_SDIV_NM                     838 non-null    str
 35  EDC_FCLTY_AR_VALUE             655 non-null    float64
 36  DATA_SPCE_AR_VALUE             505 non-null    float64
 37  DATA_CO                        503 non-null    float64
 38  OFFM_AR_CN                     837 non-null    float64
 39  CLTUR_GOODS_SPCE_AR_VALUE      233 non-null    float64
 40  RSTRNT_AR_VALUE                187 non-null    float64
 41  PARKNG_POSBL_CO                774 non-null    str
 42  HDCH_ARTFT_KND_CO              876 non-null    str
 43  HDCH_ARTFT_CAS_CO              743 non-null    str
 44  HDCH_ARTFT_CO                  874 non-null    str
 45  CRLTS_NM                       282 non-null    str
 46  CRLTS_CO                       282 non-null    str
 47  PBLPRFR_CAS_CO                 640 non-null    str
 48  TOT_PROGRM_CO                  681 non-null    float64
 49  PROGRM_CO                      374 non-null    float64
 50  FDRM_EXPRN_PROGRM_CO           524 non-null    float64
 51  NON_FDRM_EXPRN_PROGRM_CO       498 non-null    float64
 52  OUT_PROGRM_CO                  171 non-null    float64
 53  OPNNG_DAY_CO                   856 non-null    float64
 54  OPNNG_TIME                     873 non-null    str
 55  VIEWNG_NMPR_CO                 856 non-null    float64
 56  DAY_AVRG_VIEWNG_NMPR_CO        856 non-null    float64
 57  VIEWNG_PRICE                   343 non-null    str
 58  INFN_VIEWNG_PRICE              184 non-null    float64
 59  SCHBOY_VIEWNG_PRICE            321 non-null    float64
 60  MSKLSD_VIEWNG_PRICE            335 non-null    str
 61  ADULT_VIEWNG_PRICE             337 non-null    float64
 62  GRP_DSCNT_RT                   290 non-null    str
 63  ETC_DSCNT_RT                   195 non-null    str
 64  DSCNT_CN                       247 non-null    str
 65  FRE_TRGET_CN                   811 non-null    str
 66  SPECL_VIEWNG_PRICE             128 non-null    str
 67  INFN_SPECL_VIEWNG_PRICE        62 non-null     float64
 68  SCHBOY_SPECL_VIEWNG_PRICE      113 non-null    str
 69  MSKLSD_SPECL_VIEWNG_PRICE      123 non-null    str
 70  ADULT_SPECL_VIEWNG_PRICE       122 non-null    float64
 71  GRP_SPECL_VIEWNG_RT            101 non-null    str
 72  ETC_SPECL_VIEWNG_DSCNT_RT      73 non-null     str
 73  ETC_SPECL_VIEWNG_DSCNT_CN      98 non-null     str
 74  FRE_SPECL_VIEWNG_PRICE         515 non-null    str
 75  NMPR_CO                        356 non-null    float64
 76  CLTUR_ART_GVRNM_MANAGE_EMP_CO  63 non-null     float64
 77  CLTUR_ART_GVRNM_EMP_CO         265 non-null    float64
 78  QUALF_HOLD_CO                  142 non-null    float64
 79  CNTRCT_EMP_CO                  126 non-null    float64
 80  GNRL_GVRNM_EMP_CO              250 non-null    float64
 81  CNTRCT_EMP_CO.1                221 non-null    float64
 82  INTN_EMP_CO                    30 non-null     float64
 83  PUBLIC_VLNTER_CO               143 non-null    float64
 84  ARTGR_EMP_CO                   333 non-null    float64
 85  PRFSN_CO                       136 non-null    float64
 86  ETC_GNRL_EMP_CO                229 non-null    float64
 87  ETC_INTN_EMP_CO                63 non-null     float64
 88  PRVATE_VLNTER_CO               86 non-null     float64
 89  RM_CN                          0 non-null      float64
 90  LAST_CHG_DE                    898 non-null    int64
 91  ORIGIN_NM                      898 non-null    str
 92  FILE_NM                        898 non-null    str
 93  BASE_DE                        898 non-null    int64
dtypes: float64(45), int64(2), str(47)
memory usage: 659.6 KB

- 박물관에 ID가 없는 행 발견

In [180]:
display(art.head())
art.info()

,ID,LCLAS_NM,MLSFC_NM,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,LEGALDONG_CD,LEGALDONG_NM,ADSTRD_CD,ADSTRD_NM,...,CURTR_NTHG_QUALF_HOLD_CO,PRFSN_CO,GNRL_EMP_CO,PRVATE_INTN_CO,PRVATE_VLNTER_CO,RM_CN,LAST_CHG_DE,ORIGIN_NM,FILE_NM,BASE_DE
0,KCDMART25N000000001,문화시설,미술관,국립현대미술관(과천관),경기,과천시,4129010400,막계동,4129056000,문원동,...,NaN,NaN,NaN,NaN,NaN,"국립 미술관 공공(공무원) 직원수는 과천, 서울, 덕수궁, 청주관 합계 수치입니다.",20260610,문화기반시설총람 2025,KC_478_DMSTC_MCST_ARTGR_2025,20251231
1,KCDMART25N000000002,문화시설,미술관,국립현대미술관(서울관),서울,종로구,1111014200,소격동,1111054000,삼청동,...,NaN,NaN,NaN,NaN,NaN,NaN,20260610,문화기반시설총람 2025,KC_478_DMSTC_MCST_ARTGR_2025,20251231
2,KCDMART25N000000003,문화시설,미술관,국립현대미술관(덕수궁관),서울,중구,1114016700,정동,1114052000,소공동,...,NaN,NaN,NaN,NaN,NaN,NaN,20260610,문화기반시설총람 2025,KC_478_DMSTC_MCST_ARTGR_2025,20251231
3,KCDMART25N000000004,문화시설,미술관,국립현대미술관 미술품수장센터(청주관),충북,청주시,4311410200,내덕동,4311453000,내덕2동,...,NaN,NaN,NaN,NaN,NaN,NaN,20260610,문화기반시설총람 2025,KC_478_DMSTC_MCST_ARTGR_2025,20251231
4,KCDMART25N000000005,문화시설,미술관,DDP디자인뮤지엄,서울,중구,1114014900,을지로7가,1114059000,광희동,...,NaN,NaN,NaN,NaN,NaN,NaN,20260610,문화기반시설총람 2025,KC_478_DMSTC_MCST_ARTGR_2025,20251231

<class 'pandas.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 79 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         294 non-null    str
 1   LCLAS_NM                   294 non-null    str
 2   MLSFC_NM                   294 non-null    str
 3   FCLTY_NM                   294 non-null    str
 4   CTPRVN_NM                  294 non-null    str
 5   SIGNGU_NM                  294 non-null    str
 6   LEGALDONG_CD               294 non-null    int64
 7   LEGALDONG_NM               294 non-null    str
 8   ADSTRD_CD                  294 non-null    int64
 9   ADSTRD_NM                  294 non-null    str
 10  RDNMADR_CD                 294 non-null    int64
 11  RDNMADR_NM                 294 non-null    str
 12  ZIP_NO                     294 non-null    int64
 13  GID_CD                     294 non-null    str
 14  FCLTY_LO                   294 non-null    float64
 15  FCLTY_LA                   294 non-null    float64
 16  FLAG_NM                    294 non-null    str
 17  REGIST_AT                  294 non-null    str
 18  TEL_NO                     294 non-null    str
 19  OPNNG_DE                   294 non-null    str
 20  REGIST_DC                  294 non-null    str
 21  REGIST_DE                  294 non-null    str
 22  REGIST_NO                  294 non-null    str
 23  HMPG_ADDR                  276 non-null    str
 24  SOUND_PROVD_AT             294 non-null    str
 25  SOUND_UTILIIZA_PRICE       47 non-null     str
 26  MOBILE_PROVD_AT            294 non-null    str
 27  LND_AR_VALUE               292 non-null    str
 28  BULD_AR_VALUE              291 non-null    str
 29  DSPY_AR_CN                 294 non-null    str
 30  AR_CN                      0 non-null      float64
 31  EDC_FCLTY_AR_VALUE         205 non-null    str
 32  OFFM_AR_CN                 277 non-null    str
 33  DATA_SPCE_AR_VALUE         176 non-null    float64
 34  DATA_CO                    160 non-null    str
 35  PBLPRFR_CAS_CO             264 non-null    str
 36  TOT_PROGRM_CO              226 non-null    float64
 37  OPNNG_DAY_CO               294 non-null    int64
 38  VIEWNG_NMPR_CO             294 non-null    str
 39  DAY_AVRG_VIEWNG_NMPR_CO    294 non-null    str
 40  VIEWNG_PRICE               98 non-null     str
 41  INFN_VIEWNG_PRICE          97 non-null     str
 42  SCHBOY_VIEWNG_PRICE        97 non-null     str
 43  MSKLSD_VIEWNG_PRICE        97 non-null     str
 44  ADULT_VIEWNG_PRICE         96 non-null     str
 45  GRP_DSCNT_RT               76 non-null     str
 46  ETC_DSCNT_RT               64 non-null     str
 47  DSCNT_CN                   75 non-null     str
 48  FRE_TRGET_CN               213 non-null    str
 49  SPECL_VIEWNG_PRICE         117 non-null    str
 50  INFN_SPECL_VIEWNG_PRICE    112 non-null    str
 51  SCHBOY_SPECL_VIEWNG_PRICE  112 non-null    str
 52  MSKLSD_SPECL_VIEWNG_PRICE  112 non-null    str
 53  ADULT_SPECL_VIEWNG_PRICE   112 non-null    str
 54  GRP_SPECL_VIEWNG_RT        91 non-null     str
 55  ETC_SPECL_VIEWNG_DSCNT_RT  80 non-null     str
 56  ETC_SPECL_VIEWNG_DSCNT_CN  93 non-null     str
 57  FRE_SPECL_VIEWNG_PRICE     201 non-null    str
 58  NMPR_CO                    294 non-null    int64
 59  GVRNM_EMP_SM_CO            294 non-null    int64
 60  QUALF_HOLD_CO              294 non-null    int64
 61  TOT_CNTRCT_EMP_CO          38 non-null     float64
 62  CNTRCT_EMP_CRTFCT_CO       34 non-null     float64
 63  GNRL_GVRNM_EMP_CO          40 non-null     float64
 64  CNTRCT_EMP_CO              46 non-null     float64
 65  PUBLIC_INTN_CO             14 non-null     float64
 66  PUBLIC_VLNTER_CO           40 non-null     str
 67  ARTGR_EMP_CO               210 non-null    float64
 68  CURTR_QUALF_HOLD_CO        179 non-null    float64
 69  CURTR_NTHG_QUALF_HOLD_CO   72 non-null     float64
 70  PRFSN_CO                   72 non-null     float64
 71  GNRL_EMP_CO                114 non-null    float64
 72  PRVATE_INTN_CO             33 non-null     float64
 73  PRVATE_VLNTER_CO           31 non-null     float64
 74  RM_CN                      1 non-null      str
 75  LAST_CHG_DE                294 non-null    int64
 76  ORIGIN_NM                  294 non-null    str
 77  FILE_NM                    294 non-null    str
 78  BASE_DE                    294 non-null    int64
dtypes: float64(17), int64(10), str(52)
memory usage: 181.6 KB

In [181]:
print("박물관 컬럼")
print(museum.columns.tolist())

print("\n미술관 컬럼")
print(art.columns.tolist())

박물관 컬럼
['ID', 'LCLAS_NM', 'MLSFC_NM', 'FCLTY_NM', 'CTPRVN_NM', 'SIGNGU_NM', 'LEGALDONG_CD', 'LEGALDONG_NM', 'ADSTRD_CD', 'ADSTRD_NM', 'RDNMADR_CD', 'RDNMADR_NM', 'ZIP_NO', 'GID_CD', 'FCLTY_LO', 'FCLTY_LA', 'FLAG_NM', 'BASS_CRSTAT_SDIV_VALUE', 'TEL_NO', 'OPNNG_DE', 'REGIST_CRSTAT_CN', 'REGIST_DE', 'REGIST_NO', 'HMPG_ADDR', 'SOUND_PROVD_AT', 'SOUND_UTILIIZA_PRICE', 'MOBILE_PROVD_AT', 'LND_AR_VALUE', 'TOTAR_VALUE', 'DSPY_AR_CN', 'DSPY_AR_CN.1', 'DSPYRM_ARTFT_CHG_CO', 'SPECL_DSPY_AR_VALUE', 'AR_CN', 'TP_SDIV_NM', 'EDC_FCLTY_AR_VALUE', 'DATA_SPCE_AR_VALUE', 'DATA_CO', 'OFFM_AR_CN', 'CLTUR_GOODS_SPCE_AR_VALUE', 'RSTRNT_AR_VALUE', 'PARKNG_POSBL_CO', 'HDCH_ARTFT_KND_CO', 'HDCH_ARTFT_CAS_CO', 'HDCH_ARTFT_CO', 'CRLTS_NM', 'CRLTS_CO', 'PBLPRFR_CAS_CO', 'TOT_PROGRM_CO', 'PROGRM_CO', 'FDRM_EXPRN_PROGRM_CO', 'NON_FDRM_EXPRN_PROGRM_CO', 'OUT_PROGRM_CO', 'OPNNG_DAY_CO', 'OPNNG_TIME', 'VIEWNG_NMPR_CO', 'DAY_AVRG_VIEWNG_NMPR_CO', 'VIEWNG_PRICE', 'INFN_VIEWNG_PRICE', 'SCHBOY_VIEWNG_PRICE', 'MSKLSD_VIEWNG_PRICE', 'ADULT_VIEWNG_PRICE', 'GRP_DSCNT_RT', 'ETC_DSCNT_RT', 'DSCNT_CN', 'FRE_TRGET_CN', 'SPECL_VIEWNG_PRICE', 'INFN_SPECL_VIEWNG_PRICE', 'SCHBOY_SPECL_VIEWNG_PRICE', 'MSKLSD_SPECL_VIEWNG_PRICE', 'ADULT_SPECL_VIEWNG_PRICE', 'GRP_SPECL_VIEWNG_RT', 'ETC_SPECL_VIEWNG_DSCNT_RT', 'ETC_SPECL_VIEWNG_DSCNT_CN', 'FRE_SPECL_VIEWNG_PRICE', 'NMPR_CO', 'CLTUR_ART_GVRNM_MANAGE_EMP_CO', 'CLTUR_ART_GVRNM_EMP_CO', 'QUALF_HOLD_CO', 'CNTRCT_EMP_CO', 'GNRL_GVRNM_EMP_CO', 'CNTRCT_EMP_CO.1', 'INTN_EMP_CO', 'PUBLIC_VLNTER_CO', 'ARTGR_EMP_CO', 'PRFSN_CO', 'ETC_GNRL_EMP_CO', 'ETC_INTN_EMP_CO', 'PRVATE_VLNTER_CO', 'RM_CN', 'LAST_CHG_DE', 'ORIGIN_NM', 'FILE_NM', 'BASE_DE']

미술관 컬럼
['ID', 'LCLAS_NM', 'MLSFC_NM', 'FCLTY_NM', 'CTPRVN_NM', 'SIGNGU_NM', 'LEGALDONG_CD', 'LEGALDONG_NM', 'ADSTRD_CD', 'ADSTRD_NM', 'RDNMADR_CD', 'RDNMADR_NM', 'ZIP_NO', 'GID_CD', 'FCLTY_LO', 'FCLTY_LA', 'FLAG_NM', 'REGIST_AT', 'TEL_NO', 'OPNNG_DE', 'REGIST_DC', 'REGIST_DE', 'REGIST_NO', 'HMPG_ADDR', 'SOUND_PROVD_AT', 'SOUND_UTILIIZA_PRICE', 'MOBILE_PROVD_AT', 'LND_AR_VALUE', 'BULD_AR_VALUE', 'DSPY_AR_CN', 'AR_CN', 'EDC_FCLTY_AR_VALUE', 'OFFM_AR_CN', 'DATA_SPCE_AR_VALUE', 'DATA_CO', 'PBLPRFR_CAS_CO', 'TOT_PROGRM_CO', 'OPNNG_DAY_CO', 'VIEWNG_NMPR_CO', 'DAY_AVRG_VIEWNG_NMPR_CO', 'VIEWNG_PRICE', 'INFN_VIEWNG_PRICE', 'SCHBOY_VIEWNG_PRICE', 'MSKLSD_VIEWNG_PRICE', 'ADULT_VIEWNG_PRICE', 'GRP_DSCNT_RT', 'ETC_DSCNT_RT', 'DSCNT_CN', 'FRE_TRGET_CN', 'SPECL_VIEWNG_PRICE', 'INFN_SPECL_VIEWNG_PRICE', 'SCHBOY_SPECL_VIEWNG_PRICE', 'MSKLSD_SPECL_VIEWNG_PRICE', 'ADULT_SPECL_VIEWNG_PRICE', 'GRP_SPECL_VIEWNG_RT', 'ETC_SPECL_VIEWNG_DSCNT_RT', 'ETC_SPECL_VIEWNG_DSCNT_CN', 'FRE_SPECL_VIEWNG_PRICE', 'NMPR_CO', 'GVRNM_EMP_SM_CO', 'QUALF_HOLD_CO', 'TOT_CNTRCT_EMP_CO', 'CNTRCT_EMP_CRTFCT_CO', 'GNRL_GVRNM_EMP_CO', 'CNTRCT_EMP_CO', 'PUBLIC_INTN_CO', 'PUBLIC_VLNTER_CO', 'ARTGR_EMP_CO', 'CURTR_QUALF_HOLD_CO', 'CURTR_NTHG_QUALF_HOLD_CO', 'PRFSN_CO', 'GNRL_EMP_CO', 'PRVATE_INTN_CO', 'PRVATE_VLNTER_CO', 'RM_CN', 'LAST_CHG_DE', 'ORIGIN_NM', 'FILE_NM', 'BASE_DE']

#### 01.2 박물관 행수 확인
- 박물관 데이터에 비워있는 부분 발견. 추가 분석

In [182]:
# 1. 전체 컬럼이 전부 비어있는 행 확인
empty_rows = museum[museum.isna().all(axis=1)]

print("전체가 비어있는 행 개수:", len(empty_rows))
display(empty_rows)

전체가 비어있는 행 개수: 0

Empty DataFrame
Columns: [ID, LCLAS_NM, MLSFC_NM, FCLTY_NM, CTPRVN_NM, SIGNGU_NM, LEGALDONG_CD, LEGALDONG_NM, ADSTRD_CD, ADSTRD_NM, RDNMADR_CD, RDNMADR_NM, ZIP_NO, GID_CD, FCLTY_LO, FCLTY_LA, FLAG_NM, BASS_CRSTAT_SDIV_VALUE, TEL_NO, OPNNG_DE, REGIST_CRSTAT_CN, REGIST_DE, REGIST_NO, HMPG_ADDR, SOUND_PROVD_AT, SOUND_UTILIIZA_PRICE, MOBILE_PROVD_AT, LND_AR_VALUE, TOTAR_VALUE, DSPY_AR_CN, DSPY_AR_CN.1, DSPYRM_ARTFT_CHG_CO, SPECL_DSPY_AR_VALUE, AR_CN, TP_SDIV_NM, EDC_FCLTY_AR_VALUE, DATA_SPCE_AR_VALUE, DATA_CO, OFFM_AR_CN, CLTUR_GOODS_SPCE_AR_VALUE, RSTRNT_AR_VALUE, PARKNG_POSBL_CO, HDCH_ARTFT_KND_CO, HDCH_ARTFT_CAS_CO, HDCH_ARTFT_CO, CRLTS_NM, CRLTS_CO, PBLPRFR_CAS_CO, TOT_PROGRM_CO, PROGRM_CO, FDRM_EXPRN_PROGRM_CO, NON_FDRM_EXPRN_PROGRM_CO, OUT_PROGRM_CO, OPNNG_DAY_CO, OPNNG_TIME, VIEWNG_NMPR_CO, DAY_AVRG_VIEWNG_NMPR_CO, VIEWNG_PRICE, INFN_VIEWNG_PRICE, SCHBOY_VIEWNG_PRICE, MSKLSD_VIEWNG_PRICE, ADULT_VIEWNG_PRICE, GRP_DSCNT_RT, ETC_DSCNT_RT, DSCNT_CN, FRE_TRGET_CN, SPECL_VIEWNG_PRICE, INFN_SPECL_VIEWNG_PRICE, SCHBOY_SPECL_VIEWNG_PRICE, MSKLSD_SPECL_VIEWNG_PRICE, ADULT_SPECL_VIEWNG_PRICE, GRP_SPECL_VIEWNG_RT, ETC_SPECL_VIEWNG_DSCNT_RT, ETC_SPECL_VIEWNG_DSCNT_CN, FRE_SPECL_VIEWNG_PRICE, NMPR_CO, CLTUR_ART_GVRNM_MANAGE_EMP_CO, CLTUR_ART_GVRNM_EMP_CO, QUALF_HOLD_CO, CNTRCT_EMP_CO, GNRL_GVRNM_EMP_CO, CNTRCT_EMP_CO.1, INTN_EMP_CO, PUBLIC_VLNTER_CO, ARTGR_EMP_CO, PRFSN_CO, ETC_GNRL_EMP_CO, ETC_INTN_EMP_CO, PRVATE_VLNTER_CO, RM_CN, LAST_CHG_DE, ORIGIN_NM, FILE_NM, BASE_DE]
Index: []

[0 rows x 94 columns]

In [183]:
# 2. ID가 비어있는 행 확인
id_empty_rows = museum[museum["ID"].isna()]

print("ID가 비어있는 행 개수:", len(id_empty_rows))
display(id_empty_rows)

ID가 비어있는 행 개수: 1

,ID,LCLAS_NM,MLSFC_NM,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,LEGALDONG_CD,LEGALDONG_NM,ADSTRD_CD,ADSTRD_NM,...,ARTGR_EMP_CO,PRFSN_CO,ETC_GNRL_EMP_CO,ETC_INTN_EMP_CO,PRVATE_VLNTER_CO,RM_CN,LAST_CHG_DE,ORIGIN_NM,FILE_NM,BASE_DE
897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,20250327,문화데이터총람 2024,KC_477_DMSTC_MCST_MUSEUM_2024,20250327

- 완전 비어있는 행은 아님.
- 마지막 부분 칼럼들에서 값이 존재
  - 하지만 id,지역등 중요한 부분 칼럼이 비어있음 <br>
  - 출처 / 기준일 정보만 남은 행

=> 다수도 아니며 1개만 비어있어 제거

In [184]:
# 시설 ID가 없는 행 제거
museum = museum.dropna(subset=["ID"]).copy()

print("박물관 데이터 크기:", museum.shape)
print("미술관 데이터 크기:", art.shape)

print("박물관 컬럼 수:", len(museum.columns))
print("미술관 컬럼 수:", len(art.columns))

박물관 데이터 크기: (897, 94)
미술관 데이터 크기: (294, 79)
박물관 컬럼 수: 94
미술관 컬럼 수: 79

“박물관 데이터에는 완전 빈 행은 없지만, ID와 시설 정보가 비어 있고 출처 메타데이터만 남은 1개 행이 있다. 따라서 시설 분석에서는 제거한다.”

#### 02.1 분석 후보 컬럼 선정

In [185]:
# 원본 보존용 복사본
museum_raw = museum.copy()
art_raw = art.copy()

print("박물관 데이터:", museum_raw.shape)
print("미술관 데이터:", art_raw.shape)

박물관 데이터: (897, 94)
미술관 데이터: (294, 79)

In [186]:
# 박물관/미술관 공통 컬럼과 개별 컬럼 확인

museum_cols = set(museum_raw.columns)
art_cols = set(art_raw.columns)

common_cols = sorted(list(museum_cols & art_cols))
museum_only_cols = sorted(list(museum_cols - art_cols))
art_only_cols = sorted(list(art_cols - museum_cols))

print("공통 컬럼 수:", len(common_cols))
print("박물관에만 있는 컬럼 수:", len(museum_only_cols))
print("미술관에만 있는 컬럼 수:", len(art_only_cols))

print("\n[공통 컬럼]")
print(common_cols)

print("\n[박물관에만 있는 컬럼]")
print(museum_only_cols)

print("\n[미술관에만 있는 컬럼]")
print(art_only_cols)

공통 컬럼 수: 68
박물관에만 있는 컬럼 수: 26
미술관에만 있는 컬럼 수: 11

[공통 컬럼]
['ADSTRD_CD', 'ADSTRD_NM', 'ADULT_SPECL_VIEWNG_PRICE', 'ADULT_VIEWNG_PRICE', 'ARTGR_EMP_CO', 'AR_CN', 'BASE_DE', 'CNTRCT_EMP_CO', 'CTPRVN_NM', 'DATA_CO', 'DATA_SPCE_AR_VALUE', 'DAY_AVRG_VIEWNG_NMPR_CO', 'DSCNT_CN', 'DSPY_AR_CN', 'EDC_FCLTY_AR_VALUE', 'ETC_DSCNT_RT', 'ETC_SPECL_VIEWNG_DSCNT_CN', 'ETC_SPECL_VIEWNG_DSCNT_RT', 'FCLTY_LA', 'FCLTY_LO', 'FCLTY_NM', 'FILE_NM', 'FLAG_NM', 'FRE_SPECL_VIEWNG_PRICE', 'FRE_TRGET_CN', 'GID_CD', 'GNRL_GVRNM_EMP_CO', 'GRP_DSCNT_RT', 'GRP_SPECL_VIEWNG_RT', 'HMPG_ADDR', 'ID', 'INFN_SPECL_VIEWNG_PRICE', 'INFN_VIEWNG_PRICE', 'LAST_CHG_DE', 'LCLAS_NM', 'LEGALDONG_CD', 'LEGALDONG_NM', 'LND_AR_VALUE', 'MLSFC_NM', 'MOBILE_PROVD_AT', 'MSKLSD_SPECL_VIEWNG_PRICE', 'MSKLSD_VIEWNG_PRICE', 'NMPR_CO', 'OFFM_AR_CN', 'OPNNG_DAY_CO', 'OPNNG_DE', 'ORIGIN_NM', 'PBLPRFR_CAS_CO', 'PRFSN_CO', 'PRVATE_VLNTER_CO', 'PUBLIC_VLNTER_CO', 'QUALF_HOLD_CO', 'RDNMADR_CD', 'RDNMADR_NM', 'REGIST_DE', 'REGIST_NO', 'RM_CN', 'SCHBOY_SPECL_VIEWNG_PRICE', 'SCHBOY_VIEWNG_PRICE', 'SIGNGU_NM', 'SOUND_PROVD_AT', 'SOUND_UTILIIZA_PRICE', 'SPECL_VIEWNG_PRICE', 'TEL_NO', 'TOT_PROGRM_CO', 'VIEWNG_NMPR_CO', 'VIEWNG_PRICE', 'ZIP_NO']

[박물관에만 있는 컬럼]
['BASS_CRSTAT_SDIV_VALUE', 'CLTUR_ART_GVRNM_EMP_CO', 'CLTUR_ART_GVRNM_MANAGE_EMP_CO', 'CLTUR_GOODS_SPCE_AR_VALUE', 'CNTRCT_EMP_CO.1', 'CRLTS_CO', 'CRLTS_NM', 'DSPYRM_ARTFT_CHG_CO', 'DSPY_AR_CN.1', 'ETC_GNRL_EMP_CO', 'ETC_INTN_EMP_CO', 'FDRM_EXPRN_PROGRM_CO', 'HDCH_ARTFT_CAS_CO', 'HDCH_ARTFT_CO', 'HDCH_ARTFT_KND_CO', 'INTN_EMP_CO', 'NON_FDRM_EXPRN_PROGRM_CO', 'OPNNG_TIME', 'OUT_PROGRM_CO', 'PARKNG_POSBL_CO', 'PROGRM_CO', 'REGIST_CRSTAT_CN', 'RSTRNT_AR_VALUE', 'SPECL_DSPY_AR_VALUE', 'TOTAR_VALUE', 'TP_SDIV_NM']

[미술관에만 있는 컬럼]
['BULD_AR_VALUE', 'CNTRCT_EMP_CRTFCT_CO', 'CURTR_NTHG_QUALF_HOLD_CO', 'CURTR_QUALF_HOLD_CO', 'GNRL_EMP_CO', 'GVRNM_EMP_SM_CO', 'PRVATE_INTN_CO', 'PUBLIC_INTN_CO', 'REGIST_AT', 'REGIST_DC', 'TOT_CNTRCT_EMP_CO']

In [187]:
# 분석 목적별 컬럼 후보 직접 선정
# 컬럼 정의서는 코드에 사용하지 않고, 사람이 참고하는 용도로만 둔다.

# 1. 기본 정보 / 위치 정보
basic_cols = [
    "ID", "LCLAS_NM", "MLSFC_NM", "FCLTY_NM",
    "CTPRVN_NM", "SIGNGU_NM", "LEGALDONG_NM", "ADSTRD_NM",
    "RDNMADR_NM", "ZIP_NO", "GID_CD", "FCLTY_LO", "FCLTY_LA",
    "FLAG_NM", "TEL_NO", "OPNNG_DE", "HMPG_ADDR"
]

# 2. 운영 정보
operation_cols = [
    "SOUND_PROVD_AT", "MOBILE_PROVD_AT",
    "OPNNG_DAY_CO", "OPNNG_TIME"
]

# 3. 시설 규모 공통 컬럼
facility_scale_common_cols = [
    "LND_AR_VALUE", "DSPY_AR_CN", "AR_CN",
    "EDC_FCLTY_AR_VALUE", "DATA_SPCE_AR_VALUE", "OFFM_AR_CN"
]

# 4. 박물관에만 있는 시설 규모 컬럼
museum_facility_scale_cols = [
    "TOTAR_VALUE", "DSPYRM_ARTFT_CHG_CO", "SPECL_DSPY_AR_VALUE",
    "TP_SDIV_NM", "CLTUR_GOODS_SPCE_AR_VALUE", "RSTRNT_AR_VALUE",
    "PARKNG_POSBL_CO"
]

# 5. 미술관에만 있는 시설 규모 컬럼
art_facility_scale_cols = [
    "BULD_AR_VALUE"
]

# 6. 자료 / 전시 / 프로그램 공통 컬럼
content_program_common_cols = [
    "DATA_CO", "PBLPRFR_CAS_CO", "TOT_PROGRM_CO"
]

# 7. 박물관에만 있는 자료 / 프로그램 컬럼
museum_content_program_cols = [
    "HDCH_ARTFT_KND_CO", "HDCH_ARTFT_CAS_CO", "HDCH_ARTFT_CO",
    "CRLTS_NM", "CRLTS_CO",
    "PROGRM_CO", "FDRM_EXPRN_PROGRM_CO", 
    "NON_FDRM_EXPRN_PROGRM_CO", "OUT_PROGRM_CO"
]

# 8. 이용 성과 컬럼
performance_cols = [
    "VIEWNG_NMPR_CO", "DAY_AVRG_VIEWNG_NMPR_CO"
]

# 9. 관람료 컬럼
price_cols = [
    "VIEWNG_PRICE", "INFN_VIEWNG_PRICE", "SCHBOY_VIEWNG_PRICE",
    "MSKLSD_VIEWNG_PRICE", "ADULT_VIEWNG_PRICE",
    "SPECL_VIEWNG_PRICE", "INFN_SPECL_VIEWNG_PRICE",
    "SCHBOY_SPECL_VIEWNG_PRICE", "MSKLSD_SPECL_VIEWNG_PRICE",
    "ADULT_SPECL_VIEWNG_PRICE",
    "FRE_TRGET_CN"
]

# 10. 인력 컬럼 공통 후보
common_employee_cols = [
    "NMPR_CO", "QUALF_HOLD_CO", "GNRL_GVRNM_EMP_CO",
    "CNTRCT_EMP_CO", "PUBLIC_VLNTER_CO",
    "ARTGR_EMP_CO", "PRFSN_CO", "PRVATE_VLNTER_CO"
]

# 11. 박물관 인력 컬럼
museum_employee_cols = [
    "CLTUR_ART_GVRNM_MANAGE_EMP_CO", "CLTUR_ART_GVRNM_EMP_CO",
    "INTN_EMP_CO", "ETC_GNRL_EMP_CO", "ETC_INTN_EMP_CO"
]

# 12. 미술관 인력 컬럼
art_employee_cols = [
    "GVRNM_EMP_SM_CO", "TOT_CNTRCT_EMP_CO", "CNTRCT_EMP_CRTFCT_CO",
    "PUBLIC_INTN_CO", "CURTR_QUALF_HOLD_CO", "CURTR_NTHG_QUALF_HOLD_CO",
    "GNRL_EMP_CO", "PRVATE_INTN_CO"
]

# 13. 메타데이터
metadata_cols = [
    "LAST_CHG_DE", "ORIGIN_NM", "FILE_NM", "BASE_DE"
]

In [188]:
# 공통 분석 후보 컬럼
common_analysis_cols = (
    basic_cols
    + operation_cols
    + facility_scale_common_cols
    + content_program_common_cols
    + performance_cols
    + price_cols
    + common_employee_cols
    + metadata_cols
)

# 박물관 분석 후보 컬럼
museum_analysis_cols = (
    common_analysis_cols
    + museum_facility_scale_cols
    + museum_content_program_cols
    + museum_employee_cols
)

# 미술관 분석 후보 컬럼
art_analysis_cols = (
    common_analysis_cols
    + art_facility_scale_cols
    + art_employee_cols
)

In [189]:
# 실제 데이터에 존재하는 컬럼만 선택하는 함수

def select_existing_columns(df, col_list):
    selected_cols = [col for col in col_list if col in df.columns]
    missing_cols = [col for col in col_list if col not in df.columns]
    
    return selected_cols, missing_cols


museum_selected_cols, museum_missing_cols = select_existing_columns(museum, museum_analysis_cols)
art_selected_cols, art_missing_cols = select_existing_columns(art, art_analysis_cols)

print("박물관 선택 컬럼 수:", len(museum_selected_cols))
print("미술관 선택 컬럼 수:", len(art_selected_cols))

print("\n[박물관 데이터에 없는 후보 컬럼]")
print(museum_missing_cols)

print("\n[미술관 데이터에 없는 후보 컬럼]")
print(art_missing_cols)

박물관 선택 컬럼 수: 76
미술관 선택 컬럼 수: 63

[박물관 데이터에 없는 후보 컬럼]
[]

[미술관 데이터에 없는 후보 컬럼]
['OPNNG_TIME']

In [190]:
# 분석용 데이터셋 생성

museum_basic = museum[museum_selected_cols].copy()
art_basic = art[art_selected_cols].copy()

# 시설 유형 구분 컬럼 추가
museum_basic["facility_type"] = "박물관"
art_basic["facility_type"] = "미술관"

print("박물관 분석용 데이터:", museum_basic.shape)
print("미술관 분석용 데이터:", art_basic.shape)

display(museum_basic.head())
display(art_basic.head())

박물관 분석용 데이터: (897, 77)
미술관 분석용 데이터: (294, 64)

,ID,LCLAS_NM,MLSFC_NM,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,LEGALDONG_NM,ADSTRD_NM,RDNMADR_NM,ZIP_NO,...,PROGRM_CO,FDRM_EXPRN_PROGRM_CO,NON_FDRM_EXPRN_PROGRM_CO,OUT_PROGRM_CO,CLTUR_ART_GVRNM_MANAGE_EMP_CO,CLTUR_ART_GVRNM_EMP_CO,INTN_EMP_CO,ETC_GNRL_EMP_CO,ETC_INTN_EMP_CO,facility_type
0,KCDMMUS23N000000001,문화시설,박물관,국립중앙박물관,서울,용산구,용산동6가,한강로동,서울 용산구 서빙고로 137,4383.0,...,4.0,4.0,7.0,1.0,32.0,52.0,9.0,NaN,NaN,박물관
1,KCDMMUS23N000000002,문화시설,박물관,국립민속박물관,서울,종로구,세종로,청운효자동,서울 종로구 삼청로 37,3045.0,...,13.0,48.0,9.0,NaN,15.0,34.0,5.0,NaN,NaN,박물관
2,KCDMMUS23N000000003,문화시설,박물관,국립민속박물관 파주\n(개방형 수장고 및 정보센터),경기,파주시,탄현면 법흥리,탄현면,경기 파주시 탄현면 헤이리로 30,10859.0,...,NaN,8.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,박물관
3,KCDMMUS23N000000004,문화시설,박물관,대한민국역사박물관,서울,종로구,세종로,종로1.2.3.4가동,서울 종로구 세종대로 198,3141.0,...,34.0,NaN,NaN,NaN,11.0,17.0,NaN,NaN,NaN,박물관
4,KCDMMUS23N000000005,문화시설,박물관,국립한글박물관,서울,용산구,용산동6가,서빙고동,서울 용산구 서빙고로 139,4383.0,...,1.0,5.0,27.0,NaN,4.0,16.0,NaN,NaN,NaN,박물관

,ID,LCLAS_NM,MLSFC_NM,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,LEGALDONG_NM,ADSTRD_NM,RDNMADR_NM,ZIP_NO,...,BULD_AR_VALUE,GVRNM_EMP_SM_CO,TOT_CNTRCT_EMP_CO,CNTRCT_EMP_CRTFCT_CO,PUBLIC_INTN_CO,CURTR_QUALF_HOLD_CO,CURTR_NTHG_QUALF_HOLD_CO,GNRL_EMP_CO,PRVATE_INTN_CO,facility_type
0,KCDMART25N000000001,문화시설,미술관,국립현대미술관(과천관),경기,과천시,막계동,문원동,경기도 과천시 광명로 313,13829,...,"37,797",85,52.0,24.0,18.0,NaN,NaN,NaN,NaN,미술관
1,KCDMART25N000000002,문화시설,미술관,국립현대미술관(서울관),서울,종로구,소격동,삼청동,서울특별시 종로구 삼청로 30,3062,...,"52,125",85,52.0,24.0,18.0,NaN,NaN,NaN,NaN,미술관
2,KCDMART25N000000003,문화시설,미술관,국립현대미술관(덕수궁관),서울,중구,정동,소공동,서울특별시 중구 세종대로 99,4519,...,"2,247",85,52.0,24.0,18.0,NaN,NaN,NaN,NaN,미술관
3,KCDMART25N000000004,문화시설,미술관,국립현대미술관 미술품수장센터(청주관),충북,청주시,내덕동,내덕2동,충청북도 청주시 청원구 상당로 314,28501,...,"19,865",85,52.0,24.0,18.0,NaN,NaN,NaN,NaN,미술관
4,KCDMART25N000000005,문화시설,미술관,DDP디자인뮤지엄,서울,중구,을지로7가,광희동,서울특별시 중구 을지로 281,4566,...,"82,464",0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,미술관

지금까지 진행<br>

라이브러리
→ 파일 로드
→ 기본 정보 확인
→ 박물관 ID 결측 행 확인
→ ID 없는 1행 제거
→ 분석 후보 컬럼 선정
→ museum_basic / art_basic 생성

##### 중복명 처리

In [191]:
# 박물관 데이터의 중복명 처리 컬럼 확인
duplicate_like_cols = [
    col for col in museum.columns
    if ".1" in col
]

print("박물관의 중복 처리된 컬럼:")
print(duplicate_like_cols)

display(museum[["DSPY_AR_CN", "DSPY_AR_CN.1", "CNTRCT_EMP_CO", "CNTRCT_EMP_CO.1"]].head())

박물관의 중복 처리된 컬럼:
['DSPY_AR_CN.1', 'CNTRCT_EMP_CO.1']

   DSPY_AR_CN  DSPY_AR_CN.1  CNTRCT_EMP_CO  CNTRCT_EMP_CO.1
0    37651.00      33969.00            NaN             11.0
1     5874.43       5094.65            8.0              8.0
2         NaN           NaN            NaN              NaN
3     3539.00       3042.40            4.0              NaN
4     2190.00       1240.00           13.0              3.0

- 중복 처리된 컬럼은 분석 대상에서 제외 예정
- 별도 컬럼명 수정은 진행하지 않음

##### 박물관에서 `DSPY_AR_CN`, `CNTRCT_EMP_CO` 컬럼이 중복되어 pandas에서 일부 컬럼명이 `.1` 형태로 자동 변경된 것을 확인

- `DSPY_AR_CN`: 전시면적내용
- `DSPY_AR_CN.1`: 전시면적내용 중복 컬럼
- `CNTRCT_EMP_CO`: 학예인력 계약직 등 비정규직
- `CNTRCT_EMP_CO.1`: 일반인력 계약직 등 비정규직(g)

`DSPY_AR_CN`, `CNTRCT_EMP_CO`는 현재 1차 분석 후보 데이터셋에는 포함되어 있으나, 본 분석의 핵심 변수로 사용하지 않을 예정이므로 이후 전처리 단계에서 제거 여부를 확정한다. `.1` 형태로 자동 변경된 중복명 컬럼은 별도로 수정하지 않고 분석 대상에서 제외한다.

#### 02.2 결측치 비율 확인

In [192]:
# 결측치 비율 확인 함수

def missing_summary(df):
    missing_df = pd.DataFrame({
        "column": df.columns,
        "missing_count": df.isna().sum().values,
        "missing_rate": (df.isna().mean().values * 100).round(2),
        "non_missing_count": df.notna().sum().values,
        "dtype": df.dtypes.astype(str).values,
        "unique_count": df.nunique(dropna=True).values
    })
    
    missing_df = missing_df.sort_values(
        by=["missing_rate", "missing_count"],
        ascending=False
    ).reset_index(drop=True)
    
    return missing_df

In [193]:
museum_missing = missing_summary(museum_basic)
art_missing = missing_summary(art_basic)

print("박물관 결측치 요약")
display(museum_missing)

print("미술관 결측치 요약")
display(art_missing)

박물관 결측치 요약

,column,missing_count,missing_rate,non_missing_count,dtype,unique_count
0,INTN_EMP_CO,867,96.66,30,float64,6
1,INFN_SPECL_VIEWNG_PRICE,835,93.09,62,float64,14
2,CLTUR_ART_GVRNM_MANAGE_EMP_CO,834,92.98,63,float64,10
3,ETC_INTN_EMP_CO,834,92.98,63,float64,10
4,PRVATE_VLNTER_CO,811,90.41,86,float64,26
...,...,...,...,...,...,...
72,LAST_CHG_DE,0,0.00,897,int64,1
73,ORIGIN_NM,0,0.00,897,str,1
74,FILE_NM,0,0.00,897,str,1
75,BASE_DE,0,0.00,897,int64,1
76,facility_type,0,0.00,897,str,1

미술관 결측치 요약

,column,missing_count,missing_rate,non_missing_count,dtype,unique_count
0,AR_CN,294,100.00,0,float64,0
1,PUBLIC_INTN_CO,280,95.24,14,float64,4
2,PRVATE_VLNTER_CO,263,89.46,31,float64,13
3,PRVATE_INTN_CO,261,88.78,33,float64,5
4,CNTRCT_EMP_CRTFCT_CO,260,88.44,34,float64,8
...,...,...,...,...,...,...
59,ORIGIN_NM,0,0.00,294,str,1
60,FILE_NM,0,0.00,294,str,1
61,BASE_DE,0,0.00,294,int64,1
62,GVRNM_EMP_SM_CO,0,0.00,294,int64,16
63,facility_type,0,0.00,294,str,1

In [194]:
print("박물관 결측치가 있는 컬럼")
display(museum_missing[museum_missing["missing_count"] > 0])

print("미술관 결측치가 있는 컬럼")
display(art_missing[art_missing["missing_count"] > 0])

박물관 결측치가 있는 컬럼

,column,missing_count,missing_rate,non_missing_count,dtype,unique_count
0,INTN_EMP_CO,867,96.66,30,float64,6
1,INFN_SPECL_VIEWNG_PRICE,835,93.09,62,float64,14
2,CLTUR_ART_GVRNM_MANAGE_EMP_CO,834,92.98,63,float64,10
3,ETC_INTN_EMP_CO,834,92.98,63,float64,10
4,PRVATE_VLNTER_CO,811,90.41,86,float64,26
5,SCHBOY_SPECL_VIEWNG_PRICE,784,87.40,113,str,17
6,ADULT_SPECL_VIEWNG_PRICE,775,86.40,122,float64,16
7,MSKLSD_SPECL_VIEWNG_PRICE,774,86.29,123,str,22
8,CNTRCT_EMP_CO,771,85.95,126,float64,11
9,SPECL_VIEWNG_PRICE,769,85.73,128,str,17
10,PRFSN_CO,761,84.84,136,float64,14
11,QUALF_HOLD_CO,755,84.17,142,float64,11
12,PUBLIC_VLNTER_CO,754,84.06,143,float64,70
13,OUT_PROGRM_CO,726,80.94,171,float64,10
14,INFN_VIEWNG_PRICE,713,79.49,184,float64,26
15,RSTRNT_AR_VALUE,710,79.15,187,float64,133
16,ETC_GNRL_EMP_CO,668,74.47,229,float64,26
17,CLTUR_GOODS_SPCE_AR_VALUE,664,74.02,233,float64,142
18,GNRL_GVRNM_EMP_CO,647,72.13,250,float64,27
19,CLTUR_ART_GVRNM_EMP_CO,632,70.46,265,float64,18
20,CRLTS_NM,615,68.56,282,str,278
21,CRLTS_CO,615,68.56,282,str,225
22,SCHBOY_VIEWNG_PRICE,576,64.21,321,float64,32
23,ARTGR_EMP_CO,564,62.88,333,float64,14
24,MSKLSD_VIEWNG_PRICE,562,62.65,335,str,36
25,ADULT_VIEWNG_PRICE,560,62.43,337,float64,36
26,VIEWNG_PRICE,554,61.76,343,str,32
27,NMPR_CO,541,60.31,356,float64,29
28,PROGRM_CO,523,58.31,374,float64,22
29,NON_FDRM_EXPRN_PROGRM_CO,399,44.48,498,float64,33
30,DATA_CO,394,43.92,503,float64,338
31,DATA_SPCE_AR_VALUE,392,43.70,505,float64,243
32,FDRM_EXPRN_PROGRM_CO,373,41.58,524,float64,26
33,SPECL_DSPY_AR_VALUE,291,32.44,606,str,391
34,PBLPRFR_CAS_CO,257,28.65,640,str,29
35,EDC_FCLTY_AR_VALUE,242,26.98,655,float64,404
36,TOT_PROGRM_CO,216,24.08,681,float64,53
37,HDCH_ARTFT_CAS_CO,154,17.17,743,str,611
38,DSPYRM_ARTFT_CHG_CO,139,15.50,758,str,65
39,PARKNG_POSBL_CO,123,13.71,774,str,279
40,FRE_TRGET_CN,86,9.59,811,str,255
41,HMPG_ADDR,76,8.47,821,str,784
42,OFFM_AR_CN,60,6.69,837,float64,387
43,TP_SDIV_NM,59,6.58,838,str,2
44,AR_CN,50,5.57,847,float64,470
45,OPNNG_DAY_CO,41,4.57,856,float64,166
46,VIEWNG_NMPR_CO,41,4.57,856,float64,770
47,DAY_AVRG_VIEWNG_NMPR_CO,41,4.57,856,float64,389
48,OPNNG_TIME,24,2.68,873,str,129
49,HDCH_ARTFT_CO,23,2.56,874,str,760
50,HDCH_ARTFT_KND_CO,21,2.34,876,str,795
51,TOTAR_VALUE,12,1.34,885,float64,823
52,LND_AR_VALUE,11,1.23,886,float64,849
53,MOBILE_PROVD_AT,9,1.00,888,str,2
54,SOUND_PROVD_AT,8,0.89,889,str,2
55,DSPY_AR_CN,8,0.89,889,float64,758
56,TEL_NO,4,0.45,893,str,884

미술관 결측치가 있는 컬럼

,column,missing_count,missing_rate,non_missing_count,dtype,unique_count
0,AR_CN,294,100.00,0,float64,0
1,PUBLIC_INTN_CO,280,95.24,14,float64,4
2,PRVATE_VLNTER_CO,263,89.46,31,float64,13
3,PRVATE_INTN_CO,261,88.78,33,float64,5
4,CNTRCT_EMP_CRTFCT_CO,260,88.44,34,float64,8
5,TOT_CNTRCT_EMP_CO,256,87.07,38,float64,12
6,GNRL_GVRNM_EMP_CO,254,86.39,40,float64,16
7,PUBLIC_VLNTER_CO,254,86.39,40,str,29
8,CNTRCT_EMP_CO,248,84.35,46,float64,9
9,PRFSN_CO,222,75.51,72,float64,5
10,CURTR_NTHG_QUALF_HOLD_CO,222,75.51,72,float64,5
11,ADULT_VIEWNG_PRICE,198,67.35,96,str,27
12,INFN_VIEWNG_PRICE,197,67.01,97,str,20
13,SCHBOY_VIEWNG_PRICE,197,67.01,97,str,25
14,MSKLSD_VIEWNG_PRICE,197,67.01,97,str,23
15,VIEWNG_PRICE,196,66.67,98,str,24
16,INFN_SPECL_VIEWNG_PRICE,182,61.90,112,str,20
17,SCHBOY_SPECL_VIEWNG_PRICE,182,61.90,112,str,28
18,MSKLSD_SPECL_VIEWNG_PRICE,182,61.90,112,str,28
19,ADULT_SPECL_VIEWNG_PRICE,182,61.90,112,str,26
20,GNRL_EMP_CO,180,61.22,114,float64,15
21,SPECL_VIEWNG_PRICE,177,60.20,117,str,29
22,DATA_CO,134,45.58,160,str,103
23,DATA_SPCE_AR_VALUE,118,40.14,176,float64,100
24,CURTR_QUALF_HOLD_CO,115,39.12,179,float64,13
25,EDC_FCLTY_AR_VALUE,89,30.27,205,str,144
26,ARTGR_EMP_CO,84,28.57,210,float64,35
27,FRE_TRGET_CN,81,27.55,213,str,72
28,TOT_PROGRM_CO,68,23.13,226,float64,36
29,PBLPRFR_CAS_CO,30,10.20,264,str,36
30,HMPG_ADDR,18,6.12,276,str,268
31,OFFM_AR_CN,17,5.78,277,str,141
32,BULD_AR_VALUE,3,1.02,291,str,273
33,LND_AR_VALUE,2,0.68,292,str,280

In [195]:
# 결측치 비율 구간별 컬럼 확인

def check_missing_groups(missing_df, dataset_name):
    print(f"[{dataset_name}] 결측치 70% 이상 컬럼")
    display(missing_df[missing_df["missing_rate"] >= 70])
    
    print(f"[{dataset_name}] 결측치 30% 이상 70% 미만 컬럼")
    display(missing_df[
        (missing_df["missing_rate"] >= 30) & 
        (missing_df["missing_rate"] < 70)
    ])
    
    print(f"[{dataset_name}] 결측치 0% 초과 30% 미만 컬럼")
    display(missing_df[
        (missing_df["missing_rate"] > 0) & 
        (missing_df["missing_rate"] < 30)
    ])


check_missing_groups(museum_missing, "박물관")
check_missing_groups(art_missing, "미술관")

[박물관] 결측치 70% 이상 컬럼

,column,missing_count,missing_rate,non_missing_count,dtype,unique_count
0,INTN_EMP_CO,867,96.66,30,float64,6
1,INFN_SPECL_VIEWNG_PRICE,835,93.09,62,float64,14
2,CLTUR_ART_GVRNM_MANAGE_EMP_CO,834,92.98,63,float64,10
3,ETC_INTN_EMP_CO,834,92.98,63,float64,10
4,PRVATE_VLNTER_CO,811,90.41,86,float64,26
5,SCHBOY_SPECL_VIEWNG_PRICE,784,87.40,113,str,17
6,ADULT_SPECL_VIEWNG_PRICE,775,86.40,122,float64,16
7,MSKLSD_SPECL_VIEWNG_PRICE,774,86.29,123,str,22
8,CNTRCT_EMP_CO,771,85.95,126,float64,11
9,SPECL_VIEWNG_PRICE,769,85.73,128,str,17
10,PRFSN_CO,761,84.84,136,float64,14
11,QUALF_HOLD_CO,755,84.17,142,float64,11
12,PUBLIC_VLNTER_CO,754,84.06,143,float64,70
13,OUT_PROGRM_CO,726,80.94,171,float64,10
14,INFN_VIEWNG_PRICE,713,79.49,184,float64,26
15,RSTRNT_AR_VALUE,710,79.15,187,float64,133
16,ETC_GNRL_EMP_CO,668,74.47,229,float64,26
17,CLTUR_GOODS_SPCE_AR_VALUE,664,74.02,233,float64,142
18,GNRL_GVRNM_EMP_CO,647,72.13,250,float64,27
19,CLTUR_ART_GVRNM_EMP_CO,632,70.46,265,float64,18

[박물관] 결측치 30% 이상 70% 미만 컬럼

,column,missing_count,missing_rate,non_missing_count,dtype,unique_count
20,CRLTS_NM,615,68.56,282,str,278
21,CRLTS_CO,615,68.56,282,str,225
22,SCHBOY_VIEWNG_PRICE,576,64.21,321,float64,32
23,ARTGR_EMP_CO,564,62.88,333,float64,14
24,MSKLSD_VIEWNG_PRICE,562,62.65,335,str,36
25,ADULT_VIEWNG_PRICE,560,62.43,337,float64,36
26,VIEWNG_PRICE,554,61.76,343,str,32
27,NMPR_CO,541,60.31,356,float64,29
28,PROGRM_CO,523,58.31,374,float64,22
29,NON_FDRM_EXPRN_PROGRM_CO,399,44.48,498,float64,33
30,DATA_CO,394,43.92,503,float64,338
31,DATA_SPCE_AR_VALUE,392,43.70,505,float64,243
32,FDRM_EXPRN_PROGRM_CO,373,41.58,524,float64,26
33,SPECL_DSPY_AR_VALUE,291,32.44,606,str,391

[박물관] 결측치 0% 초과 30% 미만 컬럼

,column,missing_count,missing_rate,non_missing_count,dtype,unique_count
34,PBLPRFR_CAS_CO,257,28.65,640,str,29
35,EDC_FCLTY_AR_VALUE,242,26.98,655,float64,404
36,TOT_PROGRM_CO,216,24.08,681,float64,53
37,HDCH_ARTFT_CAS_CO,154,17.17,743,str,611
38,DSPYRM_ARTFT_CHG_CO,139,15.50,758,str,65
39,PARKNG_POSBL_CO,123,13.71,774,str,279
40,FRE_TRGET_CN,86,9.59,811,str,255
41,HMPG_ADDR,76,8.47,821,str,784
42,OFFM_AR_CN,60,6.69,837,float64,387
43,TP_SDIV_NM,59,6.58,838,str,2
44,AR_CN,50,5.57,847,float64,470
45,OPNNG_DAY_CO,41,4.57,856,float64,166
46,VIEWNG_NMPR_CO,41,4.57,856,float64,770
47,DAY_AVRG_VIEWNG_NMPR_CO,41,4.57,856,float64,389
48,OPNNG_TIME,24,2.68,873,str,129
49,HDCH_ARTFT_CO,23,2.56,874,str,760
50,HDCH_ARTFT_KND_CO,21,2.34,876,str,795
51,TOTAR_VALUE,12,1.34,885,float64,823
52,LND_AR_VALUE,11,1.23,886,float64,849
53,MOBILE_PROVD_AT,9,1.00,888,str,2
54,SOUND_PROVD_AT,8,0.89,889,str,2
55,DSPY_AR_CN,8,0.89,889,float64,758
56,TEL_NO,4,0.45,893,str,884

[미술관] 결측치 70% 이상 컬럼

,column,missing_count,missing_rate,non_missing_count,dtype,unique_count
0,AR_CN,294,100.00,0,float64,0
1,PUBLIC_INTN_CO,280,95.24,14,float64,4
2,PRVATE_VLNTER_CO,263,89.46,31,float64,13
3,PRVATE_INTN_CO,261,88.78,33,float64,5
4,CNTRCT_EMP_CRTFCT_CO,260,88.44,34,float64,8
5,TOT_CNTRCT_EMP_CO,256,87.07,38,float64,12
6,GNRL_GVRNM_EMP_CO,254,86.39,40,float64,16
7,PUBLIC_VLNTER_CO,254,86.39,40,str,29
8,CNTRCT_EMP_CO,248,84.35,46,float64,9
9,PRFSN_CO,222,75.51,72,float64,5
10,CURTR_NTHG_QUALF_HOLD_CO,222,75.51,72,float64,5

[미술관] 결측치 30% 이상 70% 미만 컬럼

,column,missing_count,missing_rate,non_missing_count,dtype,unique_count
11,ADULT_VIEWNG_PRICE,198,67.35,96,str,27
12,INFN_VIEWNG_PRICE,197,67.01,97,str,20
13,SCHBOY_VIEWNG_PRICE,197,67.01,97,str,25
14,MSKLSD_VIEWNG_PRICE,197,67.01,97,str,23
15,VIEWNG_PRICE,196,66.67,98,str,24
16,INFN_SPECL_VIEWNG_PRICE,182,61.90,112,str,20
17,SCHBOY_SPECL_VIEWNG_PRICE,182,61.90,112,str,28
18,MSKLSD_SPECL_VIEWNG_PRICE,182,61.90,112,str,28
19,ADULT_SPECL_VIEWNG_PRICE,182,61.90,112,str,26
20,GNRL_EMP_CO,180,61.22,114,float64,15
21,SPECL_VIEWNG_PRICE,177,60.20,117,str,29
22,DATA_CO,134,45.58,160,str,103
23,DATA_SPCE_AR_VALUE,118,40.14,176,float64,100
24,CURTR_QUALF_HOLD_CO,115,39.12,179,float64,13
25,EDC_FCLTY_AR_VALUE,89,30.27,205,str,144

[미술관] 결측치 0% 초과 30% 미만 컬럼

,column,missing_count,missing_rate,non_missing_count,dtype,unique_count
26,ARTGR_EMP_CO,84,28.57,210,float64,35
27,FRE_TRGET_CN,81,27.55,213,str,72
28,TOT_PROGRM_CO,68,23.13,226,float64,36
29,PBLPRFR_CAS_CO,30,10.20,264,str,36
30,HMPG_ADDR,18,6.12,276,str,268
31,OFFM_AR_CN,17,5.78,277,str,141
32,BULD_AR_VALUE,3,1.02,291,str,273
33,LND_AR_VALUE,2,0.68,292,str,280

- AR_CN
  - 미술관 결측치 100%
  - 박물관은 결측치가 5.57%
  - 면적 내용을  공통 변수로 사용하기 어려움
  - 제거하는 방향으로 진행

In [196]:
# 중복명 처리 관련 컬럼의 분석용 데이터 포함 여부 확인

duplicate_check_cols = [
    "DSPY_AR_CN", "DSPY_AR_CN.1",
    "CNTRCT_EMP_CO", "CNTRCT_EMP_CO.1"
]

print("[박물관 분석용 데이터 포함 여부]")
for col in duplicate_check_cols:
    print(col, ":", col in museum_basic.columns)

[박물관 분석용 데이터 포함 여부]
DSPY_AR_CN : True
DSPY_AR_CN.1 : False
CNTRCT_EMP_CO : True
CNTRCT_EMP_CO.1 : False

#### 02.3 결측치 처리 기준 정리

In [197]:
# 결측치 비율에 따른 1차 처리 기준 생성 함수

def add_missing_decision(missing_df):
    missing_df = missing_df.copy()
    
    def decide(row):
        rate = row["missing_rate"]
        
        if rate == 100:
            return "제거 후보"
        elif rate >= 70:
            return "보류/제거 후보"
        elif rate >= 30:
            return "의미 검토 필요"
        elif rate > 0:
            return "결측 처리 후 사용 가능"
        else:
            return "유지 가능"
    
    missing_df["missing_decision"] = missing_df.apply(decide, axis=1)
    
    return missing_df


museum_missing_decision = add_missing_decision(museum_missing)
art_missing_decision = add_missing_decision(art_missing)

print("박물관 결측치 처리 기준")
display(museum_missing_decision)

print("미술관 결측치 처리 기준")
display(art_missing_decision)

박물관 결측치 처리 기준

,column,missing_count,missing_rate,non_missing_count,dtype,unique_count,missing_decision
0,INTN_EMP_CO,867,96.66,30,float64,6,보류/제거 후보
1,INFN_SPECL_VIEWNG_PRICE,835,93.09,62,float64,14,보류/제거 후보
2,CLTUR_ART_GVRNM_MANAGE_EMP_CO,834,92.98,63,float64,10,보류/제거 후보
3,ETC_INTN_EMP_CO,834,92.98,63,float64,10,보류/제거 후보
4,PRVATE_VLNTER_CO,811,90.41,86,float64,26,보류/제거 후보
...,...,...,...,...,...,...,...
72,LAST_CHG_DE,0,0.00,897,int64,1,유지 가능
73,ORIGIN_NM,0,0.00,897,str,1,유지 가능
74,FILE_NM,0,0.00,897,str,1,유지 가능
75,BASE_DE,0,0.00,897,int64,1,유지 가능
76,facility_type,0,0.00,897,str,1,유지 가능

미술관 결측치 처리 기준

,column,missing_count,missing_rate,non_missing_count,dtype,unique_count,missing_decision
0,AR_CN,294,100.00,0,float64,0,제거 후보
1,PUBLIC_INTN_CO,280,95.24,14,float64,4,보류/제거 후보
2,PRVATE_VLNTER_CO,263,89.46,31,float64,13,보류/제거 후보
3,PRVATE_INTN_CO,261,88.78,33,float64,5,보류/제거 후보
4,CNTRCT_EMP_CRTFCT_CO,260,88.44,34,float64,8,보류/제거 후보
...,...,...,...,...,...,...,...
59,ORIGIN_NM,0,0.00,294,str,1,유지 가능
60,FILE_NM,0,0.00,294,str,1,유지 가능
61,BASE_DE,0,0.00,294,int64,1,유지 가능
62,GVRNM_EMP_SM_CO,0,0.00,294,int64,16,유지 가능
63,facility_type,0,0.00,294,str,1,유지 가능

In [198]:
print("[박물관 결측치 처리 기준별 컬럼 수]")
display(museum_missing_decision["missing_decision"].value_counts())

print("[미술관 결측치 처리 기준별 컬럼 수]")
display(art_missing_decision["missing_decision"].value_counts())

[박물관 결측치 처리 기준별 컬럼 수]

missing_decision
결측 처리 후 사용 가능    23
보류/제거 후보         20
유지 가능            20
의미 검토 필요         14
Name: count, dtype: int64

[미술관 결측치 처리 기준별 컬럼 수]

missing_decision
유지 가능            30
의미 검토 필요         15
보류/제거 후보         10
결측 처리 후 사용 가능     8
제거 후보             1
Name: count, dtype: int64

In [199]:
print("[박물관 제거/보류 후보]")
display(
    museum_missing_decision[
        museum_missing_decision["missing_decision"].isin(["제거 후보", "보류/제거 후보"])
    ]
)

print("[미술관 제거/보류 후보]")
display(
    art_missing_decision[
        art_missing_decision["missing_decision"].isin(["제거 후보", "보류/제거 후보"])
    ]
)

[박물관 제거/보류 후보]

,column,missing_count,missing_rate,non_missing_count,dtype,unique_count,missing_decision
0,INTN_EMP_CO,867,96.66,30,float64,6,보류/제거 후보
1,INFN_SPECL_VIEWNG_PRICE,835,93.09,62,float64,14,보류/제거 후보
2,CLTUR_ART_GVRNM_MANAGE_EMP_CO,834,92.98,63,float64,10,보류/제거 후보
3,ETC_INTN_EMP_CO,834,92.98,63,float64,10,보류/제거 후보
4,PRVATE_VLNTER_CO,811,90.41,86,float64,26,보류/제거 후보
5,SCHBOY_SPECL_VIEWNG_PRICE,784,87.40,113,str,17,보류/제거 후보
6,ADULT_SPECL_VIEWNG_PRICE,775,86.40,122,float64,16,보류/제거 후보
7,MSKLSD_SPECL_VIEWNG_PRICE,774,86.29,123,str,22,보류/제거 후보
8,CNTRCT_EMP_CO,771,85.95,126,float64,11,보류/제거 후보
9,SPECL_VIEWNG_PRICE,769,85.73,128,str,17,보류/제거 후보
10,PRFSN_CO,761,84.84,136,float64,14,보류/제거 후보
11,QUALF_HOLD_CO,755,84.17,142,float64,11,보류/제거 후보
12,PUBLIC_VLNTER_CO,754,84.06,143,float64,70,보류/제거 후보
13,OUT_PROGRM_CO,726,80.94,171,float64,10,보류/제거 후보
14,INFN_VIEWNG_PRICE,713,79.49,184,float64,26,보류/제거 후보
15,RSTRNT_AR_VALUE,710,79.15,187,float64,133,보류/제거 후보
16,ETC_GNRL_EMP_CO,668,74.47,229,float64,26,보류/제거 후보
17,CLTUR_GOODS_SPCE_AR_VALUE,664,74.02,233,float64,142,보류/제거 후보
18,GNRL_GVRNM_EMP_CO,647,72.13,250,float64,27,보류/제거 후보
19,CLTUR_ART_GVRNM_EMP_CO,632,70.46,265,float64,18,보류/제거 후보

[미술관 제거/보류 후보]

,column,missing_count,missing_rate,non_missing_count,dtype,unique_count,missing_decision
0,AR_CN,294,100.00,0,float64,0,제거 후보
1,PUBLIC_INTN_CO,280,95.24,14,float64,4,보류/제거 후보
2,PRVATE_VLNTER_CO,263,89.46,31,float64,13,보류/제거 후보
3,PRVATE_INTN_CO,261,88.78,33,float64,5,보류/제거 후보
4,CNTRCT_EMP_CRTFCT_CO,260,88.44,34,float64,8,보류/제거 후보
5,TOT_CNTRCT_EMP_CO,256,87.07,38,float64,12,보류/제거 후보
6,GNRL_GVRNM_EMP_CO,254,86.39,40,float64,16,보류/제거 후보
7,PUBLIC_VLNTER_CO,254,86.39,40,str,29,보류/제거 후보
8,CNTRCT_EMP_CO,248,84.35,46,float64,9,보류/제거 후보
9,PRFSN_CO,222,75.51,72,float64,5,보류/제거 후보
10,CURTR_NTHG_QUALF_HOLD_CO,222,75.51,72,float64,5,보류/제거 후보

- 확인하는 작업이지, 목표와 먼 칼럼은 결측 비율과 상관없이 삭제

진행사항 <br>

02.2 결측치 비율 확인(완료)
→ 02.3 결측치 처리 기준 정리(완료)
→ 03 자료형 변환
→ 04 이상치 확인
→ EDA

#### 03. 자료형 변환

숫자형 컬럼 쉼표 제거 후 numeric 변환
→ 날짜형 컬럼 변환
→ 변환 전후 dtype 확인
→ 04. 이상치 확인

In [200]:
# 03. 자료형 변환용 데이터 복사본 생성
# 원본 분석용 데이터셋(museum_basic, art_basic)은 보존하고,
# 자료형 변환은 복사본에서 진행한다.

museum_typed = museum_basic.copy()
art_typed = art_basic.copy()

print("박물관 자료형 변환용 데이터:", museum_typed.shape)
print("미술관 자료형 변환용 데이터:", art_typed.shape)

박물관 자료형 변환용 데이터: (897, 77)
미술관 자료형 변환용 데이터: (294, 64)

In [201]:
# 숫자형으로 변환할 가능성이 높은 컬럼 후보
# 단, 실제 변환 전 값 형태를 먼저 확인한다.

numeric_candidate_cols = [
    # 위치 좌표
    "FCLTY_LO", "FCLTY_LA",
    
    # 운영 정보
    "OPNNG_DAY_CO",
    
    # 시설 규모
    "LND_AR_VALUE", "EDC_FCLTY_AR_VALUE", "DATA_SPCE_AR_VALUE",
    "TOTAR_VALUE", "DSPYRM_ARTFT_CHG_CO", "SPECL_DSPY_AR_VALUE",
    "CLTUR_GOODS_SPCE_AR_VALUE", "RSTRNT_AR_VALUE", "PARKNG_POSBL_CO",
    "BULD_AR_VALUE",
    
    # 자료 / 전시 / 프로그램
    "DATA_CO", "PBLPRFR_CAS_CO", "TOT_PROGRM_CO",
    "HDCH_ARTFT_KND_CO", "HDCH_ARTFT_CAS_CO", "HDCH_ARTFT_CO",
    "CRLTS_CO", "PROGRM_CO", "FDRM_EXPRN_PROGRM_CO",
    "NON_FDRM_EXPRN_PROGRM_CO", "OUT_PROGRM_CO",
    
    # 이용 성과
    "VIEWNG_NMPR_CO",
    
    # DAY_AVRG_VIEWNG_NMPR_CO는 나중에 관람객 수 예측 모델에서
    # 데이터 누수 가능성이 있으므로 모델 입력 변수로 사용할 때 주의한다.
    "DAY_AVRG_VIEWNG_NMPR_CO",
    
    # 관람료
    "VIEWNG_PRICE", "INFN_VIEWNG_PRICE", "SCHBOY_VIEWNG_PRICE",
    "MSKLSD_VIEWNG_PRICE", "ADULT_VIEWNG_PRICE",
    "SPECL_VIEWNG_PRICE", "INFN_SPECL_VIEWNG_PRICE",
    "SCHBOY_SPECL_VIEWNG_PRICE", "MSKLSD_SPECL_VIEWNG_PRICE",
    "ADULT_SPECL_VIEWNG_PRICE",
    
    # 인력
    "NMPR_CO", "QUALF_HOLD_CO", "GNRL_GVRNM_EMP_CO",
    "CNTRCT_EMP_CO", "PUBLIC_VLNTER_CO",
    "ARTGR_EMP_CO", "PRFSN_CO", "PRVATE_VLNTER_CO",
    "CLTUR_ART_GVRNM_MANAGE_EMP_CO", "CLTUR_ART_GVRNM_EMP_CO",
    "INTN_EMP_CO", "ETC_GNRL_EMP_CO", "ETC_INTN_EMP_CO",
    "GVRNM_EMP_SM_CO", "TOT_CNTRCT_EMP_CO", "CNTRCT_EMP_CRTFCT_CO",
    "PUBLIC_INTN_CO", "CURTR_QUALF_HOLD_CO", "CURTR_NTHG_QUALF_HOLD_CO",
    "GNRL_EMP_CO", "PRVATE_INTN_CO"
]

# 중복 제거
numeric_candidate_cols = list(dict.fromkeys(numeric_candidate_cols))

# 박물관/미술관 데이터에 실제 존재하는 컬럼만 분리
museum_numeric_cols = [col for col in numeric_candidate_cols if col in museum_typed.columns]
art_numeric_cols = [col for col in numeric_candidate_cols if col in art_typed.columns]

print("박물관 숫자형 변환 후보 컬럼 수:", len(museum_numeric_cols))
print("미술관 숫자형 변환 후보 컬럼 수:", len(art_numeric_cols))

print("\n[박물관 숫자형 변환 후보 컬럼]")
print(museum_numeric_cols)

print("\n[미술관 숫자형 변환 후보 컬럼]")
print(art_numeric_cols)

박물관 숫자형 변환 후보 컬럼 수: 48
미술관 숫자형 변환 후보 컬럼 수: 38

[박물관 숫자형 변환 후보 컬럼]
['FCLTY_LO', 'FCLTY_LA', 'OPNNG_DAY_CO', 'LND_AR_VALUE', 'EDC_FCLTY_AR_VALUE', 'DATA_SPCE_AR_VALUE', 'TOTAR_VALUE', 'DSPYRM_ARTFT_CHG_CO', 'SPECL_DSPY_AR_VALUE', 'CLTUR_GOODS_SPCE_AR_VALUE', 'RSTRNT_AR_VALUE', 'PARKNG_POSBL_CO', 'DATA_CO', 'PBLPRFR_CAS_CO', 'TOT_PROGRM_CO', 'HDCH_ARTFT_KND_CO', 'HDCH_ARTFT_CAS_CO', 'HDCH_ARTFT_CO', 'CRLTS_CO', 'PROGRM_CO', 'FDRM_EXPRN_PROGRM_CO', 'NON_FDRM_EXPRN_PROGRM_CO', 'OUT_PROGRM_CO', 'VIEWNG_NMPR_CO', 'DAY_AVRG_VIEWNG_NMPR_CO', 'VIEWNG_PRICE', 'INFN_VIEWNG_PRICE', 'SCHBOY_VIEWNG_PRICE', 'MSKLSD_VIEWNG_PRICE', 'ADULT_VIEWNG_PRICE', 'SPECL_VIEWNG_PRICE', 'INFN_SPECL_VIEWNG_PRICE', 'SCHBOY_SPECL_VIEWNG_PRICE', 'MSKLSD_SPECL_VIEWNG_PRICE', 'ADULT_SPECL_VIEWNG_PRICE', 'NMPR_CO', 'QUALF_HOLD_CO', 'GNRL_GVRNM_EMP_CO', 'CNTRCT_EMP_CO', 'PUBLIC_VLNTER_CO', 'ARTGR_EMP_CO', 'PRFSN_CO', 'PRVATE_VLNTER_CO', 'CLTUR_ART_GVRNM_MANAGE_EMP_CO', 'CLTUR_ART_GVRNM_EMP_CO', 'INTN_EMP_CO', 'ETC_GNRL_EMP_CO', 'ETC_INTN_EMP_CO']

[미술관 숫자형 변환 후보 컬럼]
['FCLTY_LO', 'FCLTY_LA', 'OPNNG_DAY_CO', 'LND_AR_VALUE', 'EDC_FCLTY_AR_VALUE', 'DATA_SPCE_AR_VALUE', 'BULD_AR_VALUE', 'DATA_CO', 'PBLPRFR_CAS_CO', 'TOT_PROGRM_CO', 'VIEWNG_NMPR_CO', 'DAY_AVRG_VIEWNG_NMPR_CO', 'VIEWNG_PRICE', 'INFN_VIEWNG_PRICE', 'SCHBOY_VIEWNG_PRICE', 'MSKLSD_VIEWNG_PRICE', 'ADULT_VIEWNG_PRICE', 'SPECL_VIEWNG_PRICE', 'INFN_SPECL_VIEWNG_PRICE', 'SCHBOY_SPECL_VIEWNG_PRICE', 'MSKLSD_SPECL_VIEWNG_PRICE', 'ADULT_SPECL_VIEWNG_PRICE', 'NMPR_CO', 'QUALF_HOLD_CO', 'GNRL_GVRNM_EMP_CO', 'CNTRCT_EMP_CO', 'PUBLIC_VLNTER_CO', 'ARTGR_EMP_CO', 'PRFSN_CO', 'PRVATE_VLNTER_CO', 'GVRNM_EMP_SM_CO', 'TOT_CNTRCT_EMP_CO', 'CNTRCT_EMP_CRTFCT_CO', 'PUBLIC_INTN_CO', 'CURTR_QUALF_HOLD_CO', 'CURTR_NTHG_QUALF_HOLD_CO', 'GNRL_EMP_CO', 'PRVATE_INTN_CO']

In [202]:
# 숫자형 변환 전 점검 함수
# 쉼표를 제거한 뒤 numeric 변환이 가능한 비율을 확인한다.
# 이 셀에서는 실제 변환은 하지 않는다.

def numeric_conversion_check(df, cols):
    rows = []
    
    for col in cols:
        s = df[col]
        non_missing_count = s.notna().sum()
        
        cleaned = (
            s.astype("string")
             .str.strip()
             .str.replace(",", "", regex=False)
        )
        
        converted = pd.to_numeric(cleaned, errors="coerce")
        numeric_count = converted.notna().sum()
        
        rows.append({
            "column": col,
            "dtype_before": str(s.dtype),
            "non_missing_count": non_missing_count,
            "numeric_convertible_count": numeric_count,
            "numeric_convertible_rate": round((numeric_count / non_missing_count) * 100, 2) if non_missing_count > 0 else 0,
            "sample_values": " | ".join(s.dropna().astype(str).unique()[:5])
        })
    
    return pd.DataFrame(rows)


museum_numeric_check = numeric_conversion_check(museum_typed, museum_numeric_cols)
art_numeric_check = numeric_conversion_check(art_typed, art_numeric_cols)

print("[박물관 숫자형 변환 후보 점검]")
display(museum_numeric_check)

print("[미술관 숫자형 변환 후보 점검]")
display(art_numeric_check)

[박물관 숫자형 변환 후보 점검]

,column,dtype_before,non_missing_count,numeric_convertible_count,numeric_convertible_rate,sample_values
0,FCLTY_LO,float64,897,897,100.00,126.9777402 | 126.97889 | 126.6939179 | 126.97...
1,FCLTY_LA,float64,897,897,100.00,37.52470224 | 37.58167453 | 37.78666956 | 37.5...
2,OPNNG_DAY_CO,float64,856,856,100.00,360.0 | 362.0 | 313.0 | 312.0 | 306.0
3,LND_AR_VALUE,float64,886,886,100.00,285991.0 | 39626.62 | 60212.7 | 6445.0 | 41338.0
4,EDC_FCLTY_AR_VALUE,float64,655,655,100.00,4975.0 | 1376.68 | 277.49 | 496.0 | 378.0
5,DATA_SPCE_AR_VALUE,float64,505,505,100.00,1552.0 | 324.0 | 81.0 | 220.0 | 254.0
6,TOTAR_VALUE,float64,885,885,100.00,137569.0 | 20048.93 | 10268.29 | 11117.0 | 117...
7,DSPYRM_ARTFT_CHG_CO,str,758,0,0.00,46회/1년 | 10회/1년 | 12회/1년 | 4회/1년 | 1회/7년
8,SPECL_DSPY_AR_VALUE,str,606,605,99.83,3682 | 779.78 | 496.6 | 950 | 300
9,CLTUR_GOODS_SPCE_AR_VALUE,float64,233,233,100.00,639.0 | 56.07 | 52.0 | 194.0 | 67.0
10,RSTRNT_AR_VALUE,float64,187,187,100.00,2780.0 | 43.1 | 53.0 | 15.0 | 72.0
11,PARKNG_POSBL_CO,str,774,682,88.11,862 | 167/9967.94㎡ | 10 | 72 | 227
12,DATA_CO,float64,503,503,100.00,157323.0 | 92786.0 | 18065.0 | 30059.0 | 84732.0
13,PBLPRFR_CAS_CO,str,640,0,0.00,연13회 | 연5회 | 연2회 | 연8회 | 연3회
14,TOT_PROGRM_CO,float64,681,681,100.00,16.0 | 70.0 | 10.0 | 34.0 | 33.0
15,HDCH_ARTFT_KND_CO,str,876,0,0.00,"금속, 토제, 도자기, 서화 등 | 의식주, 생업 등 생활사 자료 | 도서, 전단,..."
16,HDCH_ARTFT_CAS_CO,str,743,742,99.87,214374 | 111604 | 109430 | 27372 | 6770
17,HDCH_ARTFT_CO,str,874,873,99.89,437683 | 178999 | 168890 | 88304 | 28551
18,CRLTS_CO,str,282,2,0.71,"국보 81건, 보물 231건, 국가등록문화재 8건, 국가민속문화재 4건 | 보물13..."
19,PROGRM_CO,float64,374,374,100.00,4.0 | 13.0 | 34.0 | 1.0 | 23.0
20,FDRM_EXPRN_PROGRM_CO,float64,524,524,100.00,4.0 | 48.0 | 8.0 | 5.0 | 2.0
21,NON_FDRM_EXPRN_PROGRM_CO,float64,498,498,100.00,7.0 | 9.0 | 2.0 | 27.0 | 1.0
22,OUT_PROGRM_CO,float64,171,171,100.00,1.0 | 3.0 | 2.0 | 6.0 | 4.0
23,VIEWNG_NMPR_CO,float64,856,856,100.00,4180285.0 | 1307690.0 | 83306.0 | 788347.0 | 3...
24,DAY_AVRG_VIEWNG_NMPR_CO,float64,856,856,100.00,11612.0 | 3612.0 | 266.0 | 2178.0 | 1097.0
25,VIEWNG_PRICE,str,343,342,99.71,1000 | 5000 | 7000 | 3000 | 4000
26,INFN_VIEWNG_PRICE,float64,184,184,100.00,5000.0 | 4000.0 | 10000.0 | 2000.0 | 6000.0
27,SCHBOY_VIEWNG_PRICE,float64,321,321,100.00,5000.0 | 3000.0 | 1000.0 | 4000.0 | 500.0
28,MSKLSD_VIEWNG_PRICE,str,335,332,99.10,5000 | 4000 | 1500 | 500 | 800
29,ADULT_VIEWNG_PRICE,float64,337,337,100.00,5000.0 | 7000.0 | 3000.0 | 4000.0 | 1000.0
30,SPECL_VIEWNG_PRICE,str,128,126,98.44,변동 | 1000 | 3000 | 10000 | 6000
31,INFN_SPECL_VIEWNG_PRICE,float64,62,62,100.00,5000.0 | 6000.0 | 8000.0 | 3000.0 | 1000.0
32,SCHBOY_SPECL_VIEWNG_PRICE,str,113,112,99.12,일반 50% | 1000 | 500 | 5000 | 6000
33,MSKLSD_SPECL_VIEWNG_PRICE,str,123,121,98.37,일반 50% | 1500 | 800 | 500 | 7000
34,ADULT_SPECL_VIEWNG_PRICE,float64,122,122,100.00,3000.0 | 1000.0 | 10000.0 | 6000.0 | 8000.0
35,NMPR_CO,float64,356,356,100.00,89.0 | 58.0 | 55.0 | 33.0 | 3.0
36,QUALF_HOLD_CO,float64,142,142,100.00,5.0 | 1.0 | 23.0 | 3.0 | 12.0
37,GNRL_GVRNM_EMP_CO,float64,250,250,100.00,128.0 | 37.0 | 19.0 | 1.0 | 7.0
38,CNTRCT_EMP_CO,float64,126,126,100.00,8.0 | 4.0 | 13.0 | 1.0 | 5.0
39,PUBLIC_VLNTER_CO,float64,143,143,100.00,213.0 | 81.0 | 37.0 | 54.0 | 64.0
40,ARTGR_EMP_CO,float64,333,333,100.00,2.0 | 14.0 | 8.0 | 1.0 | 4.0
41,PRFSN_CO,float64,136,136,100.00,2.0 | 1.0 | 4.0 | 6.0 | 34.0
42,PRVATE_VLNTER_CO,float64,86,86,100.00,35.0 | 12.0 | 20.0 | 2.0 | 1.0
43,CLTUR_ART_GVRNM_MANAGE_EMP_CO,float64,63,63,100.00,32.0 | 15.0 | 11.0 | 4.0 | 2.0
44,CLTUR_ART_GVRNM_EMP_CO,float64,265,265,100.00,52.0 | 34.0 | 17.0 | 16.0 | 1.0
45,INTN_EMP_CO,float64,30,30,100.00,9.0 | 5.0 | 4.0 | 1.0 | 2.0
46,ETC_GNRL_EMP_CO,float64,229,229,100.00,7.0 | 6.0 | 1.0 | 3.0 | 2.0
47,ETC_INTN_EMP_CO,float64,63,63,100.00,1.0 | 3.0 | 2.0 | 4.0 | 8.0

[미술관 숫자형 변환 후보 점검]

,column,dtype_before,non_missing_count,numeric_convertible_count,numeric_convertible_rate,sample_values
0,FCLTY_LO,float64,294,294,100.00,127.0199299 | 126.9800327 | 126.9737258 | 127....
1,FCLTY_LA,float64,294,294,100.00,37.43100343 | 37.57874362 | 37.56608683 | 36.6...
2,OPNNG_DAY_CO,int64,294,294,100.00,313 | 362 | 174 | 311 | 322
3,LND_AR_VALUE,str,292,291,99.66,"66,916 | 27,264 | 1,181 | 12,077 | 62,109"
4,EDC_FCLTY_AR_VALUE,str,205,205,100.00,"1,162 | 5,641 | 78 | 295 | 1,789"
5,DATA_SPCE_AR_VALUE,float64,176,176,100.00,510.0 | 710.0 | 72.0 | 13.0 | 170.0
6,BULD_AR_VALUE,str,291,291,100.00,"37,797 | 52,125 | 2,247 | 19,865 | 82,464"
7,DATA_CO,str,160,160,100.00,"69,358 | 44,409 | 4,120 | 2,648 | 46,622"
8,PBLPRFR_CAS_CO,str,264,0,0.00,연6회 | 연10회 | 연1회 | 연2회 | 연15회
9,TOT_PROGRM_CO,float64,226,226,100.00,28.0 | 88.0 | 1.0 | 16.0 | 15.0
10,VIEWNG_NMPR_CO,str,294,281,95.58,"562,604 | 1,655,834 | 459,146 | 269,870 | 855,433"
11,DAY_AVRG_VIEWNG_NMPR_CO,str,294,281,95.58,"1,797 | 4,574 | 2,639 | 862 | 2,363"
12,VIEWNG_PRICE,str,98,95,96.94,"1,000 | 5,000 | 19,000 | 3,000 | 15,000"
13,INFN_VIEWNG_PRICE,str,97,91,93.81,"0 | 3,000 | 9,000 | 2,000 | 입장불가"
14,SCHBOY_VIEWNG_PRICE,str,97,95,97.94,"500 | 3,000 | 9,000 | 2,000 | 6,000"
15,MSKLSD_VIEWNG_PRICE,str,97,95,97.94,"500 | 4,000 | 13,000 | 2,000 | 9,000"
16,ADULT_VIEWNG_PRICE,str,96,93,96.88,"1,000 | 4,000 | 19,000 | 3,000 | 15,000"
17,SPECL_VIEWNG_PRICE,str,117,102,87.18,"기획전시별 별도 책정\n(2,000원~5,000원 수준) | 기획전시별 별도 책정\..."
18,INFN_SPECL_VIEWNG_PRICE,str,112,103,91.96,"0 | 10,000 | 12,000 | 5000(전시별 상이) | 전시별 상이"
19,SCHBOY_SPECL_VIEWNG_PRICE,str,112,104,92.86,"500 | 12,000 | 1,200 | 8,000 | 5000(전시별 상이)"
20,MSKLSD_SPECL_VIEWNG_PRICE,str,112,103,91.96,"500 | 15,000 | 1,800 | 8,000 | 5000(전시별 상이)"
21,ADULT_SPECL_VIEWNG_PRICE,str,112,103,91.96,"1,000 | 15,000 | 1,800 | 10,000 | 6000(전시별 상이)"
22,NMPR_CO,int64,294,294,100.00,368 | 364 | 373 | 10 | 59
23,QUALF_HOLD_CO,int64,294,294,100.00,63 | 0 | 36 | 8 | 4
24,GNRL_GVRNM_EMP_CO,float64,40,40,100.00,63.0 | 60.0 | 3.0 | 20.0 | 15.0
25,CNTRCT_EMP_CO,float64,46,46,100.00,128.0 | 4.0 | 2.0 | 3.0 | 1.0
26,PUBLIC_VLNTER_CO,str,40,40,100.00,20 | 16 | 25 | 57 | 150
27,ARTGR_EMP_CO,float64,210,210,100.00,2.0 | 11.0 | 10.0 | 6.0 | 23.0
28,PRFSN_CO,float64,72,72,100.00,1.0 | 8.0 | 2.0 | 3.0 | 4.0
29,PRVATE_VLNTER_CO,float64,31,31,100.00,2.0 | 103.0 | 95.0 | 6.0 | 85.0
30,GVRNM_EMP_SM_CO,int64,294,294,100.00,85 | 0 | 37 | 8 | 4
31,TOT_CNTRCT_EMP_CO,float64,38,38,100.00,52.0 | 10.0 | 2.0 | 1.0 | 26.0
32,CNTRCT_EMP_CRTFCT_CO,float64,34,34,100.00,24.0 | 1.0 | 9.0 | 8.0 | 6.0
33,PUBLIC_INTN_CO,float64,14,14,100.00,18.0 | 1.0 | 4.0 | 7.0
34,CURTR_QUALF_HOLD_CO,float64,179,179,100.00,5.0 | 8.0 | 3.0 | 1.0 | 7.0
35,CURTR_NTHG_QUALF_HOLD_CO,float64,72,72,100.00,1.0 | 8.0 | 2.0 | 3.0 | 4.0
36,GNRL_EMP_CO,float64,114,114,100.00,2.0 | 4.0 | 7.0 | 1.0 | 16.0
37,PRVATE_INTN_CO,float64,33,33,100.00,1.0 | 4.0 | 3.0 | 2.0 | 29.0

In [203]:
# 숫자형 변환 가능 비율이 낮은 컬럼 확인
# 단위, 설명, 문자가 섞인 컬럼은 바로 numeric 변환하지 않고 따로 판단한다.

print("[박물관] numeric 변환 가능 비율 95% 미만 컬럼")
display(
    museum_numeric_check[
        museum_numeric_check["numeric_convertible_rate"] < 95
    ].sort_values("numeric_convertible_rate")
)

print("[미술관] numeric 변환 가능 비율 95% 미만 컬럼")
display(
    art_numeric_check[
        art_numeric_check["numeric_convertible_rate"] < 95
    ].sort_values("numeric_convertible_rate")
)

[박물관] numeric 변환 가능 비율 95% 미만 컬럼

,column,dtype_before,non_missing_count,numeric_convertible_count,numeric_convertible_rate,sample_values
7,DSPYRM_ARTFT_CHG_CO,str,758,0,0.00,46회/1년 | 10회/1년 | 12회/1년 | 4회/1년 | 1회/7년
13,PBLPRFR_CAS_CO,str,640,0,0.00,연13회 | 연5회 | 연2회 | 연8회 | 연3회
15,HDCH_ARTFT_KND_CO,str,876,0,0.00,"금속, 토제, 도자기, 서화 등 | 의식주, 생업 등 생활사 자료 | 도서, 전단,..."
18,CRLTS_CO,str,282,2,0.71,"국보 81건, 보물 231건, 국가등록문화재 8건, 국가민속문화재 4건 | 보물13..."
11,PARKNG_POSBL_CO,str,774,682,88.11,862 | 167/9967.94㎡ | 10 | 72 | 227

[미술관] numeric 변환 가능 비율 95% 미만 컬럼

,column,dtype_before,non_missing_count,numeric_convertible_count,numeric_convertible_rate,sample_values
8,PBLPRFR_CAS_CO,str,264,0,0.00,연6회 | 연10회 | 연1회 | 연2회 | 연15회
17,SPECL_VIEWNG_PRICE,str,117,102,87.18,"기획전시별 별도 책정\n(2,000원~5,000원 수준) | 기획전시별 별도 책정\..."
18,INFN_SPECL_VIEWNG_PRICE,str,112,103,91.96,"0 | 10,000 | 12,000 | 5000(전시별 상이) | 전시별 상이"
20,MSKLSD_SPECL_VIEWNG_PRICE,str,112,103,91.96,"500 | 15,000 | 1,800 | 8,000 | 5000(전시별 상이)"
21,ADULT_SPECL_VIEWNG_PRICE,str,112,103,91.96,"1,000 | 15,000 | 1,800 | 10,000 | 6000(전시별 상이)"
19,SCHBOY_SPECL_VIEWNG_PRICE,str,112,104,92.86,"500 | 12,000 | 1,200 | 8,000 | 5000(전시별 상이)"
13,INFN_VIEWNG_PRICE,str,97,91,93.81,"0 | 3,000 | 9,000 | 2,000 | 입장불가"

박물관 보류 후보
- DSPYRM_ARTFT_CHG_CO
- PBLPRFR_CAS_CO
- HDCH_ARTFT_KND_CO
- CRLTS_CO
- PARKNG_POSBL_CO

미술관 보류 후보
- PBLPRFR_CAS_CO
- SPECL_VIEWNG_PRICE
- INFN_SPECL_VIEWNG_PRICE
- SCHBOY_SPECL_VIEWNG_PRICE
-  MSKLSD_SPECL_VIEWNG_PRICE
- ADULT_SPECL_VIEWNG_PRICE
-  INFN_VIEWNG_PRICE

In [204]:
# 95% 이상 변환 가능하지만 일부 비숫자 값이 섞인 컬럼 확인
# 실제 변환 전에 어떤 값이 numeric 변환을 막는지 확인한다.

def check_non_numeric_values(df, check_df, dataset_name, lower_rate=95, upper_rate=100):
    target_cols = check_df[
        (check_df["numeric_convertible_rate"] >= lower_rate) &
        (check_df["numeric_convertible_rate"] < upper_rate)
    ]["column"].tolist()
    
    rows = []
    
    for col in target_cols:
        s = df[col]
        
        cleaned = (
            s.astype("string")
             .str.strip()
             .str.replace(",", "", regex=False)
        )
        
        converted = pd.to_numeric(cleaned, errors="coerce")
        
        # 원래 값은 있는데 numeric 변환 결과가 NaN인 값
        non_numeric_values = s[
            s.notna() & converted.isna()
        ].astype(str).unique()
        
        rows.append({
            "dataset": dataset_name,
            "column": col,
            "dtype_before": str(s.dtype),
            "non_numeric_count": len(non_numeric_values),
            "non_numeric_values": " | ".join(non_numeric_values[:10])
        })
    
    return pd.DataFrame(rows)


museum_ambiguous_numeric = check_non_numeric_values(
    museum_typed,
    museum_numeric_check,
    "박물관"
)

art_ambiguous_numeric = check_non_numeric_values(
    art_typed,
    art_numeric_check,
    "미술관"
)

print("[박물관] 95% 이상 100% 미만 숫자형 변환 후보의 비숫자 값")
display(museum_ambiguous_numeric)

print("[미술관] 95% 이상 100% 미만 숫자형 변환 후보의 비숫자 값")
display(art_ambiguous_numeric)

[박물관] 95% 이상 100% 미만 숫자형 변환 후보의 비숫자 값

,dataset,column,dtype_before,non_numeric_count,non_numeric_values
0,박물관,SPECL_DSPY_AR_VALUE,str,1,상설/특별전 구분없이 전시에 따라 유동적으로 사용
1,박물관,HDCH_ARTFT_CAS_CO,str,1,본관통합
2,박물관,HDCH_ARTFT_CO,str,1,본관통합
3,박물관,VIEWNG_PRICE,str,1,자율봉헌
4,박물관,MSKLSD_VIEWNG_PRICE,str,3,"중-1,000, 고-2,000 | 7000, 9000 | 관람불가"
5,박물관,SPECL_VIEWNG_PRICE,str,2,변동 | 자율봉헌
6,박물관,SCHBOY_SPECL_VIEWNG_PRICE,str,1,일반 50%
7,박물관,MSKLSD_SPECL_VIEWNG_PRICE,str,2,"일반 50% | 7000, 9000"

[미술관] 95% 이상 100% 미만 숫자형 변환 후보의 비숫자 값

,dataset,column,dtype_before,non_numeric_count,non_numeric_values
0,미술관,LND_AR_VALUE,str,1,포스코센터
1,미술관,VIEWNG_NMPR_CO,str,2,- | 미제출
2,미술관,DAY_AVRG_VIEWNG_NMPR_CO,str,2,- | 미제출
3,미술관,VIEWNG_PRICE,str,3,"13,000 (커피제공) | 전시별 상이 | 야간 22000 \n주간 10000"
4,미술관,SCHBOY_VIEWNG_PRICE,str,2,전시별 상이 | 야간 17000 \n주간 7000
5,미술관,MSKLSD_VIEWNG_PRICE,str,2,전시별 상이 | 야간 20000 \n주간 9000
6,미술관,ADULT_VIEWNG_PRICE,str,3,"13,000 (커피제공) | 전시별 상이 | 야간 22000 \n주간 10000"

In [205]:
# 숫자형 변환 대상 1차 분류
# 1) safe: 결측이 아닌 값 기준 100% numeric 변환 가능
# 2) ambiguous: 95% 이상 변환 가능하지만 일부 문자값 존재
# 3) hold: 95% 미만으로 변환 보류

def split_numeric_columns(check_df):
    safe_cols = check_df[
        check_df["numeric_convertible_rate"] == 100
    ]["column"].tolist()
    
    ambiguous_cols = check_df[
        (check_df["numeric_convertible_rate"] >= 95) &
        (check_df["numeric_convertible_rate"] < 100)
    ]["column"].tolist()
    
    hold_cols = check_df[
        check_df["numeric_convertible_rate"] < 95
    ]["column"].tolist()
    
    return safe_cols, ambiguous_cols, hold_cols


museum_numeric_safe_cols, museum_numeric_ambiguous_cols, museum_numeric_hold_cols = split_numeric_columns(museum_numeric_check)
art_numeric_safe_cols, art_numeric_ambiguous_cols, art_numeric_hold_cols = split_numeric_columns(art_numeric_check)

print("[박물관] 바로 변환 가능 컬럼 수:", len(museum_numeric_safe_cols))
print(museum_numeric_safe_cols)

print("\n[박물관] 일부 문자값 확인 필요 컬럼 수:", len(museum_numeric_ambiguous_cols))
print(museum_numeric_ambiguous_cols)

print("\n[박물관] 변환 보류 컬럼 수:", len(museum_numeric_hold_cols))
print(museum_numeric_hold_cols)

print("\n" + "=" * 80 + "\n")

print("[미술관] 바로 변환 가능 컬럼 수:", len(art_numeric_safe_cols))
print(art_numeric_safe_cols)

print("\n[미술관] 일부 문자값 확인 필요 컬럼 수:", len(art_numeric_ambiguous_cols))
print(art_numeric_ambiguous_cols)

print("\n[미술관] 변환 보류 컬럼 수:", len(art_numeric_hold_cols))
print(art_numeric_hold_cols)

[박물관] 바로 변환 가능 컬럼 수: 35
['FCLTY_LO', 'FCLTY_LA', 'OPNNG_DAY_CO', 'LND_AR_VALUE', 'EDC_FCLTY_AR_VALUE', 'DATA_SPCE_AR_VALUE', 'TOTAR_VALUE', 'CLTUR_GOODS_SPCE_AR_VALUE', 'RSTRNT_AR_VALUE', 'DATA_CO', 'TOT_PROGRM_CO', 'PROGRM_CO', 'FDRM_EXPRN_PROGRM_CO', 'NON_FDRM_EXPRN_PROGRM_CO', 'OUT_PROGRM_CO', 'VIEWNG_NMPR_CO', 'DAY_AVRG_VIEWNG_NMPR_CO', 'INFN_VIEWNG_PRICE', 'SCHBOY_VIEWNG_PRICE', 'ADULT_VIEWNG_PRICE', 'INFN_SPECL_VIEWNG_PRICE', 'ADULT_SPECL_VIEWNG_PRICE', 'NMPR_CO', 'QUALF_HOLD_CO', 'GNRL_GVRNM_EMP_CO', 'CNTRCT_EMP_CO', 'PUBLIC_VLNTER_CO', 'ARTGR_EMP_CO', 'PRFSN_CO', 'PRVATE_VLNTER_CO', 'CLTUR_ART_GVRNM_MANAGE_EMP_CO', 'CLTUR_ART_GVRNM_EMP_CO', 'INTN_EMP_CO', 'ETC_GNRL_EMP_CO', 'ETC_INTN_EMP_CO']

[박물관] 일부 문자값 확인 필요 컬럼 수: 8
['SPECL_DSPY_AR_VALUE', 'HDCH_ARTFT_CAS_CO', 'HDCH_ARTFT_CO', 'VIEWNG_PRICE', 'MSKLSD_VIEWNG_PRICE', 'SPECL_VIEWNG_PRICE', 'SCHBOY_SPECL_VIEWNG_PRICE', 'MSKLSD_SPECL_VIEWNG_PRICE']

[박물관] 변환 보류 컬럼 수: 5
['DSPYRM_ARTFT_CHG_CO', 'PARKNG_POSBL_CO', 'PBLPRFR_CAS_CO', 'HDCH_ARTFT_KND_CO', 'CRLTS_CO']

================================================================================

[미술관] 바로 변환 가능 컬럼 수: 24
['FCLTY_LO', 'FCLTY_LA', 'OPNNG_DAY_CO', 'EDC_FCLTY_AR_VALUE', 'DATA_SPCE_AR_VALUE', 'BULD_AR_VALUE', 'DATA_CO', 'TOT_PROGRM_CO', 'NMPR_CO', 'QUALF_HOLD_CO', 'GNRL_GVRNM_EMP_CO', 'CNTRCT_EMP_CO', 'PUBLIC_VLNTER_CO', 'ARTGR_EMP_CO', 'PRFSN_CO', 'PRVATE_VLNTER_CO', 'GVRNM_EMP_SM_CO', 'TOT_CNTRCT_EMP_CO', 'CNTRCT_EMP_CRTFCT_CO', 'PUBLIC_INTN_CO', 'CURTR_QUALF_HOLD_CO', 'CURTR_NTHG_QUALF_HOLD_CO', 'GNRL_EMP_CO', 'PRVATE_INTN_CO']

[미술관] 일부 문자값 확인 필요 컬럼 수: 7
['LND_AR_VALUE', 'VIEWNG_NMPR_CO', 'DAY_AVRG_VIEWNG_NMPR_CO', 'VIEWNG_PRICE', 'SCHBOY_VIEWNG_PRICE', 'MSKLSD_VIEWNG_PRICE', 'ADULT_VIEWNG_PRICE']

[미술관] 변환 보류 컬럼 수: 7
['PBLPRFR_CAS_CO', 'INFN_VIEWNG_PRICE', 'SPECL_VIEWNG_PRICE', 'INFN_SPECL_VIEWNG_PRICE', 'SCHBOY_SPECL_VIEWNG_PRICE', 'MSKLSD_SPECL_VIEWNG_PRICE', 'ADULT_SPECL_VIEWNG_PRICE']

- safe_cols만 먼저 숫자형 변환
- ambiguous_cols는 "전시별 상이", "관람불가", "자율봉헌", "미제출" 같은 값이 섞여 있어서 다음 단계에서 따로 판단

In [206]:
# 숫자형 변환 전 dtype 저장
# safe 컬럼만 먼저 변환하고, 변환 전후 dtype을 비교한다.

museum_dtype_before_numeric = museum_typed[museum_numeric_safe_cols].dtypes.astype(str)
art_dtype_before_numeric = art_typed[art_numeric_safe_cols].dtypes.astype(str)

print("[박물관] 숫자형 변환 전 dtype")
display(museum_dtype_before_numeric.to_frame("dtype_before"))

print("[미술관] 숫자형 변환 전 dtype")
display(art_dtype_before_numeric.to_frame("dtype_before"))

[박물관] 숫자형 변환 전 dtype

                              dtype_before
FCLTY_LO                           float64
FCLTY_LA                           float64
OPNNG_DAY_CO                       float64
LND_AR_VALUE                       float64
EDC_FCLTY_AR_VALUE                 float64
DATA_SPCE_AR_VALUE                 float64
TOTAR_VALUE                        float64
CLTUR_GOODS_SPCE_AR_VALUE          float64
RSTRNT_AR_VALUE                    float64
DATA_CO                            float64
TOT_PROGRM_CO                      float64
PROGRM_CO                          float64
FDRM_EXPRN_PROGRM_CO               float64
NON_FDRM_EXPRN_PROGRM_CO           float64
OUT_PROGRM_CO                      float64
VIEWNG_NMPR_CO                     float64
DAY_AVRG_VIEWNG_NMPR_CO            float64
INFN_VIEWNG_PRICE                  float64
SCHBOY_VIEWNG_PRICE                float64
ADULT_VIEWNG_PRICE                 float64
INFN_SPECL_VIEWNG_PRICE            float64
ADULT_SPECL_VIEWNG_PRICE           float64
NMPR_CO                            float64
QUALF_HOLD_CO                      float64
GNRL_GVRNM_EMP_CO                  float64
CNTRCT_EMP_CO                      float64
PUBLIC_VLNTER_CO                   float64
ARTGR_EMP_CO                       float64
PRFSN_CO                           float64
PRVATE_VLNTER_CO                   float64
CLTUR_ART_GVRNM_MANAGE_EMP_CO      float64
CLTUR_ART_GVRNM_EMP_CO             float64
INTN_EMP_CO                        float64
ETC_GNRL_EMP_CO                    float64
ETC_INTN_EMP_CO                    float64

[미술관] 숫자형 변환 전 dtype

                         dtype_before
FCLTY_LO                      float64
FCLTY_LA                      float64
OPNNG_DAY_CO                    int64
EDC_FCLTY_AR_VALUE                str
DATA_SPCE_AR_VALUE            float64
BULD_AR_VALUE                     str
DATA_CO                           str
TOT_PROGRM_CO                 float64
NMPR_CO                         int64
QUALF_HOLD_CO                   int64
GNRL_GVRNM_EMP_CO             float64
CNTRCT_EMP_CO                 float64
PUBLIC_VLNTER_CO                  str
ARTGR_EMP_CO                  float64
PRFSN_CO                      float64
PRVATE_VLNTER_CO              float64
GVRNM_EMP_SM_CO                 int64
TOT_CNTRCT_EMP_CO             float64
CNTRCT_EMP_CRTFCT_CO          float64
PUBLIC_INTN_CO                float64
CURTR_QUALF_HOLD_CO           float64
CURTR_NTHG_QUALF_HOLD_CO      float64
GNRL_EMP_CO                   float64
PRVATE_INTN_CO                float64

In [207]:
# 숫자형 변환 함수
# 쉼표 제거 후 numeric 변환
# errors="coerce"를 사용하지만, safe 컬럼은 사전 점검에서 100% 변환 가능했던 컬럼이다.

def convert_to_numeric(df, cols):
    df = df.copy()
    
    for col in cols:
        df[col] = (
            df[col]
            .astype("string")
            .str.strip()
            .str.replace(",", "", regex=False)
        )
        df[col] = pd.to_numeric(df[col], errors="coerce")
    
    return df


museum_typed = convert_to_numeric(museum_typed, museum_numeric_safe_cols)
art_typed = convert_to_numeric(art_typed, art_numeric_safe_cols)

print("safe 컬럼 숫자형 변환 완료")
print("박물관 변환 컬럼 수:", len(museum_numeric_safe_cols))
print("미술관 변환 컬럼 수:", len(art_numeric_safe_cols))

safe 컬럼 숫자형 변환 완료
박물관 변환 컬럼 수: 35
미술관 변환 컬럼 수: 24

In [208]:
# 숫자형 변환 후 dtype 저장
museum_dtype_after_numeric = museum_typed[museum_numeric_safe_cols].dtypes.astype(str)
art_dtype_after_numeric = art_typed[art_numeric_safe_cols].dtypes.astype(str)

museum_numeric_dtype_compare = pd.DataFrame({
    "dtype_before": museum_dtype_before_numeric,
    "dtype_after": museum_dtype_after_numeric
})

art_numeric_dtype_compare = pd.DataFrame({
    "dtype_before": art_dtype_before_numeric,
    "dtype_after": art_dtype_after_numeric
})

print("[박물관] 숫자형 변환 전후 dtype 비교")
display(museum_numeric_dtype_compare)

print("[미술관] 숫자형 변환 전후 dtype 비교")
display(art_numeric_dtype_compare)

[박물관] 숫자형 변환 전후 dtype 비교

                              dtype_before dtype_after
FCLTY_LO                           float64     Float64
FCLTY_LA                           float64     Float64
OPNNG_DAY_CO                       float64     Float64
LND_AR_VALUE                       float64     Float64
EDC_FCLTY_AR_VALUE                 float64     Float64
DATA_SPCE_AR_VALUE                 float64     Float64
TOTAR_VALUE                        float64     Float64
CLTUR_GOODS_SPCE_AR_VALUE          float64     Float64
RSTRNT_AR_VALUE                    float64     Float64
DATA_CO                            float64     Float64
TOT_PROGRM_CO                      float64     Float64
PROGRM_CO                          float64     Float64
FDRM_EXPRN_PROGRM_CO               float64     Float64
NON_FDRM_EXPRN_PROGRM_CO           float64     Float64
OUT_PROGRM_CO                      float64     Float64
VIEWNG_NMPR_CO                     float64     Float64
DAY_AVRG_VIEWNG_NMPR_CO            float64     Float64
INFN_VIEWNG_PRICE                  float64     Float64
SCHBOY_VIEWNG_PRICE                float64     Float64
ADULT_VIEWNG_PRICE                 float64     Float64
INFN_SPECL_VIEWNG_PRICE            float64     Float64
ADULT_SPECL_VIEWNG_PRICE           float64     Float64
NMPR_CO                            float64     Float64
QUALF_HOLD_CO                      float64     Float64
GNRL_GVRNM_EMP_CO                  float64     Float64
CNTRCT_EMP_CO                      float64     Float64
PUBLIC_VLNTER_CO                   float64     Float64
ARTGR_EMP_CO                       float64     Float64
PRFSN_CO                           float64     Float64
PRVATE_VLNTER_CO                   float64     Float64
CLTUR_ART_GVRNM_MANAGE_EMP_CO      float64     Float64
CLTUR_ART_GVRNM_EMP_CO             float64     Float64
INTN_EMP_CO                        float64     Float64
ETC_GNRL_EMP_CO                    float64     Float64
ETC_INTN_EMP_CO                    float64     Float64

[미술관] 숫자형 변환 전후 dtype 비교

                         dtype_before dtype_after
FCLTY_LO                      float64     Float64
FCLTY_LA                      float64     Float64
OPNNG_DAY_CO                    int64       Int64
EDC_FCLTY_AR_VALUE                str       Int64
DATA_SPCE_AR_VALUE            float64     Float64
BULD_AR_VALUE                     str       Int64
DATA_CO                           str       Int64
TOT_PROGRM_CO                 float64     Float64
NMPR_CO                         int64       Int64
QUALF_HOLD_CO                   int64       Int64
GNRL_GVRNM_EMP_CO             float64     Float64
CNTRCT_EMP_CO                 float64     Float64
PUBLIC_VLNTER_CO                  str       Int64
ARTGR_EMP_CO                  float64     Float64
PRFSN_CO                      float64     Float64
PRVATE_VLNTER_CO              float64     Float64
GVRNM_EMP_SM_CO                 int64       Int64
TOT_CNTRCT_EMP_CO             float64     Float64
CNTRCT_EMP_CRTFCT_CO          float64     Float64
PUBLIC_INTN_CO                float64     Float64
CURTR_QUALF_HOLD_CO           float64     Float64
CURTR_NTHG_QUALF_HOLD_CO      float64     Float64
GNRL_EMP_CO                   float64     Float64
PRVATE_INTN_CO                float64     Float64

In [209]:
# 숫자형 변환 과정에서 결측치가 새로 생겼는지 확인
# safe 컬럼은 원칙적으로 새 결측치가 생기지 않아야 한다.

def check_new_missing_after_numeric_conversion(df_original, df_converted, cols):
    rows = []
    
    for col in cols:
        before_missing = df_original[col].isna().sum()
        after_missing = df_converted[col].isna().sum()
        
        rows.append({
            "column": col,
            "missing_before": before_missing,
            "missing_after": after_missing,
            "new_missing_count": after_missing - before_missing
        })
    
    return pd.DataFrame(rows)


museum_numeric_missing_check = check_new_missing_after_numeric_conversion(
    museum_basic,
    museum_typed,
    museum_numeric_safe_cols
)

art_numeric_missing_check = check_new_missing_after_numeric_conversion(
    art_basic,
    art_typed,
    art_numeric_safe_cols
)

print("[박물관] 숫자형 변환 후 신규 결측 발생 확인")
display(
    museum_numeric_missing_check[
        museum_numeric_missing_check["new_missing_count"] != 0
    ]
)

print("[미술관] 숫자형 변환 후 신규 결측 발생 확인")
display(
    art_numeric_missing_check[
        art_numeric_missing_check["new_missing_count"] != 0
    ]
)

[박물관] 숫자형 변환 후 신규 결측 발생 확인

Empty DataFrame
Columns: [column, missing_before, missing_after, new_missing_count]
Index: []

[미술관] 숫자형 변환 후 신규 결측 발생 확인

Empty DataFrame
Columns: [column, missing_before, missing_after, new_missing_count]
Index: []

- safe_cols 숫자형 변환 완료
- 박물관 변환 컬럼 수: 35개
- 미술관 변환 컬럼 수: 24개
- dtype_after가 Float64로 변환

##### ambiguous_cols 처리

In [210]:
# ambiguous 숫자형 후보 처리 기준
# 일부 비숫자 값이 있지만, 컬럼 의미상 숫자형으로 보는 것이 적절한 컬럼만 변환한다.
# 가격이 여러 기준으로 적혀 있거나, "전시별 상이", "일반 50%"처럼 해석이 필요한 컬럼은 보류한다.

museum_ambiguous_to_numeric_cols = [
    "SPECL_DSPY_AR_VALUE",   # 특별전시면적: 1개 설명값 존재
    "HDCH_ARTFT_CAS_CO",     # 소장자료 건수: 1개 '본관통합'
    "HDCH_ARTFT_CO",         # 소장자료 수량: 1개 '본관통합'
    "VIEWNG_PRICE",          # 관람료: 1개 '자율봉헌'
    "SPECL_VIEWNG_PRICE"     # 특별관람료: '변동', '자율봉헌'
]

museum_ambiguous_hold_cols = [
    "MSKLSD_VIEWNG_PRICE",         # 중/고등학생 가격이 한 셀에 혼합
    "SCHBOY_SPECL_VIEWNG_PRICE",   # '일반 50%' 등 산식형 값 존재
    "MSKLSD_SPECL_VIEWNG_PRICE"    # '일반 50%', 복수 가격 존재
]

art_ambiguous_to_numeric_cols = [
    "LND_AR_VALUE",              # 부지면적: 1개 '포스코센터'
    "VIEWNG_NMPR_CO",            # 관람인원: '-', '미제출'
    "DAY_AVRG_VIEWNG_NMPR_CO"    # 일평균 관람인원: '-', '미제출'
]

art_ambiguous_hold_cols = [
    "VIEWNG_PRICE",          # '전시별 상이', 주간/야간 가격 혼합
    "SCHBOY_VIEWNG_PRICE",   # '전시별 상이', 주간/야간 가격 혼합
    "MSKLSD_VIEWNG_PRICE",   # '전시별 상이', 주간/야간 가격 혼합
    "ADULT_VIEWNG_PRICE"     # '커피제공', 주간/야간 가격 혼합
]

print("[박물관] ambiguous 중 numeric 변환 대상:", len(museum_ambiguous_to_numeric_cols))
print(museum_ambiguous_to_numeric_cols)

print("\n[박물관] ambiguous 중 보류 대상:", len(museum_ambiguous_hold_cols))
print(museum_ambiguous_hold_cols)

print("\n[미술관] ambiguous 중 numeric 변환 대상:", len(art_ambiguous_to_numeric_cols))
print(art_ambiguous_to_numeric_cols)

print("\n[미술관] ambiguous 중 보류 대상:", len(art_ambiguous_hold_cols))
print(art_ambiguous_hold_cols)

[박물관] ambiguous 중 numeric 변환 대상: 5
['SPECL_DSPY_AR_VALUE', 'HDCH_ARTFT_CAS_CO', 'HDCH_ARTFT_CO', 'VIEWNG_PRICE', 'SPECL_VIEWNG_PRICE']

[박물관] ambiguous 중 보류 대상: 3
['MSKLSD_VIEWNG_PRICE', 'SCHBOY_SPECL_VIEWNG_PRICE', 'MSKLSD_SPECL_VIEWNG_PRICE']

[미술관] ambiguous 중 numeric 변환 대상: 3
['LND_AR_VALUE', 'VIEWNG_NMPR_CO', 'DAY_AVRG_VIEWNG_NMPR_CO']

[미술관] ambiguous 중 보류 대상: 4
['VIEWNG_PRICE', 'SCHBOY_VIEWNG_PRICE', 'MSKLSD_VIEWNG_PRICE', 'ADULT_VIEWNG_PRICE']

In [211]:
# ambiguous 중 변환 대상으로 선정한 컬럼의 변환 전 dtype 저장

museum_dtype_before_ambiguous_numeric = museum_typed[museum_ambiguous_to_numeric_cols].dtypes.astype(str)
art_dtype_before_ambiguous_numeric = art_typed[art_ambiguous_to_numeric_cols].dtypes.astype(str)

print("[박물관] ambiguous numeric 변환 전 dtype")
display(museum_dtype_before_ambiguous_numeric.to_frame("dtype_before"))

print("[미술관] ambiguous numeric 변환 전 dtype")
display(art_dtype_before_ambiguous_numeric.to_frame("dtype_before"))

[박물관] ambiguous numeric 변환 전 dtype

                    dtype_before
SPECL_DSPY_AR_VALUE          str
HDCH_ARTFT_CAS_CO            str
HDCH_ARTFT_CO                str
VIEWNG_PRICE                 str
SPECL_VIEWNG_PRICE           str

[미술관] ambiguous numeric 변환 전 dtype

                        dtype_before
LND_AR_VALUE                     str
VIEWNG_NMPR_CO                   str
DAY_AVRG_VIEWNG_NMPR_CO          str

In [212]:
# ambiguous 중 숫자형으로 판단한 컬럼만 변환
# 비숫자 값은 numeric 변환이 불가능하므로 NaN으로 처리된다.
# 이 단계는 결측치 대체가 아니라, 숫자로 해석할 수 없는 값을 결측으로 표시하는 과정이다.

museum_typed = convert_to_numeric(museum_typed, museum_ambiguous_to_numeric_cols)
art_typed = convert_to_numeric(art_typed, art_ambiguous_to_numeric_cols)

print("ambiguous 일부 컬럼 숫자형 변환 완료")
print("박물관 변환 컬럼 수:", len(museum_ambiguous_to_numeric_cols))
print("미술관 변환 컬럼 수:", len(art_ambiguous_to_numeric_cols))

ambiguous 일부 컬럼 숫자형 변환 완료
박물관 변환 컬럼 수: 5
미술관 변환 컬럼 수: 3

In [213]:
# ambiguous 숫자형 변환 후 dtype 비교

museum_dtype_after_ambiguous_numeric = museum_typed[museum_ambiguous_to_numeric_cols].dtypes.astype(str)
art_dtype_after_ambiguous_numeric = art_typed[art_ambiguous_to_numeric_cols].dtypes.astype(str)

museum_ambiguous_numeric_dtype_compare = pd.DataFrame({
    "dtype_before": museum_dtype_before_ambiguous_numeric,
    "dtype_after": museum_dtype_after_ambiguous_numeric
})

art_ambiguous_numeric_dtype_compare = pd.DataFrame({
    "dtype_before": art_dtype_before_ambiguous_numeric,
    "dtype_after": art_dtype_after_ambiguous_numeric
})

print("[박물관] ambiguous 숫자형 변환 전후 dtype 비교")
display(museum_ambiguous_numeric_dtype_compare)

print("[미술관] ambiguous 숫자형 변환 전후 dtype 비교")
display(art_ambiguous_numeric_dtype_compare)

[박물관] ambiguous 숫자형 변환 전후 dtype 비교

                    dtype_before dtype_after
SPECL_DSPY_AR_VALUE          str     Float64
HDCH_ARTFT_CAS_CO            str       Int64
HDCH_ARTFT_CO                str       Int64
VIEWNG_PRICE                 str       Int64
SPECL_VIEWNG_PRICE           str       Int64

[미술관] ambiguous 숫자형 변환 전후 dtype 비교

                        dtype_before dtype_after
LND_AR_VALUE                     str       Int64
VIEWNG_NMPR_CO                   str       Int64
DAY_AVRG_VIEWNG_NMPR_CO          str       Int64

In [214]:
# ambiguous 컬럼은 일부 비숫자 값이 있었으므로 신규 결측이 생기는 것이 정상이다.
# 어떤 컬럼에서 몇 개가 NaN으로 바뀌었는지 확인한다.

museum_ambiguous_missing_check = check_new_missing_after_numeric_conversion(
    museum_basic,
    museum_typed,
    museum_ambiguous_to_numeric_cols
)

art_ambiguous_missing_check = check_new_missing_after_numeric_conversion(
    art_basic,
    art_typed,
    art_ambiguous_to_numeric_cols
)

print("[박물관] ambiguous 숫자형 변환 후 신규 결측 발생 확인")
display(museum_ambiguous_missing_check)

print("[미술관] ambiguous 숫자형 변환 후 신규 결측 발생 확인")
display(art_ambiguous_missing_check)

[박물관] ambiguous 숫자형 변환 후 신규 결측 발생 확인

                column  missing_before  missing_after  new_missing_count
0  SPECL_DSPY_AR_VALUE             291            292                  1
1    HDCH_ARTFT_CAS_CO             154            155                  1
2        HDCH_ARTFT_CO              23             24                  1
3         VIEWNG_PRICE             554            555                  1
4   SPECL_VIEWNG_PRICE             769            771                  2

[미술관] ambiguous 숫자형 변환 후 신규 결측 발생 확인

                    column  missing_before  missing_after  new_missing_count
0             LND_AR_VALUE               2              3                  1
1           VIEWNG_NMPR_CO               0             13                 13
2  DAY_AVRG_VIEWNG_NMPR_CO               0             13                 13

<숫자형 변환 완료>

safe 숫자형 변환:
- 박물관 35개 컬럼 변환 완료
- 미술관 24개 컬럼 변환 완료
- 신규 결측 없음

ambiguous 숫자형 변환:
- 박물관 5개 컬럼 변환 완료
- 미술관 3개 컬럼 변환 완료
- 일부 비숫자 값은 NaN으로 변경됨

<주의><br>
DAY_AVRG_VIEWNG_NMPR_CO는 숫자형으로 변환은 했지만,
나중에 관람객 수 예측 모델에서는 데이터 누수 가능성이 있으므로
입력 변수로 사용할지 반드시 주의해야 한다.

In [215]:
# 날짜형 변환 후보 컬럼 확인
# 컬럼명 기준으로 날짜 가능성이 높은 컬럼을 먼저 찾는다.
# 일반적으로 이 데이터에서는 *_DE 컬럼이 날짜 컬럼 후보이다.

date_candidate_cols = sorted(
    set(
        [col for col in museum_typed.columns if col.endswith("_DE")] +
        [col for col in art_typed.columns if col.endswith("_DE")]
    )
)

museum_date_cols = [col for col in date_candidate_cols if col in museum_typed.columns]
art_date_cols = [col for col in date_candidate_cols if col in art_typed.columns]

print("전체 날짜형 후보 컬럼:")
print(date_candidate_cols)

print("\n[박물관] 날짜형 후보 컬럼:")
print(museum_date_cols)

print("\n[미술관] 날짜형 후보 컬럼:")
print(art_date_cols)

전체 날짜형 후보 컬럼:
['BASE_DE', 'LAST_CHG_DE', 'OPNNG_DE']

[박물관] 날짜형 후보 컬럼:
['BASE_DE', 'LAST_CHG_DE', 'OPNNG_DE']

[미술관] 날짜형 후보 컬럼:
['BASE_DE', 'LAST_CHG_DE', 'OPNNG_DE']

In [216]:
# 날짜형 후보 컬럼의 dtype과 샘플 값 확인
# 실제 변환 전에 값 형태를 먼저 확인한다.

def check_date_candidate_values(df, cols, dataset_name):
    rows = []
    
    for col in cols:
        s = df[col]
        
        rows.append({
            "dataset": dataset_name,
            "column": col,
            "dtype_before": str(s.dtype),
            "non_missing_count": s.notna().sum(),
            "missing_count": s.isna().sum(),
            "sample_values": " | ".join(s.dropna().astype(str).unique()[:10])
        })
    
    return pd.DataFrame(rows)


museum_date_value_check = check_date_candidate_values(
    museum_typed,
    museum_date_cols,
    "박물관"
)

art_date_value_check = check_date_candidate_values(
    art_typed,
    art_date_cols,
    "미술관"
)

print("[박물관] 날짜형 후보 값 확인")
display(museum_date_value_check)

print("[미술관] 날짜형 후보 값 확인")
display(art_date_value_check)

[박물관] 날짜형 후보 값 확인

,dataset,column,dtype_before,non_missing_count,missing_count,sample_values
0,박물관,BASE_DE,int64,897,0,20250327
1,박물관,LAST_CHG_DE,int64,897,0,20250327
2,박물관,OPNNG_DE,str,897,0,1945.12.03 | 1946.04.25 | 2021.07.23 | 2012.12...

[미술관] 날짜형 후보 값 확인

,dataset,column,dtype_before,non_missing_count,missing_count,sample_values
0,미술관,BASE_DE,int64,294,0,20251231
1,미술관,LAST_CHG_DE,int64,294,0,20260610
2,미술관,OPNNG_DE,str,294,0,1986.08.25 | 2013.11.12 | 1998.12.01 | 2018.12...

In [217]:
# 날짜형 변환 가능 여부 확인
# 실제 변환은 아직 하지 않고, pd.to_datetime으로 변환 가능한 비율만 확인한다.

def date_conversion_check(df, cols, dataset_name):
    rows = []
    
    for col in cols:
        s = df[col]
        
        cleaned = (
            s.astype("string")
             .str.strip()
        )
        
        # 빈 문자열, '-', '미상' 등은 결측으로 간주
        cleaned = cleaned.replace({
            "": pd.NA,
            "-": pd.NA,
            "미상": pd.NA,
            "미정": pd.NA,
            "nan": pd.NA,
            "None": pd.NA
        })
        
        converted = pd.to_datetime(cleaned, errors="coerce")
        
        non_missing_count = cleaned.notna().sum()
        convertible_count = converted.notna().sum()
        
        rows.append({
            "dataset": dataset_name,
            "column": col,
            "dtype_before": str(s.dtype),
            "non_missing_count": non_missing_count,
            "date_convertible_count": convertible_count,
            "date_convertible_rate": round((convertible_count / non_missing_count) * 100, 2) if non_missing_count > 0 else 0,
            "sample_values": " | ".join(s.dropna().astype(str).unique()[:10])
        })
    
    return pd.DataFrame(rows)


museum_date_check = date_conversion_check(
    museum_typed,
    museum_date_cols,
    "박물관"
)

art_date_check = date_conversion_check(
    art_typed,
    art_date_cols,
    "미술관"
)

print("[박물관] 날짜형 변환 가능 여부")
display(museum_date_check)

print("[미술관] 날짜형 변환 가능 여부")
display(art_date_check)

[박물관] 날짜형 변환 가능 여부

,dataset,column,dtype_before,non_missing_count,date_convertible_count,date_convertible_rate,sample_values
0,박물관,BASE_DE,int64,897,897,100.00,20250327
1,박물관,LAST_CHG_DE,int64,897,897,100.00,20250327
2,박물관,OPNNG_DE,str,897,885,98.66,1945.12.03 | 1946.04.25 | 2021.07.23 | 2012.12...

[미술관] 날짜형 변환 가능 여부

,dataset,column,dtype_before,non_missing_count,date_convertible_count,date_convertible_rate,sample_values
0,미술관,BASE_DE,int64,294,294,100.00,20251231
1,미술관,LAST_CHG_DE,int64,294,294,100.00,20260610
2,미술관,OPNNG_DE,str,294,291,98.98,1986.08.25 | 2013.11.12 | 1998.12.01 | 2018.12...

In [218]:
# OPNNG_DE에서 날짜형 변환이 어려운 값 확인
# 개관일은 분석에서 의미가 있을 수 있으므로, 바로 NaT 처리하지 않고 원본 값을 먼저 확인한다.

def check_invalid_date_values(df, col, dataset_name):
    s = df[col]
    
    cleaned = (
        s.astype("string")
         .str.strip()
    )
    
    cleaned = cleaned.replace({
        "": pd.NA,
        "-": pd.NA,
        "미상": pd.NA,
        "미정": pd.NA,
        "nan": pd.NA,
        "None": pd.NA
    })
    
    converted = pd.to_datetime(cleaned, errors="coerce")
    
    invalid_mask = cleaned.notna() & converted.isna()
    
    # 시설명/지역 컬럼이 있으면 같이 확인
    info_cols = [
        col for col in ["ID", "FCLTY_NM", "CTPRVN_NM", "SIGNGU_NM", "OPNNG_DE"]
        if col in df.columns
    ]
    
    invalid_df = df.loc[invalid_mask, info_cols].copy()
    invalid_df.insert(0, "dataset", dataset_name)
    
    return invalid_df


museum_invalid_opnng_date = check_invalid_date_values(
    museum_typed,
    "OPNNG_DE",
    "박물관"
)

art_invalid_opnng_date = check_invalid_date_values(
    art_typed,
    "OPNNG_DE",
    "미술관"
)

print("[박물관] OPNNG_DE 날짜형 변환 불가 값")
print("건수:", len(museum_invalid_opnng_date))
display(museum_invalid_opnng_date)

print("[미술관] OPNNG_DE 날짜형 변환 불가 값")
print("건수:", len(art_invalid_opnng_date))
display(art_invalid_opnng_date)

[박물관] OPNNG_DE 날짜형 변환 불가 값
건수: 12

,dataset,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,OPNNG_DE
111,박물관,KCDMMUS23N000000112,고려대학교박물관,서울,성북구,1934
117,박물관,KCDMMUS23N000000118,상명대학교박물관,서울,종로구,1967
129,박물관,KCDMMUS23N000000130,연세대학교박물관,서울,서대문구,1928
300,박물관,KCDMMUS23N000000301,유엔군 초전기념관,경기,오산시,유엔군초전기념관 (2013.04.23)\n스미스평화관 (2020.07.05)
323,박물관,KCDMMUS23N000000324,목아박물관,경기,여주시,1990.12
499,박물관,KCDMMUS23N000000500,진천종박물관,충북,진천군,2005.06.22.
519,박물관,KCDMMUS23N000000520,한국교원대학교 교육박물관,충북,청주시 흥덕구,2010.11.16 (1987.10.31)
654,박물관,KCDMMUS23N000000655,장보고기념관,전남,완도군,2008.02.29 (2023.09.01 재개관)
726,박물관,KCDMMUS23N000000727,정기룡장군유물전시관,경북,상주시,1980.05
753,박물관,KCDMMUS23N000000754,경주대학교박물관,경북,경주시,1992.07
844,박물관,KCDMMUS23N000000845,제주돌문화공원,제주특별자치도,제주시,돌박물관(2006.06.03)\n오백장군갤러리(2010.09.09)\n설문대할망전시...
872,박물관,KCDMMUS23N000000873,여미지식물원,제주특별자치도,서귀포시,1989.01

[미술관] OPNNG_DE 날짜형 변환 불가 값
건수: 3

,dataset,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,OPNNG_DE
25,미술관,KCDMART25N000000026,소마미술관,서울,송파구,2004.09.16\n2018.09.14
229,미술관,KCDMART25N000000230,도화헌미술관,전남,고흥군,2000.01
230,미술관,KCDMART25N000000231,리:피움미술관,전남,고흥군,2021.04

- 개관일이 적혀있지만 값의 형태들이 섞여있음 <br>
=> 원본(OPNNG_DE)은 보존하고, 날짜형으로 처리

In [219]:
# 날짜형 변환 전 원본 보존 및 dtype 저장
# OPNNG_DE는 값 형태가 다양하므로 원본 컬럼을 별도로 보존한다.

date_cols_to_convert = ["BASE_DE", "LAST_CHG_DE", "OPNNG_DE"]

museum_date_convert_cols = [col for col in date_cols_to_convert if col in museum_typed.columns]
art_date_convert_cols = [col for col in date_cols_to_convert if col in art_typed.columns]

# OPNNG_DE 원본 보존
for df in [museum_typed, art_typed]:
    if "OPNNG_DE" in df.columns and "OPNNG_DE_RAW" not in df.columns:
        insert_idx = df.columns.get_loc("OPNNG_DE") + 1
        df.insert(insert_idx, "OPNNG_DE_RAW", df["OPNNG_DE"])

museum_dtype_before_date = museum_typed[museum_date_convert_cols].dtypes.astype(str)
art_dtype_before_date = art_typed[art_date_convert_cols].dtypes.astype(str)

print("[박물관] 날짜형 변환 전 dtype")
display(museum_dtype_before_date.to_frame("dtype_before"))

print("[미술관] 날짜형 변환 전 dtype")
display(art_dtype_before_date.to_frame("dtype_before"))

[박물관] 날짜형 변환 전 dtype

            dtype_before
BASE_DE            int64
LAST_CHG_DE        int64
OPNNG_DE             str

[미술관] 날짜형 변환 전 dtype

            dtype_before
BASE_DE            int64
LAST_CHG_DE        int64
OPNNG_DE             str

In [220]:
# 날짜형 변환 함수 정의
# BASE_DE, LAST_CHG_DE는 일반 날짜 변환
# OPNNG_DE는 날짜 패턴을 추출한 뒤 변환한다.

import re

def normalize_missing_date_values(s):
    return (
        s.astype("string")
         .str.strip()
         .replace({
             "": pd.NA,
             "-": pd.NA,
             "미상": pd.NA,
             "미정": pd.NA,
             "nan": pd.NA,
             "None": pd.NA
         })
    )


def convert_general_date_series(s):
    cleaned = normalize_missing_date_values(s)
    return pd.to_datetime(cleaned, errors="coerce")


def parse_opening_date_value(value):
    if pd.isna(value):
        return pd.Series({
            "parsed_date": pd.NaT,
            "precision": pd.NA
        })
    
    text = str(value).strip()
    
    if text in ["", "-", "미상", "미정", "nan", "None"]:
        return pd.Series({
            "parsed_date": pd.NaT,
            "precision": pd.NA
        })
    
    # 한글 날짜 표현도 일부 대응
    text = (
        text.replace("년", ".")
            .replace("월", ".")
            .replace("일", "")
    )
    
    # YYYY / YYYY.MM / YYYY.MM.DD 형태 추출
    pattern = r"(\d{4})(?:[.\-/]\s*(\d{1,2}))?(?:[.\-/]\s*(\d{1,2}))?"
    
    for match in re.finditer(pattern, text):
        year = int(match.group(1))
        month = match.group(2)
        day = match.group(3)
        
        # 너무 비현실적인 연도는 제외
        if year < 1800 or year > 2100:
            continue
        
        if month is None:
            month = 1
            day = 1
            precision = "year"
        elif day is None:
            month = int(month)
            day = 1
            precision = "month"
        else:
            month = int(month)
            day = int(day)
            precision = "day"
        
        if not (1 <= month <= 12):
            continue
        
        if not (1 <= day <= 31):
            continue
        
        parsed = pd.to_datetime(
            f"{year:04d}-{month:02d}-{day:02d}",
            errors="coerce"
        )
        
        if pd.notna(parsed):
            return pd.Series({
                "parsed_date": parsed,
                "precision": precision
            })
    
    return pd.Series({
        "parsed_date": pd.NaT,
        "precision": pd.NA
    })


def convert_date_columns(df):
    df = df.copy()
    
    # 일반 날짜 컬럼 변환
    for col in ["BASE_DE", "LAST_CHG_DE"]:
        if col in df.columns:
            df[col] = convert_general_date_series(df[col])
    
    # 개관일 변환
    if "OPNNG_DE" in df.columns:
        raw_col = "OPNNG_DE_RAW" if "OPNNG_DE_RAW" in df.columns else "OPNNG_DE"
        parsed_result = df[raw_col].apply(parse_opening_date_value)
        
        df["OPNNG_DE"] = parsed_result["parsed_date"]
        df["OPNNG_DE_PRECISION"] = parsed_result["precision"]
    
    return df


museum_typed = convert_date_columns(museum_typed)
art_typed = convert_date_columns(art_typed)

print("날짜형 변환 완료")

날짜형 변환 완료

In [221]:
# 날짜형 변환 후 dtype 비교

museum_dtype_after_date = museum_typed[museum_date_convert_cols].dtypes.astype(str)
art_dtype_after_date = art_typed[art_date_convert_cols].dtypes.astype(str)

museum_date_dtype_compare = pd.DataFrame({
    "dtype_before": museum_dtype_before_date,
    "dtype_after": museum_dtype_after_date
})

art_date_dtype_compare = pd.DataFrame({
    "dtype_before": art_dtype_before_date,
    "dtype_after": art_dtype_after_date
})

print("[박물관] 날짜형 변환 전후 dtype 비교")
display(museum_date_dtype_compare)

print("[미술관] 날짜형 변환 전후 dtype 비교")
display(art_date_dtype_compare)

[박물관] 날짜형 변환 전후 dtype 비교

            dtype_before     dtype_after
BASE_DE            int64  datetime64[us]
LAST_CHG_DE        int64  datetime64[us]
OPNNG_DE             str  datetime64[us]

[미술관] 날짜형 변환 전후 dtype 비교

            dtype_before     dtype_after
BASE_DE            int64  datetime64[us]
LAST_CHG_DE        int64  datetime64[us]
OPNNG_DE             str  datetime64[us]

In [222]:
# 날짜형 변환 검증
# OPNNG_DE_RAW는 원본, OPNNG_DE는 변환된 날짜
# OPNNG_DE_PRECISION은 날짜 정확도 수준이다.

def check_date_missing_after_conversion(df, cols):
    rows = []
    
    for col in cols:
        if col == "OPNNG_DE" and "OPNNG_DE_RAW" in df.columns:
            raw_s = normalize_missing_date_values(df["OPNNG_DE_RAW"])
        else:
            raw_s = normalize_missing_date_values(df[col])
        
        before_missing = raw_s.isna().sum()
        after_missing = df[col].isna().sum()
        
        rows.append({
            "column": col,
            "missing_before": before_missing,
            "missing_after": after_missing,
            "new_missing_count": after_missing - before_missing
        })
    
    return pd.DataFrame(rows)


museum_date_missing_check = check_date_missing_after_conversion(
    museum_typed,
    museum_date_convert_cols
)

art_date_missing_check = check_date_missing_after_conversion(
    art_typed,
    art_date_convert_cols
)

print("[박물관] 날짜형 변환 후 신규 결측 확인")
display(museum_date_missing_check)

print("[미술관] 날짜형 변환 후 신규 결측 확인")
display(art_date_missing_check)

print("[박물관] OPNNG_DE 날짜 정확도 수준")
display(museum_typed["OPNNG_DE_PRECISION"].value_counts(dropna=False).to_frame("count"))

print("[미술관] OPNNG_DE 날짜 정확도 수준")
display(art_typed["OPNNG_DE_PRECISION"].value_counts(dropna=False).to_frame("count"))

[박물관] 날짜형 변환 후 신규 결측 확인

        column  missing_before  missing_after  new_missing_count
0      BASE_DE               0              0                  0
1  LAST_CHG_DE               0              0                  0
2     OPNNG_DE               0              0                  0

[미술관] 날짜형 변환 후 신규 결측 확인

        column  missing_before  missing_after  new_missing_count
0      BASE_DE               0              0                  0
1  LAST_CHG_DE               0              0                  0
2     OPNNG_DE               0              0                  0

[박물관] OPNNG_DE 날짜 정확도 수준

                    count
OPNNG_DE_PRECISION
day                   890
month                   4
year                    3

[미술관] OPNNG_DE 날짜 정확도 수준

                    count
OPNNG_DE_PRECISION
day                   292
month                   2

In [223]:
# 이전에 날짜 변환이 어려웠던 OPNNG_DE 값들이 어떻게 변환되었는지 확인

museum_opnng_check_cols = [
    col for col in ["ID", "FCLTY_NM", "CTPRVN_NM", "SIGNGU_NM", "OPNNG_DE_RAW", "OPNNG_DE", "OPNNG_DE_PRECISION"]
    if col in museum_typed.columns
]

art_opnng_check_cols = [
    col for col in ["ID", "FCLTY_NM", "CTPRVN_NM", "SIGNGU_NM", "OPNNG_DE_RAW", "OPNNG_DE", "OPNNG_DE_PRECISION"]
    if col in art_typed.columns
]

print("[박물관] OPNNG_DE 원본/변환 결과 확인")
display(
    museum_typed.loc[
        museum_typed["OPNNG_DE_RAW"].astype("string").str.contains(
            r"\n|\(|\)|^\d{4}$|^\d{4}\.\d{1,2}$|\.$",
            regex=True,
            na=False
        ),
        museum_opnng_check_cols
    ]
)

print("[미술관] OPNNG_DE 원본/변환 결과 확인")
display(
    art_typed.loc[
        art_typed["OPNNG_DE_RAW"].astype("string").str.contains(
            r"\n|\(|\)|^\d{4}$|^\d{4}\.\d{1,2}$|\.$",
            regex=True,
            na=False
        ),
        art_opnng_check_cols
    ]
)

[박물관] OPNNG_DE 원본/변환 결과 확인

,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,OPNNG_DE_RAW,OPNNG_DE,OPNNG_DE_PRECISION
111,KCDMMUS23N000000112,고려대학교박물관,서울,성북구,1934,1934-01-01,year
117,KCDMMUS23N000000118,상명대학교박물관,서울,종로구,1967,1967-01-01,year
129,KCDMMUS23N000000130,연세대학교박물관,서울,서대문구,1928,1928-01-01,year
300,KCDMMUS23N000000301,유엔군 초전기념관,경기,오산시,유엔군초전기념관 (2013.04.23)\n스미스평화관 (2020.07.05),2013-04-23,day
323,KCDMMUS23N000000324,목아박물관,경기,여주시,1990.12,1990-12-01,month
499,KCDMMUS23N000000500,진천종박물관,충북,진천군,2005.06.22.,2005-06-22,day
519,KCDMMUS23N000000520,한국교원대학교 교육박물관,충북,청주시 흥덕구,2010.11.16 (1987.10.31),2010-11-16,day
654,KCDMMUS23N000000655,장보고기념관,전남,완도군,2008.02.29 (2023.09.01 재개관),2008-02-29,day
726,KCDMMUS23N000000727,정기룡장군유물전시관,경북,상주시,1980.05,1980-05-01,month
753,KCDMMUS23N000000754,경주대학교박물관,경북,경주시,1992.07,1992-07-01,month
844,KCDMMUS23N000000845,제주돌문화공원,제주특별자치도,제주시,돌박물관(2006.06.03)\n오백장군갤러리(2010.09.09)\n설문대할망전시...,2006-06-03,day
872,KCDMMUS23N000000873,여미지식물원,제주특별자치도,서귀포시,1989.01,1989-01-01,month

[미술관] OPNNG_DE 원본/변환 결과 확인

,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,OPNNG_DE_RAW,OPNNG_DE,OPNNG_DE_PRECISION
25,KCDMART25N000000026,소마미술관,서울,송파구,2004.09.16\n2018.09.14,2004-09-16,day
229,KCDMART25N000000230,도화헌미술관,전남,고흥군,2000.01,2000-01-01,month
230,KCDMART25N000000231,리:피움미술관,전남,고흥군,2021.04,2021-04-01,month

- OPNNG_DE_RAW 보존
- OPNNG_DE_PRECISION 생성

In [224]:
# 03. 자료형 변환 요약표
# 숫자형 / 날짜형 변환 결과와 보류 컬럼 수를 정리한다.

museum_numeric_converted_cols = list(dict.fromkeys(
    museum_numeric_safe_cols + museum_ambiguous_to_numeric_cols
))

art_numeric_converted_cols = list(dict.fromkeys(
    art_numeric_safe_cols + art_ambiguous_to_numeric_cols
))

museum_numeric_not_converted_cols = list(dict.fromkeys(
    museum_numeric_hold_cols + museum_ambiguous_hold_cols
))

art_numeric_not_converted_cols = list(dict.fromkeys(
    art_numeric_hold_cols + art_ambiguous_hold_cols
))

type_conversion_summary = pd.DataFrame([
    {
        "dataset": "박물관",
        "category": "숫자형 변환 완료",
        "column_count": len(museum_numeric_converted_cols),
        "columns": ", ".join(museum_numeric_converted_cols)
    },
    {
        "dataset": "박물관",
        "category": "숫자형 변환 보류",
        "column_count": len(museum_numeric_not_converted_cols),
        "columns": ", ".join(museum_numeric_not_converted_cols)
    },
    {
        "dataset": "박물관",
        "category": "날짜형 변환 완료",
        "column_count": len(museum_date_convert_cols),
        "columns": ", ".join(museum_date_convert_cols)
    },
    {
        "dataset": "미술관",
        "category": "숫자형 변환 완료",
        "column_count": len(art_numeric_converted_cols),
        "columns": ", ".join(art_numeric_converted_cols)
    },
    {
        "dataset": "미술관",
        "category": "숫자형 변환 보류",
        "column_count": len(art_numeric_not_converted_cols),
        "columns": ", ".join(art_numeric_not_converted_cols)
    },
    {
        "dataset": "미술관",
        "category": "날짜형 변환 완료",
        "column_count": len(art_date_convert_cols),
        "columns": ", ".join(art_date_convert_cols)
    }
])

display(type_conversion_summary)

,dataset,category,column_count,columns
0,박물관,숫자형 변환 완료,40,"FCLTY_LO, FCLTY_LA, OPNNG_DAY_CO, LND_AR_VALUE..."
1,박물관,숫자형 변환 보류,8,"DSPYRM_ARTFT_CHG_CO, PARKNG_POSBL_CO, PBLPRFR_..."
2,박물관,날짜형 변환 완료,3,"BASE_DE, LAST_CHG_DE, OPNNG_DE"
3,미술관,숫자형 변환 완료,27,"FCLTY_LO, FCLTY_LA, OPNNG_DAY_CO, EDC_FCLTY_AR..."
4,미술관,숫자형 변환 보류,11,"PBLPRFR_CAS_CO, INFN_VIEWNG_PRICE, SPECL_VIEWN..."
5,미술관,날짜형 변환 완료,3,"BASE_DE, LAST_CHG_DE, OPNNG_DE"

In [225]:
# 자료형 변환 후 dtype 분포 확인

museum_dtype_distribution = (
    museum_typed.dtypes.astype(str)
    .value_counts()
    .rename_axis("dtype")
    .reset_index(name="column_count")
)

art_dtype_distribution = (
    art_typed.dtypes.astype(str)
    .value_counts()
    .rename_axis("dtype")
    .reset_index(name="column_count")
)

print("[박물관] 자료형 변환 후 dtype 분포")
display(museum_dtype_distribution)

print("[미술관] 자료형 변환 후 dtype 분포")
display(art_dtype_distribution)

[박물관] 자료형 변환 후 dtype 분포

            dtype  column_count
0         Float64            36
1             str            32
2         float64             4
3           Int64             4
4  datetime64[us]             3

[미술관] 자료형 변환 후 dtype 분포

            dtype  column_count
0             str            34
1         Float64            16
2           Int64            11
3  datetime64[us]             3
4           int64             1
5         float64             1

In [226]:
# 변환 완료 컬럼들이 실제로 numeric / datetime으로 변환되었는지 검증한다.

def verify_converted_dtypes(df, numeric_cols, date_cols, dataset_name):
    rows = []
    
    for col in numeric_cols:
        rows.append({
            "dataset": dataset_name,
            "column": col,
            "expected_type": "numeric",
            "actual_dtype": str(df[col].dtype),
            "is_valid": pd.api.types.is_numeric_dtype(df[col])
        })
    
    for col in date_cols:
        rows.append({
            "dataset": dataset_name,
            "column": col,
            "expected_type": "datetime",
            "actual_dtype": str(df[col].dtype),
            "is_valid": pd.api.types.is_datetime64_any_dtype(df[col])
        })
    
    return pd.DataFrame(rows)


museum_dtype_validation = verify_converted_dtypes(
    museum_typed,
    museum_numeric_converted_cols,
    museum_date_convert_cols,
    "박물관"
)

art_dtype_validation = verify_converted_dtypes(
    art_typed,
    art_numeric_converted_cols,
    art_date_convert_cols,
    "미술관"
)

print("[박물관] 변환 완료 컬럼 dtype 검증")
display(museum_dtype_validation)

print("[미술관] 변환 완료 컬럼 dtype 검증")
display(art_dtype_validation)

print("[박물관] 검증 실패 컬럼")
display(museum_dtype_validation[museum_dtype_validation["is_valid"] == False])

print("[미술관] 검증 실패 컬럼")
display(art_dtype_validation[art_dtype_validation["is_valid"] == False])

[박물관] 변환 완료 컬럼 dtype 검증

,dataset,column,expected_type,actual_dtype,is_valid
0,박물관,FCLTY_LO,numeric,Float64,True
1,박물관,FCLTY_LA,numeric,Float64,True
2,박물관,OPNNG_DAY_CO,numeric,Float64,True
3,박물관,LND_AR_VALUE,numeric,Float64,True
4,박물관,EDC_FCLTY_AR_VALUE,numeric,Float64,True
5,박물관,DATA_SPCE_AR_VALUE,numeric,Float64,True
6,박물관,TOTAR_VALUE,numeric,Float64,True
7,박물관,CLTUR_GOODS_SPCE_AR_VALUE,numeric,Float64,True
8,박물관,RSTRNT_AR_VALUE,numeric,Float64,True
9,박물관,DATA_CO,numeric,Float64,True
10,박물관,TOT_PROGRM_CO,numeric,Float64,True
11,박물관,PROGRM_CO,numeric,Float64,True
12,박물관,FDRM_EXPRN_PROGRM_CO,numeric,Float64,True
13,박물관,NON_FDRM_EXPRN_PROGRM_CO,numeric,Float64,True
14,박물관,OUT_PROGRM_CO,numeric,Float64,True
15,박물관,VIEWNG_NMPR_CO,numeric,Float64,True
16,박물관,DAY_AVRG_VIEWNG_NMPR_CO,numeric,Float64,True
17,박물관,INFN_VIEWNG_PRICE,numeric,Float64,True
18,박물관,SCHBOY_VIEWNG_PRICE,numeric,Float64,True
19,박물관,ADULT_VIEWNG_PRICE,numeric,Float64,True
20,박물관,INFN_SPECL_VIEWNG_PRICE,numeric,Float64,True
21,박물관,ADULT_SPECL_VIEWNG_PRICE,numeric,Float64,True
22,박물관,NMPR_CO,numeric,Float64,True
23,박물관,QUALF_HOLD_CO,numeric,Float64,True
24,박물관,GNRL_GVRNM_EMP_CO,numeric,Float64,True
25,박물관,CNTRCT_EMP_CO,numeric,Float64,True
26,박물관,PUBLIC_VLNTER_CO,numeric,Float64,True
27,박물관,ARTGR_EMP_CO,numeric,Float64,True
28,박물관,PRFSN_CO,numeric,Float64,True
29,박물관,PRVATE_VLNTER_CO,numeric,Float64,True
30,박물관,CLTUR_ART_GVRNM_MANAGE_EMP_CO,numeric,Float64,True
31,박물관,CLTUR_ART_GVRNM_EMP_CO,numeric,Float64,True
32,박물관,INTN_EMP_CO,numeric,Float64,True
33,박물관,ETC_GNRL_EMP_CO,numeric,Float64,True
34,박물관,ETC_INTN_EMP_CO,numeric,Float64,True
35,박물관,SPECL_DSPY_AR_VALUE,numeric,Float64,True
36,박물관,HDCH_ARTFT_CAS_CO,numeric,Int64,True
37,박물관,HDCH_ARTFT_CO,numeric,Int64,True
38,박물관,VIEWNG_PRICE,numeric,Int64,True
39,박물관,SPECL_VIEWNG_PRICE,numeric,Int64,True
40,박물관,BASE_DE,datetime,datetime64[us],True
41,박물관,LAST_CHG_DE,datetime,datetime64[us],True
42,박물관,OPNNG_DE,datetime,datetime64[us],True

[미술관] 변환 완료 컬럼 dtype 검증

   dataset                    column expected_type    actual_dtype  is_valid
0      미술관                  FCLTY_LO       numeric         Float64      True
1      미술관                  FCLTY_LA       numeric         Float64      True
2      미술관              OPNNG_DAY_CO       numeric           Int64      True
3      미술관        EDC_FCLTY_AR_VALUE       numeric           Int64      True
4      미술관        DATA_SPCE_AR_VALUE       numeric         Float64      True
5      미술관             BULD_AR_VALUE       numeric           Int64      True
6      미술관                   DATA_CO       numeric           Int64      True
7      미술관             TOT_PROGRM_CO       numeric         Float64      True
8      미술관                   NMPR_CO       numeric           Int64      True
9      미술관             QUALF_HOLD_CO       numeric           Int64      True
10     미술관         GNRL_GVRNM_EMP_CO       numeric         Float64      True
11     미술관             CNTRCT_EMP_CO       numeric         Float64      True
12     미술관          PUBLIC_VLNTER_CO       numeric           Int64      True
13     미술관              ARTGR_EMP_CO       numeric         Float64      True
14     미술관                  PRFSN_CO       numeric         Float64      True
15     미술관          PRVATE_VLNTER_CO       numeric         Float64      True
16     미술관           GVRNM_EMP_SM_CO       numeric           Int64      True
17     미술관         TOT_CNTRCT_EMP_CO       numeric         Float64      True
18     미술관      CNTRCT_EMP_CRTFCT_CO       numeric         Float64      True
19     미술관            PUBLIC_INTN_CO       numeric         Float64      True
20     미술관       CURTR_QUALF_HOLD_CO       numeric         Float64      True
21     미술관  CURTR_NTHG_QUALF_HOLD_CO       numeric         Float64      True
22     미술관               GNRL_EMP_CO       numeric         Float64      True
23     미술관            PRVATE_INTN_CO       numeric         Float64      True
24     미술관              LND_AR_VALUE       numeric           Int64      True
25     미술관            VIEWNG_NMPR_CO       numeric           Int64      True
26     미술관   DAY_AVRG_VIEWNG_NMPR_CO       numeric           Int64      True
27     미술관                   BASE_DE      datetime  datetime64[us]      True
28     미술관               LAST_CHG_DE      datetime  datetime64[us]      True
29     미술관                  OPNNG_DE      datetime  datetime64[us]      True

[박물관] 검증 실패 컬럼

Empty DataFrame
Columns: [dataset, column, expected_type, actual_dtype, is_valid]
Index: []

[미술관] 검증 실패 컬럼

Empty DataFrame
Columns: [dataset, column, expected_type, actual_dtype, is_valid]
Index: []

### 03. 자료형 변환 단계 정리

##### 1) 숫자형 변환

- 쉼표가 포함된 숫자 문자열은 쉼표를 제거한 뒤 `numeric` 자료형으로 변환하였다.
- 숫자형 변환 가능 비율이 100%인 컬럼을 우선 변환하였다.
- 일부 비숫자 값이 섞여 있더라도 컬럼 의미상 숫자형으로 해석하는 것이 적절한 컬럼은 숫자형으로 변환하였다.
- 숫자로 해석하기 어려운 값은 `NaN`으로 처리되었다.
- 설명형 값, 복합 가격 정보, 문자 혼합 값이 많은 컬럼은 무리하게 변환하지 않고 보류하였다.

##### 2) 날짜형 변환

- `BASE_DE`, `LAST_CHG_DE`, `OPNNG_DE` 컬럼을 날짜형으로 변환하였다.
- `OPNNG_DE`는 개관일 정보이지만 연도만 있는 값, 연월만 있는 값, 복수 날짜가 포함된 값, 설명이 함께 적힌 값이 존재하였다.
- 따라서 `OPNNG_DE`의 원본 값은 `OPNNG_DE_RAW` 컬럼으로 보존하였다.
- 날짜로 해석 가능한 첫 번째 날짜 패턴을 추출하여 `OPNNG_DE`를 변환하였다.
- 날짜 정확도 수준을 구분하기 위해 `OPNNG_DE_PRECISION` 컬럼을 추가하였다.
  - `day`: 연월일 수준
  - `month`: 연월 수준
  - `year`: 연도 수준

##### 3) 변환 결과

- 박물관 데이터의 숫자형 변환 대상 컬럼은 정상적으로 변환되었다.
- 미술관 데이터의 숫자형 변환 대상 컬럼도 정상적으로 변환되었다.
- 날짜형 컬럼은 모두 `datetime` 자료형으로 변환되었다.
- 안전 변환 컬럼에서는 신규 결측치가 발생하지 않았다.
- 일부 문자값이 섞인 컬럼에서는 숫자로 해석할 수 없는 값이 `NaN`으로 처리되었다.

##### 4) 주의 사항

- 현재 단계에서는 자료형 변환만 진행하였다.
- 결측치 대체, 이상치 처리, 행 제거는 아직 추가로 진행하지 않았다.
- `DAY_AVRG_VIEWNG_NMPR_CO`는 숫자형으로 변환했지만, 이후 관람객 수 예측 모델에서 데이터 누수 가능성이 있으므로 입력 변수로 사용할 때 주의가 필요하다.

#### 04.1 박물관/미술관 통합 전 컬럼 정리

In [227]:
# 04.1 박물관/미술관 컬럼 구조 비교
# 통합 전 두 데이터셋의 공통 컬럼과 개별 컬럼을 확인한다.

museum_cols = set(museum_typed.columns)
art_cols = set(art_typed.columns)

common_cols = sorted(museum_cols & art_cols)
museum_only_cols = sorted(museum_cols - art_cols)
art_only_cols = sorted(art_cols - museum_cols)

column_structure_summary = pd.DataFrame([
    {
        "category": "박물관 전체 컬럼 수",
        "column_count": len(museum_typed.columns)
    },
    {
        "category": "미술관 전체 컬럼 수",
        "column_count": len(art_typed.columns)
    },
    {
        "category": "공통 컬럼 수",
        "column_count": len(common_cols)
    },
    {
        "category": "박물관에만 있는 컬럼 수",
        "column_count": len(museum_only_cols)
    },
    {
        "category": "미술관에만 있는 컬럼 수",
        "column_count": len(art_only_cols)
    }
])

display(column_structure_summary)

print("[공통 컬럼]")
print(common_cols)

print("\n[박물관에만 있는 컬럼]")
print(museum_only_cols)

print("\n[미술관에만 있는 컬럼]")
print(art_only_cols)

        category  column_count
0    박물관 전체 컬럼 수            79
1    미술관 전체 컬럼 수            66
2        공통 컬럼 수            57
3  박물관에만 있는 컬럼 수            22
4  미술관에만 있는 컬럼 수             9

[공통 컬럼]
['ADSTRD_NM', 'ADULT_SPECL_VIEWNG_PRICE', 'ADULT_VIEWNG_PRICE', 'ARTGR_EMP_CO', 'AR_CN', 'BASE_DE', 'CNTRCT_EMP_CO', 'CTPRVN_NM', 'DATA_CO', 'DATA_SPCE_AR_VALUE', 'DAY_AVRG_VIEWNG_NMPR_CO', 'DSPY_AR_CN', 'EDC_FCLTY_AR_VALUE', 'FCLTY_LA', 'FCLTY_LO', 'FCLTY_NM', 'FILE_NM', 'FLAG_NM', 'FRE_TRGET_CN', 'GID_CD', 'GNRL_GVRNM_EMP_CO', 'HMPG_ADDR', 'ID', 'INFN_SPECL_VIEWNG_PRICE', 'INFN_VIEWNG_PRICE', 'LAST_CHG_DE', 'LCLAS_NM', 'LEGALDONG_NM', 'LND_AR_VALUE', 'MLSFC_NM', 'MOBILE_PROVD_AT', 'MSKLSD_SPECL_VIEWNG_PRICE', 'MSKLSD_VIEWNG_PRICE', 'NMPR_CO', 'OFFM_AR_CN', 'OPNNG_DAY_CO', 'OPNNG_DE', 'OPNNG_DE_PRECISION', 'OPNNG_DE_RAW', 'ORIGIN_NM', 'PBLPRFR_CAS_CO', 'PRFSN_CO', 'PRVATE_VLNTER_CO', 'PUBLIC_VLNTER_CO', 'QUALF_HOLD_CO', 'RDNMADR_NM', 'SCHBOY_SPECL_VIEWNG_PRICE', 'SCHBOY_VIEWNG_PRICE', 'SIGNGU_NM', 'SOUND_PROVD_AT', 'SPECL_VIEWNG_PRICE', 'TEL_NO', 'TOT_PROGRM_CO', 'VIEWNG_NMPR_CO', 'VIEWNG_PRICE', 'ZIP_NO', 'facility_type']

[박물관에만 있는 컬럼]
['CLTUR_ART_GVRNM_EMP_CO', 'CLTUR_ART_GVRNM_MANAGE_EMP_CO', 'CLTUR_GOODS_SPCE_AR_VALUE', 'CRLTS_CO', 'CRLTS_NM', 'DSPYRM_ARTFT_CHG_CO', 'ETC_GNRL_EMP_CO', 'ETC_INTN_EMP_CO', 'FDRM_EXPRN_PROGRM_CO', 'HDCH_ARTFT_CAS_CO', 'HDCH_ARTFT_CO', 'HDCH_ARTFT_KND_CO', 'INTN_EMP_CO', 'NON_FDRM_EXPRN_PROGRM_CO', 'OPNNG_TIME', 'OUT_PROGRM_CO', 'PARKNG_POSBL_CO', 'PROGRM_CO', 'RSTRNT_AR_VALUE', 'SPECL_DSPY_AR_VALUE', 'TOTAR_VALUE', 'TP_SDIV_NM']

[미술관에만 있는 컬럼]
['BULD_AR_VALUE', 'CNTRCT_EMP_CRTFCT_CO', 'CURTR_NTHG_QUALF_HOLD_CO', 'CURTR_QUALF_HOLD_CO', 'GNRL_EMP_CO', 'GVRNM_EMP_SM_CO', 'PRVATE_INTN_CO', 'PUBLIC_INTN_CO', 'TOT_CNTRCT_EMP_CO']

In [228]:
# 공통 컬럼의 dtype 비교
# 같은 컬럼명이어도 자료형이 다르면 통합 전에 확인이 필요하다.

common_dtype_compare = pd.DataFrame({
    "column": common_cols,
    "museum_dtype": [str(museum_typed[col].dtype) for col in common_cols],
    "art_dtype": [str(art_typed[col].dtype) for col in common_cols]
})

common_dtype_compare["dtype_same"] = (
    common_dtype_compare["museum_dtype"] == common_dtype_compare["art_dtype"]
)

print("[공통 컬럼 dtype 비교]")
display(common_dtype_compare)

print("[dtype이 다른 공통 컬럼]")
display(
    common_dtype_compare[
        common_dtype_compare["dtype_same"] == False
    ]
)

[공통 컬럼 dtype 비교]

                       column    museum_dtype       art_dtype  dtype_same
0                   ADSTRD_NM             str             str        True
1    ADULT_SPECL_VIEWNG_PRICE         Float64             str       False
2          ADULT_VIEWNG_PRICE         Float64             str       False
3                ARTGR_EMP_CO         Float64         Float64        True
4                       AR_CN         float64         float64        True
5                     BASE_DE  datetime64[us]  datetime64[us]        True
6               CNTRCT_EMP_CO         Float64         Float64        True
7                   CTPRVN_NM             str             str        True
8                     DATA_CO         Float64           Int64       False
9          DATA_SPCE_AR_VALUE         Float64         Float64        True
10    DAY_AVRG_VIEWNG_NMPR_CO         Float64           Int64       False
11                 DSPY_AR_CN         float64             str       False
12         EDC_FCLTY_AR_VALUE         Float64           Int64       False
13                   FCLTY_LA         Float64         Float64        True
14                   FCLTY_LO         Float64         Float64        True
15                   FCLTY_NM             str             str        True
16                    FILE_NM             str             str        True
17                    FLAG_NM             str             str        True
18               FRE_TRGET_CN             str             str        True
19                     GID_CD             str             str        True
20          GNRL_GVRNM_EMP_CO         Float64         Float64        True
21                  HMPG_ADDR             str             str        True
22                         ID             str             str        True
23    INFN_SPECL_VIEWNG_PRICE         Float64             str       False
24          INFN_VIEWNG_PRICE         Float64             str       False
25                LAST_CHG_DE  datetime64[us]  datetime64[us]        True
26                   LCLAS_NM             str             str        True
27               LEGALDONG_NM             str             str        True
28               LND_AR_VALUE         Float64           Int64       False
29                   MLSFC_NM             str             str        True
30            MOBILE_PROVD_AT             str             str        True
31  MSKLSD_SPECL_VIEWNG_PRICE             str             str        True
32        MSKLSD_VIEWNG_PRICE             str             str        True
33                    NMPR_CO         Float64           Int64       False
34                 OFFM_AR_CN         float64             str       False
35               OPNNG_DAY_CO         Float64           Int64       False
36                   OPNNG_DE  datetime64[us]  datetime64[us]        True
37         OPNNG_DE_PRECISION             str             str        True
38               OPNNG_DE_RAW             str             str        True
39                  ORIGIN_NM             str             str        True
40             PBLPRFR_CAS_CO             str             str        True
41                   PRFSN_CO         Float64         Float64        True
42           PRVATE_VLNTER_CO         Float64         Float64        True
43           PUBLIC_VLNTER_CO         Float64           Int64       False
44              QUALF_HOLD_CO         Float64           Int64       False
45                 RDNMADR_NM             str             str        True
46  SCHBOY_SPECL_VIEWNG_PRICE             str             str        True
47        SCHBOY_VIEWNG_PRICE         Float64             str       False
48                  SIGNGU_NM             str             str        True
49             SOUND_PROVD_AT             str             str        True
50         SPECL_VIEWNG_PRICE           Int64             str       False
51                     TEL_NO             str             str        True
52              TOT_PROGRM_CO         Float64         Float64        True
53             VIEWNG_NMPR_CO         Float64           Int64       False
54               VIEWNG_PRICE           Int64             str       False
55                     ZIP_NO         float64           int64       False
56              facility_type             str             str        True

[dtype이 다른 공통 컬럼]

                      column museum_dtype art_dtype  dtype_same
1   ADULT_SPECL_VIEWNG_PRICE      Float64       str       False
2         ADULT_VIEWNG_PRICE      Float64       str       False
8                    DATA_CO      Float64     Int64       False
10   DAY_AVRG_VIEWNG_NMPR_CO      Float64     Int64       False
11                DSPY_AR_CN      float64       str       False
12        EDC_FCLTY_AR_VALUE      Float64     Int64       False
23   INFN_SPECL_VIEWNG_PRICE      Float64       str       False
24         INFN_VIEWNG_PRICE      Float64       str       False
28              LND_AR_VALUE      Float64     Int64       False
33                   NMPR_CO      Float64     Int64       False
34                OFFM_AR_CN      float64       str       False
35              OPNNG_DAY_CO      Float64     Int64       False
43          PUBLIC_VLNTER_CO      Float64     Int64       False
44             QUALF_HOLD_CO      Float64     Int64       False
47       SCHBOY_VIEWNG_PRICE      Float64       str       False
50        SPECL_VIEWNG_PRICE        Int64       str       False
53            VIEWNG_NMPR_CO      Float64     Int64       False
54              VIEWNG_PRICE        Int64       str       False
55                    ZIP_NO      float64     int64       False

In [229]:
# 통합 분석에서 우선적으로 사용할 핵심 컬럼 존재 여부 확인
# 이 단계에서는 컬럼을 제거하지 않고, 존재 여부만 확인한다.

core_check_cols = [
    # 구분 / 식별
    "facility_type", "ID", "FCLTY_NM",
    
    # 지역
    "CTPRVN_NM", "SIGNGU_NM",
    
    # 위치
    "FCLTY_LO", "FCLTY_LA",
    
    # 운영 / 날짜
    "OPNNG_DE", "OPNNG_DE_RAW", "OPNNG_DE_PRECISION",
    "OPNNG_DAY_CO", "BASE_DE", "LAST_CHG_DE",
    
    # 규모
    "LND_AR_VALUE", "BULD_AR_VALUE", "TOTAR_VALUE",
    
    # 인력
    "NMPR_CO",
    
    # 프로그램 / 전시 / 자료
    "DATA_CO", "TOT_PROGRM_CO", "PROGRM_CO",
    
    # 이용 성과
    "VIEWNG_NMPR_CO", "DAY_AVRG_VIEWNG_NMPR_CO"
]

core_col_check = pd.DataFrame({
    "column": core_check_cols,
    "in_museum": [col in museum_typed.columns for col in core_check_cols],
    "in_art": [col in art_typed.columns for col in core_check_cols]
})

core_col_check["in_both"] = (
    core_col_check["in_museum"] & core_col_check["in_art"]
)

display(core_col_check)

print("[박물관/미술관에 모두 존재하는 핵심 컬럼]")
print(core_col_check[core_col_check["in_both"]]["column"].tolist())

print("\n[한쪽에만 있거나 없는 핵심 컬럼]")
display(core_col_check[core_col_check["in_both"] == False])

                     column  in_museum  in_art  in_both
0             facility_type       True    True     True
1                        ID       True    True     True
2                  FCLTY_NM       True    True     True
3                 CTPRVN_NM       True    True     True
4                 SIGNGU_NM       True    True     True
5                  FCLTY_LO       True    True     True
6                  FCLTY_LA       True    True     True
7                  OPNNG_DE       True    True     True
8              OPNNG_DE_RAW       True    True     True
9        OPNNG_DE_PRECISION       True    True     True
10             OPNNG_DAY_CO       True    True     True
11                  BASE_DE       True    True     True
12              LAST_CHG_DE       True    True     True
13             LND_AR_VALUE       True    True     True
14            BULD_AR_VALUE      False    True    False
15              TOTAR_VALUE       True   False    False
16                  NMPR_CO       True    True     True
17                  DATA_CO       True    True     True
18            TOT_PROGRM_CO       True    True     True
19                PROGRM_CO       True   False    False
20           VIEWNG_NMPR_CO       True    True     True
21  DAY_AVRG_VIEWNG_NMPR_CO       True    True     True

[박물관/미술관에 모두 존재하는 핵심 컬럼]
['facility_type', 'ID', 'FCLTY_NM', 'CTPRVN_NM', 'SIGNGU_NM', 'FCLTY_LO', 'FCLTY_LA', 'OPNNG_DE', 'OPNNG_DE_RAW', 'OPNNG_DE_PRECISION', 'OPNNG_DAY_CO', 'BASE_DE', 'LAST_CHG_DE', 'LND_AR_VALUE', 'NMPR_CO', 'DATA_CO', 'TOT_PROGRM_CO', 'VIEWNG_NMPR_CO', 'DAY_AVRG_VIEWNG_NMPR_CO']

[한쪽에만 있거나 없는 핵심 컬럼]

           column  in_museum  in_art  in_both
14  BULD_AR_VALUE      False    True    False
15    TOTAR_VALUE       True   False    False
19      PROGRM_CO       True   False    False

#### 04.2 통합 기준 컬럼 선정

In [230]:
# 04.2 통합 분석 기준 컬럼 1차 선정
# 박물관/미술관에 모두 존재하고, 통합 분석에서 해석 가능한 컬럼 중심으로 선정한다.

common_analysis_cols = [
    # 구분 / 식별
    "facility_type",
    "ID",
    "FCLTY_NM",
    
    # 지역
    "CTPRVN_NM",
    "SIGNGU_NM",
    "LEGALDONG_NM",
    "ADSTRD_NM",
    
    # 위치
    "FCLTY_LO",
    "FCLTY_LA",
    
    # 운영 / 날짜
    "OPNNG_DE",
    "OPNNG_DE_RAW",
    "OPNNG_DE_PRECISION",
    "OPNNG_DAY_CO",
    "BASE_DE",
    "LAST_CHG_DE",
    
    # 시설 규모
    "LND_AR_VALUE",
    "EDC_FCLTY_AR_VALUE",
    "DATA_SPCE_AR_VALUE",
    
    # 인력
    "NMPR_CO",
    "QUALF_HOLD_CO",
    "GNRL_GVRNM_EMP_CO",
    "CNTRCT_EMP_CO",
    "PUBLIC_VLNTER_CO",
    "ARTGR_EMP_CO",
    "PRFSN_CO",
    "PRVATE_VLNTER_CO",
    
    # 자료 / 프로그램
    "DATA_CO",
    "TOT_PROGRM_CO",
    
    # 이용 성과
    "VIEWNG_NMPR_CO",
    "DAY_AVRG_VIEWNG_NMPR_CO",
    
    # 접근성 / 편의 정보
    "MOBILE_PROVD_AT",
    "SOUND_PROVD_AT",
    
    # 참고 정보
    "HMPG_ADDR",
    "TEL_NO"
]

# 실제 양쪽 데이터에 모두 존재하는 컬럼만 사용
common_analysis_cols = [
    col for col in common_analysis_cols
    if col in museum_typed.columns and col in art_typed.columns
]

print("통합 분석 기준 컬럼 수:", len(common_analysis_cols))
print(common_analysis_cols)

통합 분석 기준 컬럼 수: 34
['facility_type', 'ID', 'FCLTY_NM', 'CTPRVN_NM', 'SIGNGU_NM', 'LEGALDONG_NM', 'ADSTRD_NM', 'FCLTY_LO', 'FCLTY_LA', 'OPNNG_DE', 'OPNNG_DE_RAW', 'OPNNG_DE_PRECISION', 'OPNNG_DAY_CO', 'BASE_DE', 'LAST_CHG_DE', 'LND_AR_VALUE', 'EDC_FCLTY_AR_VALUE', 'DATA_SPCE_AR_VALUE', 'NMPR_CO', 'QUALF_HOLD_CO', 'GNRL_GVRNM_EMP_CO', 'CNTRCT_EMP_CO', 'PUBLIC_VLNTER_CO', 'ARTGR_EMP_CO', 'PRFSN_CO', 'PRVATE_VLNTER_CO', 'DATA_CO', 'TOT_PROGRM_CO', 'VIEWNG_NMPR_CO', 'DAY_AVRG_VIEWNG_NMPR_CO', 'MOBILE_PROVD_AT', 'SOUND_PROVD_AT', 'HMPG_ADDR', 'TEL_NO']

In [231]:
# 시설 유형별로만 존재하는 컬럼 중 분석 가치가 있어 보이는 컬럼 정리
# 이 컬럼들은 통합 데이터의 기본 컬럼으로 바로 넣지 않고,
# 박물관/미술관 개별 분석에서 활용할 수 있다.

museum_specific_analysis_cols = [
    # 박물관 특화 규모 / 전시 / 자료
    "TOTAR_VALUE",
    "SPECL_DSPY_AR_VALUE",
    "CLTUR_GOODS_SPCE_AR_VALUE",
    "RSTRNT_AR_VALUE",
    "PARKNG_POSBL_CO",
    
    # 박물관 소장자료 / 프로그램
    "HDCH_ARTFT_KND_CO",
    "HDCH_ARTFT_CAS_CO",
    "HDCH_ARTFT_CO",
    "CRLTS_CO",
    "PROGRM_CO",
    "FDRM_EXPRN_PROGRM_CO",
    "NON_FDRM_EXPRN_PROGRM_CO",
    "OUT_PROGRM_CO",
    
    # 박물관 특화 인력
    "CLTUR_ART_GVRNM_MANAGE_EMP_CO",
    "CLTUR_ART_GVRNM_EMP_CO",
    "INTN_EMP_CO",
    "ETC_GNRL_EMP_CO",
    "ETC_INTN_EMP_CO"
]

art_specific_analysis_cols = [
    # 미술관 특화 규모
    "BULD_AR_VALUE",
    
    # 미술관 특화 인력
    "GVRNM_EMP_SM_CO",
    "TOT_CNTRCT_EMP_CO",
    "CNTRCT_EMP_CRTFCT_CO",
    "PUBLIC_INTN_CO",
    "CURTR_QUALF_HOLD_CO",
    "CURTR_NTHG_QUALF_HOLD_CO",
    "GNRL_EMP_CO",
    "PRVATE_INTN_CO"
]

museum_specific_analysis_cols = [
    col for col in museum_specific_analysis_cols
    if col in museum_typed.columns
]

art_specific_analysis_cols = [
    col for col in art_specific_analysis_cols
    if col in art_typed.columns
]

print("[박물관 개별 분석 후보 컬럼 수]", len(museum_specific_analysis_cols))
print(museum_specific_analysis_cols)

print("\n[미술관 개별 분석 후보 컬럼 수]", len(art_specific_analysis_cols))
print(art_specific_analysis_cols)

[박물관 개별 분석 후보 컬럼 수] 18
['TOTAR_VALUE', 'SPECL_DSPY_AR_VALUE', 'CLTUR_GOODS_SPCE_AR_VALUE', 'RSTRNT_AR_VALUE', 'PARKNG_POSBL_CO', 'HDCH_ARTFT_KND_CO', 'HDCH_ARTFT_CAS_CO', 'HDCH_ARTFT_CO', 'CRLTS_CO', 'PROGRM_CO', 'FDRM_EXPRN_PROGRM_CO', 'NON_FDRM_EXPRN_PROGRM_CO', 'OUT_PROGRM_CO', 'CLTUR_ART_GVRNM_MANAGE_EMP_CO', 'CLTUR_ART_GVRNM_EMP_CO', 'INTN_EMP_CO', 'ETC_GNRL_EMP_CO', 'ETC_INTN_EMP_CO']

[미술관 개별 분석 후보 컬럼 수] 9
['BULD_AR_VALUE', 'GVRNM_EMP_SM_CO', 'TOT_CNTRCT_EMP_CO', 'CNTRCT_EMP_CRTFCT_CO', 'PUBLIC_INTN_CO', 'CURTR_QUALF_HOLD_CO', 'CURTR_NTHG_QUALF_HOLD_CO', 'GNRL_EMP_CO', 'PRVATE_INTN_CO']

In [232]:
# 통합 기준 컬럼만 대상으로 dtype 차이를 다시 확인한다.
# 전체 공통 컬럼에서는 가격/설명형 컬럼까지 포함되어 dtype 차이가 많았지만,
# 실제 통합 분석 기준 컬럼에서는 관리 가능한지 확인한다.

common_analysis_dtype_compare = pd.DataFrame({
    "column": common_analysis_cols,
    "museum_dtype": [str(museum_typed[col].dtype) for col in common_analysis_cols],
    "art_dtype": [str(art_typed[col].dtype) for col in common_analysis_cols]
})

common_analysis_dtype_compare["dtype_same"] = (
    common_analysis_dtype_compare["museum_dtype"] == common_analysis_dtype_compare["art_dtype"]
)

print("[통합 분석 기준 컬럼 dtype 비교]")
display(common_analysis_dtype_compare)

print("[통합 분석 기준 컬럼 중 dtype이 다른 컬럼]")
display(
    common_analysis_dtype_compare[
        common_analysis_dtype_compare["dtype_same"] == False
    ]
)

[통합 분석 기준 컬럼 dtype 비교]

                     column    museum_dtype       art_dtype  dtype_same
0             facility_type             str             str        True
1                        ID             str             str        True
2                  FCLTY_NM             str             str        True
3                 CTPRVN_NM             str             str        True
4                 SIGNGU_NM             str             str        True
5              LEGALDONG_NM             str             str        True
6                 ADSTRD_NM             str             str        True
7                  FCLTY_LO         Float64         Float64        True
8                  FCLTY_LA         Float64         Float64        True
9                  OPNNG_DE  datetime64[us]  datetime64[us]        True
10             OPNNG_DE_RAW             str             str        True
11       OPNNG_DE_PRECISION             str             str        True
12             OPNNG_DAY_CO         Float64           Int64       False
13                  BASE_DE  datetime64[us]  datetime64[us]        True
14              LAST_CHG_DE  datetime64[us]  datetime64[us]        True
15             LND_AR_VALUE         Float64           Int64       False
16       EDC_FCLTY_AR_VALUE         Float64           Int64       False
17       DATA_SPCE_AR_VALUE         Float64         Float64        True
18                  NMPR_CO         Float64           Int64       False
19            QUALF_HOLD_CO         Float64           Int64       False
20        GNRL_GVRNM_EMP_CO         Float64         Float64        True
21            CNTRCT_EMP_CO         Float64         Float64        True
22         PUBLIC_VLNTER_CO         Float64           Int64       False
23             ARTGR_EMP_CO         Float64         Float64        True
24                 PRFSN_CO         Float64         Float64        True
25         PRVATE_VLNTER_CO         Float64         Float64        True
26                  DATA_CO         Float64           Int64       False
27            TOT_PROGRM_CO         Float64         Float64        True
28           VIEWNG_NMPR_CO         Float64           Int64       False
29  DAY_AVRG_VIEWNG_NMPR_CO         Float64           Int64       False
30          MOBILE_PROVD_AT             str             str        True
31           SOUND_PROVD_AT             str             str        True
32                HMPG_ADDR             str             str        True
33                   TEL_NO             str             str        True

[통합 분석 기준 컬럼 중 dtype이 다른 컬럼]

                     column museum_dtype art_dtype  dtype_same
12             OPNNG_DAY_CO      Float64     Int64       False
15             LND_AR_VALUE      Float64     Int64       False
16       EDC_FCLTY_AR_VALUE      Float64     Int64       False
18                  NMPR_CO      Float64     Int64       False
19            QUALF_HOLD_CO      Float64     Int64       False
22         PUBLIC_VLNTER_CO      Float64     Int64       False
26                  DATA_CO      Float64     Int64       False
28           VIEWNG_NMPR_CO      Float64     Int64       False
29  DAY_AVRG_VIEWNG_NMPR_CO      Float64     Int64       False

In [233]:
# 통합 전 기준 컬럼만 선택한 데이터셋 생성
# 아직 concat으로 통합하지 않고, 두 데이터셋의 형태만 맞춰 확인한다.

museum_common = museum_typed[common_analysis_cols].copy()
art_common = art_typed[common_analysis_cols].copy()

print("박물관 통합 기준 데이터 크기:", museum_common.shape)
print("미술관 통합 기준 데이터 크기:", art_common.shape)

print("\n[박물관 통합 기준 데이터 미리보기]")
display(museum_common.head())

print("\n[미술관 통합 기준 데이터 미리보기]")
display(art_common.head())

박물관 통합 기준 데이터 크기: (897, 34)
미술관 통합 기준 데이터 크기: (294, 34)

[박물관 통합 기준 데이터 미리보기]

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,LEGALDONG_NM,ADSTRD_NM,FCLTY_LO,FCLTY_LA,OPNNG_DE,...,PRFSN_CO,PRVATE_VLNTER_CO,DATA_CO,TOT_PROGRM_CO,VIEWNG_NMPR_CO,DAY_AVRG_VIEWNG_NMPR_CO,MOBILE_PROVD_AT,SOUND_PROVD_AT,HMPG_ADDR,TEL_NO
0,박물관,KCDMMUS23N000000001,국립중앙박물관,서울,용산구,용산동6가,한강로동,126.97774,37.524702,1945-12-03,...,<NA>,<NA>,157323.0,16.0,4180285.0,11612.0,O,O,www.museum.go.kr,02-2077-9000
1,박물관,KCDMMUS23N000000002,국립민속박물관,서울,종로구,세종로,청운효자동,126.97889,37.581675,1946-04-25,...,<NA>,<NA>,92786.0,70.0,1307690.0,3612.0,O,X,www.nfm.go.kr,02-3704-3114
2,박물관,KCDMMUS23N000000003,국립민속박물관 파주\n(개방형 수장고 및 정보센터),경기,파주시,탄현면 법흥리,탄현면,126.693918,37.78667,2021-07-23,...,<NA>,<NA>,<NA>,10.0,83306.0,266.0,X,X,www.nfm.go.kr,031-580-5800
3,박물관,KCDMMUS23N000000004,대한민국역사박물관,서울,종로구,세종로,종로1.2.3.4가동,126.978339,37.573714,2012-12-26,...,<NA>,<NA>,18065.0,34.0,788347.0,2178.0,O,O,www.much.go.kr,02-3703-9200
4,박물관,KCDMMUS23N000000005,국립한글박물관,서울,용산구,용산동6가,서빙고동,126.980486,37.521069,2014-10-09,...,<NA>,<NA>,30059.0,33.0,397107.0,1097.0,O,O,www.hangeul.go.kr,02-2124-6200

[미술관 통합 기준 데이터 미리보기]

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,LEGALDONG_NM,ADSTRD_NM,FCLTY_LO,FCLTY_LA,OPNNG_DE,...,PRFSN_CO,PRVATE_VLNTER_CO,DATA_CO,TOT_PROGRM_CO,VIEWNG_NMPR_CO,DAY_AVRG_VIEWNG_NMPR_CO,MOBILE_PROVD_AT,SOUND_PROVD_AT,HMPG_ADDR,TEL_NO
0,미술관,KCDMART25N000000001,국립현대미술관(과천관),경기,과천시,막계동,문원동,127.01993,37.431003,1986-08-25,...,<NA>,<NA>,69358,28.0,562604,1797,O,O,"www.mmca.go.kr, \nwww.facebook.com/MMCAKorea, ...",02-2188-6114
1,미술관,KCDMART25N000000002,국립현대미술관(서울관),서울,종로구,소격동,삼청동,126.980033,37.578744,2013-11-12,...,<NA>,<NA>,44409,88.0,1655834,4574,O,O,"www.mmca.go.kr, www.facebook.com/MMCAKorea, \n...",02-3701-9500
2,미술관,KCDMART25N000000003,국립현대미술관(덕수궁관),서울,중구,정동,소공동,126.973726,37.566087,1998-12-01,...,<NA>,<NA>,<NA>,1.0,459146,2639,O,O,"www.mmca.go.kr, www.facebook.com/MMCAKorea, \n...",02-2022-0600
3,미술관,KCDMART25N000000004,국립현대미술관 미술품수장센터(청주관),충북,청주시,내덕동,내덕2동,127.492382,36.656196,2018-12-27,...,<NA>,<NA>,4120,16.0,269870,862,O,O,"www.mmca.go.kr, www.facebook.com/MMCAKorea, \n...",043-261-1400
4,미술관,KCDMART25N000000005,DDP디자인뮤지엄,서울,중구,을지로7가,광희동,127.01089,37.568045,2020-02-17,...,<NA>,<NA>,<NA>,15.0,855433,2363,X,X,www.ddp.or.kr,02-2153-0066

In [234]:
# 04.3 통합 전 dtype 통일
# 통합 기준 컬럼 중 숫자형 컬럼은 박물관/미술관 모두 Float64로 통일한다.
# Int64와 Float64가 섞여 있으면 concat 후 dtype이 달라질 수 있으므로 사전에 맞춘다.

common_numeric_cols = [
    "FCLTY_LO",
    "FCLTY_LA",
    "OPNNG_DAY_CO",
    "LND_AR_VALUE",
    "EDC_FCLTY_AR_VALUE",
    "DATA_SPCE_AR_VALUE",
    "NMPR_CO",
    "QUALF_HOLD_CO",
    "GNRL_GVRNM_EMP_CO",
    "CNTRCT_EMP_CO",
    "PUBLIC_VLNTER_CO",
    "ARTGR_EMP_CO",
    "PRFSN_CO",
    "PRVATE_VLNTER_CO",
    "DATA_CO",
    "TOT_PROGRM_CO",
    "VIEWNG_NMPR_CO",
    "DAY_AVRG_VIEWNG_NMPR_CO"
]

# 실제 통합 기준 데이터에 존재하는 컬럼만 사용
common_numeric_cols = [
    col for col in common_numeric_cols
    if col in museum_common.columns and col in art_common.columns
]

for col in common_numeric_cols:
    museum_common[col] = museum_common[col].astype("Float64")
    art_common[col] = art_common[col].astype("Float64")

print("통합 기준 숫자형 컬럼 Float64 통일 완료")
print("대상 컬럼 수:", len(common_numeric_cols))
print(common_numeric_cols)

통합 기준 숫자형 컬럼 Float64 통일 완료
대상 컬럼 수: 18
['FCLTY_LO', 'FCLTY_LA', 'OPNNG_DAY_CO', 'LND_AR_VALUE', 'EDC_FCLTY_AR_VALUE', 'DATA_SPCE_AR_VALUE', 'NMPR_CO', 'QUALF_HOLD_CO', 'GNRL_GVRNM_EMP_CO', 'CNTRCT_EMP_CO', 'PUBLIC_VLNTER_CO', 'ARTGR_EMP_CO', 'PRFSN_CO', 'PRVATE_VLNTER_CO', 'DATA_CO', 'TOT_PROGRM_CO', 'VIEWNG_NMPR_CO', 'DAY_AVRG_VIEWNG_NMPR_CO']

In [235]:
# dtype 통일 후 박물관/미술관 공통 컬럼의 dtype이 일치하는지 재확인한다.

common_analysis_dtype_compare_after = pd.DataFrame({
    "column": common_analysis_cols,
    "museum_dtype": [str(museum_common[col].dtype) for col in common_analysis_cols],
    "art_dtype": [str(art_common[col].dtype) for col in common_analysis_cols]
})

common_analysis_dtype_compare_after["dtype_same"] = (
    common_analysis_dtype_compare_after["museum_dtype"] ==
    common_analysis_dtype_compare_after["art_dtype"]
)

print("[통합 기준 컬럼 dtype 통일 후 비교]")
display(common_analysis_dtype_compare_after)

print("[dtype이 아직 다른 컬럼]")
display(
    common_analysis_dtype_compare_after[
        common_analysis_dtype_compare_after["dtype_same"] == False
    ]
)

[통합 기준 컬럼 dtype 통일 후 비교]

                     column    museum_dtype       art_dtype  dtype_same
0             facility_type             str             str        True
1                        ID             str             str        True
2                  FCLTY_NM             str             str        True
3                 CTPRVN_NM             str             str        True
4                 SIGNGU_NM             str             str        True
5              LEGALDONG_NM             str             str        True
6                 ADSTRD_NM             str             str        True
7                  FCLTY_LO         Float64         Float64        True
8                  FCLTY_LA         Float64         Float64        True
9                  OPNNG_DE  datetime64[us]  datetime64[us]        True
10             OPNNG_DE_RAW             str             str        True
11       OPNNG_DE_PRECISION             str             str        True
12             OPNNG_DAY_CO         Float64         Float64        True
13                  BASE_DE  datetime64[us]  datetime64[us]        True
14              LAST_CHG_DE  datetime64[us]  datetime64[us]        True
15             LND_AR_VALUE         Float64         Float64        True
16       EDC_FCLTY_AR_VALUE         Float64         Float64        True
17       DATA_SPCE_AR_VALUE         Float64         Float64        True
18                  NMPR_CO         Float64         Float64        True
19            QUALF_HOLD_CO         Float64         Float64        True
20        GNRL_GVRNM_EMP_CO         Float64         Float64        True
21            CNTRCT_EMP_CO         Float64         Float64        True
22         PUBLIC_VLNTER_CO         Float64         Float64        True
23             ARTGR_EMP_CO         Float64         Float64        True
24                 PRFSN_CO         Float64         Float64        True
25         PRVATE_VLNTER_CO         Float64         Float64        True
26                  DATA_CO         Float64         Float64        True
27            TOT_PROGRM_CO         Float64         Float64        True
28           VIEWNG_NMPR_CO         Float64         Float64        True
29  DAY_AVRG_VIEWNG_NMPR_CO         Float64         Float64        True
30          MOBILE_PROVD_AT             str             str        True
31           SOUND_PROVD_AT             str             str        True
32                HMPG_ADDR             str             str        True
33                   TEL_NO             str             str        True

[dtype이 아직 다른 컬럼]

Empty DataFrame
Columns: [column, museum_dtype, art_dtype, dtype_same]
Index: []

In [236]:
# 통합 전 두 데이터셋의 컬럼 순서와 크기를 최종 확인한다.
# 아직 concat은 하지 않는다.

print("박물관 통합 기준 데이터 크기:", museum_common.shape)
print("미술관 통합 기준 데이터 크기:", art_common.shape)

print("\n컬럼 순서 일치 여부:", list(museum_common.columns) == list(art_common.columns))

if list(museum_common.columns) == list(art_common.columns):
    print("컬럼 순서가 동일합니다.")
else:
    print("컬럼 순서가 다릅니다. 통합 전 컬럼 순서를 맞춰야 합니다.")

print("\n박물관 컬럼 수:", len(museum_common.columns))
print("미술관 컬럼 수:", len(art_common.columns))

박물관 통합 기준 데이터 크기: (897, 34)
미술관 통합 기준 데이터 크기: (294, 34)

컬럼 순서 일치 여부: True
컬럼 순서가 동일합니다.

박물관 컬럼 수: 34
미술관 컬럼 수: 34

In [237]:
# 통합 전 ID, 시설명, 시설유형 값이 정상적으로 들어있는지 확인한다.

pre_concat_check = pd.DataFrame([
    {
        "dataset": "박물관",
        "row_count": len(museum_common),
        "column_count": museum_common.shape[1],
        "id_missing_count": museum_common["ID"].isna().sum(),
        "id_duplicate_count": museum_common["ID"].duplicated().sum(),
        "facility_name_missing_count": museum_common["FCLTY_NM"].isna().sum(),
        "facility_type_unique": ", ".join(museum_common["facility_type"].dropna().unique())
    },
    {
        "dataset": "미술관",
        "row_count": len(art_common),
        "column_count": art_common.shape[1],
        "id_missing_count": art_common["ID"].isna().sum(),
        "id_duplicate_count": art_common["ID"].duplicated().sum(),
        "facility_name_missing_count": art_common["FCLTY_NM"].isna().sum(),
        "facility_type_unique": ", ".join(art_common["facility_type"].dropna().unique())
    }
])

display(pre_concat_check)

,dataset,row_count,column_count,id_missing_count,id_duplicate_count,facility_name_missing_count,facility_type_unique
0,박물관,897,34,0,0,0,박물관
1,미술관,294,34,0,0,0,미술관

### 04. 박물관/미술관 통합 전 컬럼 정리 결과

#### 1) 컬럼 구조 비교

- 박물관 데이터는 자료형 변환 후 79개 컬럼으로 구성되어 있다.
- 미술관 데이터는 자료형 변환 후 66개 컬럼으로 구성되어 있다.
- 두 데이터셋의 공통 컬럼은 57개이다.
- 박물관에만 존재하는 컬럼은 22개, 미술관에만 존재하는 컬럼은 9개이다.

#### 2) 통합 분석 기준 컬럼 선정

- 박물관과 미술관에 모두 존재하고, 통합 분석에서 공통적으로 해석 가능한 컬럼을 중심으로 34개 컬럼을 선정하였다.
- 선정한 컬럼은 식별 정보, 지역 정보, 위치 정보, 운영 정보, 시설 규모, 인력, 자료/프로그램, 이용 성과, 접근성/편의 정보로 구성하였다.
- 박물관에만 존재하는 `TOTAR_VALUE`, `PROGRM_CO` 등은 통합 기본 컬럼에서는 제외하고, 박물관 개별 분석 후보로 보류하였다.
- 미술관에만 존재하는 `BULD_AR_VALUE` 등은 통합 기본 컬럼에서는 제외하고, 미술관 개별 분석 후보로 보류하였다.

#### 3) dtype 통일

- 통합 기준 컬럼 중 숫자형 컬럼은 박물관과 미술관 모두 `Float64`로 통일하였다.
- dtype 통일 후 박물관과 미술관의 통합 기준 컬럼 자료형은 모두 일치하였다.
- 컬럼 순서도 동일하게 맞춰졌으며, 통합 가능한 형태로 정리되었다.

#### 4) 통합 전 검증 결과

- 박물관 통합 기준 데이터 크기: `(897, 34)`
- 미술관 통합 기준 데이터 크기: `(294, 34)`
- 두 데이터셋의 컬럼 순서는 동일하다.
- `ID` 결측치는 박물관과 미술관 모두 0개이다.
- `ID` 중복값은 박물관과 미술관 모두 0개이다.
- 시설명 결측치는 박물관과 미술관 모두 0개이다.
- `facility_type` 값은 박물관 데이터에서 `"박물관"`, 미술관 데이터에서 `"미술관"`으로 정상 입력되어 있다.

#### 5) 주의 사항

- 아직 박물관과 미술관 데이터를 실제로 통합하지는 않았다.
- 현재 단계에서는 통합 가능한 컬럼 구조와 자료형을 맞추는 작업까지만 진행하였다.
- 다음 단계에서 `museum_common`과 `art_common`을 행 기준으로 결합하여 통합 데이터셋을 생성한다.

#### 05. 박물관/미술관 데이터 통합

In [238]:
# 05.1 박물관/미술관 데이터 통합
# 04 단계에서 컬럼 구조와 dtype을 맞춘 museum_common, art_common을 행 기준으로 결합한다.

facility_common = pd.concat(
    [museum_common, art_common],
    axis=0,
    ignore_index=True
)

print("통합 데이터 크기:", facility_common.shape)

print("\n시설 유형별 행 수")
display(facility_common["facility_type"].value_counts().to_frame("count"))

print("\n통합 데이터 미리보기")
display(facility_common.head())

통합 데이터 크기: (1191, 34)

시설 유형별 행 수

               count
facility_type
박물관              897
미술관              294

통합 데이터 미리보기

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,LEGALDONG_NM,ADSTRD_NM,FCLTY_LO,FCLTY_LA,OPNNG_DE,...,PRFSN_CO,PRVATE_VLNTER_CO,DATA_CO,TOT_PROGRM_CO,VIEWNG_NMPR_CO,DAY_AVRG_VIEWNG_NMPR_CO,MOBILE_PROVD_AT,SOUND_PROVD_AT,HMPG_ADDR,TEL_NO
0,박물관,KCDMMUS23N000000001,국립중앙박물관,서울,용산구,용산동6가,한강로동,126.97774,37.524702,1945-12-03,...,<NA>,<NA>,157323.0,16.0,4180285.0,11612.0,O,O,www.museum.go.kr,02-2077-9000
1,박물관,KCDMMUS23N000000002,국립민속박물관,서울,종로구,세종로,청운효자동,126.97889,37.581675,1946-04-25,...,<NA>,<NA>,92786.0,70.0,1307690.0,3612.0,O,X,www.nfm.go.kr,02-3704-3114
2,박물관,KCDMMUS23N000000003,국립민속박물관 파주\n(개방형 수장고 및 정보센터),경기,파주시,탄현면 법흥리,탄현면,126.693918,37.78667,2021-07-23,...,<NA>,<NA>,<NA>,10.0,83306.0,266.0,X,X,www.nfm.go.kr,031-580-5800
3,박물관,KCDMMUS23N000000004,대한민국역사박물관,서울,종로구,세종로,종로1.2.3.4가동,126.978339,37.573714,2012-12-26,...,<NA>,<NA>,18065.0,34.0,788347.0,2178.0,O,O,www.much.go.kr,02-3703-9200
4,박물관,KCDMMUS23N000000005,국립한글박물관,서울,용산구,용산동6가,서빙고동,126.980486,37.521069,2014-10-09,...,<NA>,<NA>,30059.0,33.0,397107.0,1097.0,O,O,www.hangeul.go.kr,02-2124-6200

In [239]:
# 05.2 통합 후 기본 검증
# 행 수, 컬럼 수, ID 결측/중복, 시설 유형 값을 확인한다.

concat_validation = pd.DataFrame([
    {
        "check_item": "통합 전 박물관 행 수",
        "value": len(museum_common)
    },
    {
        "check_item": "통합 전 미술관 행 수",
        "value": len(art_common)
    },
    {
        "check_item": "통합 후 전체 행 수",
        "value": len(facility_common)
    },
    {
        "check_item": "통합 전 행 수 합계",
        "value": len(museum_common) + len(art_common)
    },
    {
        "check_item": "통합 후 컬럼 수",
        "value": facility_common.shape[1]
    },
    {
        "check_item": "ID 결측치 수",
        "value": facility_common["ID"].isna().sum()
    },
    {
        "check_item": "ID 중복 수",
        "value": facility_common["ID"].duplicated().sum()
    },
    {
        "check_item": "시설명 결측치 수",
        "value": facility_common["FCLTY_NM"].isna().sum()
    }
])

display(concat_validation)

print("시설 유형 고유값:")
print(facility_common["facility_type"].unique())

     check_item  value
0  통합 전 박물관 행 수    897
1  통합 전 미술관 행 수    294
2   통합 후 전체 행 수   1191
3   통합 전 행 수 합계   1191
4     통합 후 컬럼 수     34
5      ID 결측치 수      0
6       ID 중복 수      0
7     시설명 결측치 수      0

시설 유형 고유값:
<StringArray>
['박물관', '미술관']
Length: 2, dtype: str

In [240]:
# 05.3 통합 데이터 결측치 구조 확인
# 통합 후 공통 분석 컬럼의 결측치 현황을 확인한다.

facility_missing = missing_summary(facility_common)

print("[통합 데이터 결측치 요약]")
display(facility_missing)

print("[통합 데이터 결측치가 있는 컬럼]")
display(
    facility_missing[
        facility_missing["missing_count"] > 0
    ]
)

[통합 데이터 결측치 요약]

,column,missing_count,missing_rate,non_missing_count,dtype,unique_count
0,PRVATE_VLNTER_CO,1074,90.18,117,Float64,32
1,CNTRCT_EMP_CO,1019,85.56,172,Float64,12
2,PUBLIC_VLNTER_CO,1008,84.63,183,Float64,80
3,PRFSN_CO,983,82.54,208,Float64,14
4,GNRL_GVRNM_EMP_CO,901,75.65,290,Float64,30
5,QUALF_HOLD_CO,755,63.39,436,Float64,17
6,ARTGR_EMP_CO,648,54.41,543,Float64,37
7,NMPR_CO,541,45.42,650,Float64,68
8,DATA_CO,528,44.33,663,Float64,405
9,DATA_SPCE_AR_VALUE,510,42.82,681,Float64,267
10,EDC_FCLTY_AR_VALUE,331,27.79,860,Float64,464
11,TOT_PROGRM_CO,284,23.85,907,Float64,59
12,HMPG_ADDR,94,7.89,1097,str,1048
13,VIEWNG_NMPR_CO,54,4.53,1137,Float64,998
14,DAY_AVRG_VIEWNG_NMPR_CO,54,4.53,1137,Float64,453
15,OPNNG_DAY_CO,41,3.44,1150,Float64,199
16,LND_AR_VALUE,14,1.18,1177,Float64,1104
17,MOBILE_PROVD_AT,9,0.76,1182,str,2
18,SOUND_PROVD_AT,8,0.67,1183,str,3
19,TEL_NO,4,0.34,1187,str,1168
20,facility_type,0,0.00,1191,str,2
21,ID,0,0.00,1191,str,1191
22,FCLTY_NM,0,0.00,1191,str,1191
23,CTPRVN_NM,0,0.00,1191,str,20
24,SIGNGU_NM,0,0.00,1191,str,224
25,LEGALDONG_NM,0,0.00,1191,str,912
26,ADSTRD_NM,0,0.00,1191,str,723
27,FCLTY_LO,0,0.00,1191,Float64,1153
28,FCLTY_LA,0,0.00,1191,Float64,1153
29,OPNNG_DE,0,0.00,1191,datetime64[us],1095
30,OPNNG_DE_RAW,0,0.00,1191,str,1099
31,OPNNG_DE_PRECISION,0,0.00,1191,str,3
32,BASE_DE,0,0.00,1191,datetime64[us],2
33,LAST_CHG_DE,0,0.00,1191,datetime64[us],2

[통합 데이터 결측치가 있는 컬럼]

,column,missing_count,missing_rate,non_missing_count,dtype,unique_count
0,PRVATE_VLNTER_CO,1074,90.18,117,Float64,32
1,CNTRCT_EMP_CO,1019,85.56,172,Float64,12
2,PUBLIC_VLNTER_CO,1008,84.63,183,Float64,80
3,PRFSN_CO,983,82.54,208,Float64,14
4,GNRL_GVRNM_EMP_CO,901,75.65,290,Float64,30
5,QUALF_HOLD_CO,755,63.39,436,Float64,17
6,ARTGR_EMP_CO,648,54.41,543,Float64,37
7,NMPR_CO,541,45.42,650,Float64,68
8,DATA_CO,528,44.33,663,Float64,405
9,DATA_SPCE_AR_VALUE,510,42.82,681,Float64,267
10,EDC_FCLTY_AR_VALUE,331,27.79,860,Float64,464
11,TOT_PROGRM_CO,284,23.85,907,Float64,59
12,HMPG_ADDR,94,7.89,1097,str,1048
13,VIEWNG_NMPR_CO,54,4.53,1137,Float64,998
14,DAY_AVRG_VIEWNG_NMPR_CO,54,4.53,1137,Float64,453
15,OPNNG_DAY_CO,41,3.44,1150,Float64,199
16,LND_AR_VALUE,14,1.18,1177,Float64,1104
17,MOBILE_PROVD_AT,9,0.76,1182,str,2
18,SOUND_PROVD_AT,8,0.67,1183,str,3
19,TEL_NO,4,0.34,1187,str,1168

In [241]:
# 시설 유형별 결측치 비교
# 같은 컬럼이라도 박물관/미술관별 결측 양상이 다를 수 있으므로 분리해서 확인한다.

def missing_summary_by_facility_type(df, group_col="facility_type"):
    rows = []
    
    for facility_type, group_df in df.groupby(group_col):
        for col in group_df.columns:
            if col == group_col:
                continue
            
            rows.append({
                "facility_type": facility_type,
                "column": col,
                "missing_count": group_df[col].isna().sum(),
                "missing_rate": round(group_df[col].isna().mean() * 100, 2),
                "non_missing_count": group_df[col].notna().sum(),
                "dtype": str(group_df[col].dtype),
                "unique_count": group_df[col].nunique(dropna=True)
            })
    
    return pd.DataFrame(rows)


facility_missing_by_type = missing_summary_by_facility_type(facility_common)

print("[시설 유형별 결측치 비교]")
display(
    facility_missing_by_type.sort_values(
        by=["column", "facility_type"]
    )
)

[시설 유형별 결측치 비교]

,facility_type,column,missing_count,missing_rate,non_missing_count,dtype,unique_count
5,미술관,ADSTRD_NM,0,0.00,294,str,233
38,박물관,ADSTRD_NM,0,0.00,897,str,599
22,미술관,ARTGR_EMP_CO,84,28.57,210,Float64,35
55,박물관,ARTGR_EMP_CO,564,62.88,333,Float64,14
12,미술관,BASE_DE,0,0.00,294,datetime64[us],1
...,...,...,...,...,...,...,...
65,박물관,TEL_NO,4,0.45,893,str,884
26,미술관,TOT_PROGRM_CO,68,23.13,226,Float64,36
59,박물관,TOT_PROGRM_CO,216,24.08,681,Float64,53
27,미술관,VIEWNG_NMPR_CO,13,4.42,281,Float64,257
60,박물관,VIEWNG_NMPR_CO,41,4.57,856,Float64,770

In [242]:
# 통합 데이터에서 결측률이 높은 컬럼 확인
# 이후 결측치 처리 또는 분석 제외 여부 판단에 활용한다.

print("[통합 데이터 결측률 30% 이상 컬럼]")
display(
    facility_missing[
        facility_missing["missing_rate"] >= 30
    ].sort_values("missing_rate", ascending=False)
)

print("[시설 유형별 결측률 30% 이상 컬럼]")
display(
    facility_missing_by_type[
        facility_missing_by_type["missing_rate"] >= 30
    ].sort_values(
        by=["missing_rate", "facility_type"],
        ascending=[False, True]
    )
)

[통합 데이터 결측률 30% 이상 컬럼]

,column,missing_count,missing_rate,non_missing_count,dtype,unique_count
0,PRVATE_VLNTER_CO,1074,90.18,117,Float64,32
1,CNTRCT_EMP_CO,1019,85.56,172,Float64,12
2,PUBLIC_VLNTER_CO,1008,84.63,183,Float64,80
3,PRFSN_CO,983,82.54,208,Float64,14
4,GNRL_GVRNM_EMP_CO,901,75.65,290,Float64,30
5,QUALF_HOLD_CO,755,63.39,436,Float64,17
6,ARTGR_EMP_CO,648,54.41,543,Float64,37
7,NMPR_CO,541,45.42,650,Float64,68
8,DATA_CO,528,44.33,663,Float64,405
9,DATA_SPCE_AR_VALUE,510,42.82,681,Float64,267

[시설 유형별 결측률 30% 이상 컬럼]

,facility_type,column,missing_count,missing_rate,non_missing_count,dtype,unique_count
57,박물관,PRVATE_VLNTER_CO,811,90.41,86,Float64,26
24,미술관,PRVATE_VLNTER_CO,263,89.46,31,Float64,13
19,미술관,GNRL_GVRNM_EMP_CO,254,86.39,40,Float64,16
21,미술관,PUBLIC_VLNTER_CO,254,86.39,40,Float64,29
53,박물관,CNTRCT_EMP_CO,771,85.95,126,Float64,11
56,박물관,PRFSN_CO,761,84.84,136,Float64,14
20,미술관,CNTRCT_EMP_CO,248,84.35,46,Float64,9
51,박물관,QUALF_HOLD_CO,755,84.17,142,Float64,11
54,박물관,PUBLIC_VLNTER_CO,754,84.06,143,Float64,70
23,미술관,PRFSN_CO,222,75.51,72,Float64,5
52,박물관,GNRL_GVRNM_EMP_CO,647,72.13,250,Float64,27
55,박물관,ARTGR_EMP_CO,564,62.88,333,Float64,14
50,박물관,NMPR_CO,541,60.31,356,Float64,29
25,미술관,DATA_CO,134,45.58,160,Float64,103
58,박물관,DATA_CO,394,43.92,503,Float64,338
49,박물관,DATA_SPCE_AR_VALUE,392,43.70,505,Float64,243
16,미술관,DATA_SPCE_AR_VALUE,118,40.14,176,Float64,100
15,미술관,EDC_FCLTY_AR_VALUE,89,30.27,205,Float64,144

### 05. 박물관/미술관 데이터 통합 결과

#### 1) 데이터 통합 결과

- 박물관 통합 기준 데이터와 미술관 통합 기준 데이터를 행 기준으로 결합하였다.
- 통합 데이터셋 이름은 `facility_common`으로 설정하였다.
- 통합 데이터 크기는 `(1191, 34)`이다.
  - 박물관: 897개
  - 미술관: 294개

#### 2) 통합 후 기본 검증

- 통합 전 박물관과 미술관의 행 수 합계는 1191개이다.
- 통합 후 전체 행 수 역시 1191개로 일치한다.
- 통합 후 컬럼 수는 34개이다.
- `ID` 결측치는 0개이다.
- `ID` 중복값은 0개이다.
- 시설명 결측치는 0개이다.
- `facility_type` 값은 `"박물관"`, `"미술관"`으로 정상 구분되어 있다.

#### 3) 통합 데이터 결측치 구조

- 통합 데이터에서 결측률이 높은 컬럼은 주로 인력 관련 컬럼이다.
- `PRVATE_VLNTER_CO`, `CNTRCT_EMP_CO`, `PUBLIC_VLNTER_CO`, `PRFSN_CO`, `GNRL_GVRNM_EMP_CO` 등은 결측률이 매우 높다.
- `NMPR_CO`, `DATA_CO`, `DATA_SPCE_AR_VALUE`도 결측률이 40% 이상으로 나타났다.
- 반면 관람객 수 관련 컬럼인 `VIEWNG_NMPR_CO`, `DAY_AVRG_VIEWNG_NMPR_CO`의 결측률은 약 4.53%로 비교적 낮다.

#### 4) 주의 사항

- 결측률이 높은 인력 관련 컬럼은 단순히 평균이나 중앙값으로 대체하기보다, 실제 미제출인지 또는 해당 없음인지 의미를 검토할 필요가 있다.
- 현재 단계에서는 결측치를 대체하거나 제거하지 않았다.
- 다음 단계에서는 숫자형 컬럼을 중심으로 이상치 구조를 확인한다.
- `DAY_AVRG_VIEWNG_NMPR_CO`는 이후 관람객 수 예측 모델에서 데이터 누수 가능성이 있으므로 입력 변수 사용에 주의한다.

#### 06. 이상치 확인

In [243]:
# 06.1 이상치 확인 대상 숫자형 컬럼 정리
# 통합 데이터에서 숫자형 컬럼만 추출한다.
# 아직 이상치를 제거하지 않고, 분포와 극단값을 확인하는 단계이다.

numeric_cols_for_outlier = facility_common.select_dtypes(include=["number"]).columns.tolist()

print("이상치 확인 대상 숫자형 컬럼 수:", len(numeric_cols_for_outlier))
print(numeric_cols_for_outlier)

# 관람객 수 예측 모델에서 주의해야 할 컬럼 따로 표시
leakage_attention_cols = [
    col for col in ["DAY_AVRG_VIEWNG_NMPR_CO"]
    if col in numeric_cols_for_outlier
]

print("\n[데이터 누수 주의 컬럼]")
print(leakage_attention_cols)

이상치 확인 대상 숫자형 컬럼 수: 18
['FCLTY_LO', 'FCLTY_LA', 'OPNNG_DAY_CO', 'LND_AR_VALUE', 'EDC_FCLTY_AR_VALUE', 'DATA_SPCE_AR_VALUE', 'NMPR_CO', 'QUALF_HOLD_CO', 'GNRL_GVRNM_EMP_CO', 'CNTRCT_EMP_CO', 'PUBLIC_VLNTER_CO', 'ARTGR_EMP_CO', 'PRFSN_CO', 'PRVATE_VLNTER_CO', 'DATA_CO', 'TOT_PROGRM_CO', 'VIEWNG_NMPR_CO', 'DAY_AVRG_VIEWNG_NMPR_CO']

[데이터 누수 주의 컬럼]
['DAY_AVRG_VIEWNG_NMPR_CO']

In [244]:
# 숫자형 컬럼의 기초 통계 확인
# count, mean, std, min, quartile, max를 통해 극단값 가능성을 1차 확인한다.

numeric_describe = facility_common[numeric_cols_for_outlier].describe().T

display(numeric_describe)

,count,mean,std,min,25%,50%,75%,max
FCLTY_LO,1191.0,127.463743,0.850809,125.427618,126.889709,127.115518,128.134943,130.90088
FCLTY_LA,1191.0,36.365302,1.311086,33.239977,35.274295,36.681267,37.524225,38.584138
OPNNG_DAY_CO,1150.0,283.038261,67.047872,0.0,253.25,306.0,312.0,365.0
LND_AR_VALUE,1177.0,37193.332408,200380.019432,3.853,1625.6,5634.0,17179.0,3872931.0
EDC_FCLTY_AR_VALUE,860.0,251.253988,413.883529,1.0,75.0,141.08,272.3925,5641.0
DATA_SPCE_AR_VALUE,681.0,105.470511,254.986676,2.6,26.0,50.0,100.0,5321.0
NMPR_CO,650.0,22.723077,107.551114,0.0,2.0,4.0,10.0,1852.0
QUALF_HOLD_CO,436.0,1.788991,6.560521,0.0,0.0,0.0,1.0,63.0
GNRL_GVRNM_EMP_CO,290.0,7.037931,12.162763,1.0,2.0,3.0,8.0,128.0
CNTRCT_EMP_CO,172.0,5.773256,19.106069,1.0,1.0,2.0,4.0,128.0
PUBLIC_VLNTER_CO,183.0,144.896175,437.051717,1.0,6.5,18.0,55.0,3499.0
ARTGR_EMP_CO,543.0,7.186004,43.744314,0.0,1.0,2.0,4.0,926.0
PRFSN_CO,208.0,2.365385,5.220838,1.0,1.0,1.0,2.0,58.0
PRVATE_VLNTER_CO,117.0,25.692308,92.833691,1.0,2.0,3.0,15.0,920.0
DATA_CO,663.0,7599.280543,15534.218106,10.0,600.0,2000.0,7901.0,157323.0
TOT_PROGRM_CO,907.0,9.818082,12.30925,0.0,3.0,6.0,12.0,122.0
VIEWNG_NMPR_CO,1137.0,80313.941953,233939.802099,68.0,5167.0,20000.0,64484.0,4180285.0
DAY_AVRG_VIEWNG_NMPR_CO,1137.0,260.049676,714.549718,0.4,19.0,69.0,216.0,11612.0

In [245]:
# 숫자형 컬럼별 결측치, 0 값, 음수 값 확인
# 면적, 인원, 프로그램 수, 관람객 수 등은 일반적으로 음수가 나오면 이상값 가능성이 높다.

numeric_value_check_rows = []

for col in numeric_cols_for_outlier:
    s = facility_common[col]
    
    numeric_value_check_rows.append({
        "column": col,
        "missing_count": s.isna().sum(),
        "missing_rate": round(s.isna().mean() * 100, 2),
        "zero_count": (s == 0).sum(),
        "zero_rate": round((s == 0).mean() * 100, 2),
        "negative_count": (s < 0).sum(),
        "min": s.min(),
        "max": s.max()
    })

numeric_value_check = pd.DataFrame(numeric_value_check_rows)

display(
    numeric_value_check.sort_values(
        by=["negative_count", "zero_rate", "missing_rate"],
        ascending=[False, False, False]
    )
)

,column,missing_count,missing_rate,zero_count,zero_rate,negative_count,min,max
7,QUALF_HOLD_CO,755,63.39,240,55.05,0,0.000000,6.300000e+01
11,ARTGR_EMP_CO,648,54.41,16,2.95,0,0.000000,9.260000e+02
6,NMPR_CO,541,45.42,13,2.00,0,0.000000,1.852000e+03
2,OPNNG_DAY_CO,41,3.44,12,1.04,0,0.000000,3.650000e+02
15,TOT_PROGRM_CO,284,23.85,1,0.11,0,0.000000,1.220000e+02
13,PRVATE_VLNTER_CO,1074,90.18,0,0.00,0,1.000000,9.200000e+02
9,CNTRCT_EMP_CO,1019,85.56,0,0.00,0,1.000000,1.280000e+02
10,PUBLIC_VLNTER_CO,1008,84.63,0,0.00,0,1.000000,3.499000e+03
12,PRFSN_CO,983,82.54,0,0.00,0,1.000000,5.800000e+01
8,GNRL_GVRNM_EMP_CO,901,75.65,0,0.00,0,1.000000,1.280000e+02
14,DATA_CO,528,44.33,0,0.00,0,10.000000,1.573230e+05
5,DATA_SPCE_AR_VALUE,510,42.82,0,0.00,0,2.600000,5.321000e+03
4,EDC_FCLTY_AR_VALUE,331,27.79,0,0.00,0,1.000000,5.641000e+03
16,VIEWNG_NMPR_CO,54,4.53,0,0.00,0,68.000000,4.180285e+06
17,DAY_AVRG_VIEWNG_NMPR_CO,54,4.53,0,0.00,0,0.400000,1.161200e+04
3,LND_AR_VALUE,14,1.18,0,0.00,0,3.853000,3.872931e+06
0,FCLTY_LO,0,0.00,0,0.00,0,125.427618,1.309009e+02
1,FCLTY_LA,0,0.00,0,0.00,0,33.239977,3.858414e+01

- 음수 값 → 없음
- 좌표값 → 범위상 큰 문제 없어 보임
- 0 값 → 일부 컬럼에서 확인 필요
- 극단적으로 큰 값 → 면적, 인력, 자료 수, 관람객 수에서 확인 필요

In [246]:
# 06.2 좌표 컬럼 범위 검증
# 시설 위치 좌표가 국내 시설 범위에서 크게 벗어나는지 확인한다.
# 일반적으로 한국 경도는 약 124~132, 위도는 약 33~39 범위로 볼 수 있다.

coordinate_check = pd.DataFrame([
    {
        "column": "FCLTY_LO",
        "expected_range": "124 ~ 132",
        "min": facility_common["FCLTY_LO"].min(),
        "max": facility_common["FCLTY_LO"].max(),
        "out_of_range_count": (
            (facility_common["FCLTY_LO"] < 124) |
            (facility_common["FCLTY_LO"] > 132)
        ).sum()
    },
    {
        "column": "FCLTY_LA",
        "expected_range": "33 ~ 39",
        "min": facility_common["FCLTY_LA"].min(),
        "max": facility_common["FCLTY_LA"].max(),
        "out_of_range_count": (
            (facility_common["FCLTY_LA"] < 33) |
            (facility_common["FCLTY_LA"] > 39)
        ).sum()
    }
])

display(coordinate_check)

     column expected_range         min         max  out_of_range_count
0  FCLTY_LO      124 ~ 132  125.427618  130.900880                   0
1  FCLTY_LA        33 ~ 39   33.239977   38.584138                   0

In [247]:
# 06.3 0 값 확인
# 0이 실제 의미 있는 값인지, 입력 오류인지 판단하기 위해 주요 컬럼의 0 값 행을 확인한다.

zero_check_cols = [
    "OPNNG_DAY_CO",
    "NMPR_CO",
    "QUALF_HOLD_CO",
    "ARTGR_EMP_CO",
    "TOT_PROGRM_CO"
]

zero_check_cols = [
    col for col in zero_check_cols
    if col in facility_common.columns
]

for col in zero_check_cols:
    zero_rows = facility_common[
        facility_common[col] == 0
    ][[
        "facility_type", "ID", "FCLTY_NM", "CTPRVN_NM", "SIGNGU_NM", col
    ]]
    
    print(f"[{col}] 0 값 행 수:", len(zero_rows))
    display(zero_rows.head(20))

[OPNNG_DAY_CO] 0 값 행 수: 12

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,OPNNG_DAY_CO
917,미술관,KCDMART25N000000021,상원미술관(휴관),서울,종로구,0.0
941,미술관,KCDMART25N000000045,이영미술관(휴관),서울,성북구,0.0
950,미술관,KCDMART25N000000054,한광미술관(휴관),부산,중구,0.0
983,미술관,KCDMART25N000000087,남철미술관(휴관),대전,서구,0.0
985,미술관,KCDMART25N000000089,여진불교미술관(휴관),대전,유성구,0.0
1025,미술관,KCDMART25N000000129,엠엠아트센터(휴관),경기,평택시,0.0
1056,미술관,KCDMART25N000000160,오랜미래신화미술관(휴관),강원,원주시,0.0
1059,미술관,KCDMART25N000000163,일현미술관(휴관),강원,양양군,0.0
1102,미술관,KCDMART25N000000206,장수미술관(폐관),전북,장수군,0.0
1112,미술관,KCDMART25N000000216,아산조방원미술관(휴관),전남,곡성군,0.0
1140,미술관,KCDMART25N000000244,장전미술관(휴관),전남,진도군,0.0
1186,미술관,KCDMART25N000000290,제주유리의성(휴관),제주,제주시,0.0

[NMPR_CO] 0 값 행 수: 13

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,NMPR_CO
950,미술관,KCDMART25N000000054,한광미술관(휴관),부산,중구,0.0
983,미술관,KCDMART25N000000087,남철미술관(휴관),대전,서구,0.0
985,미술관,KCDMART25N000000089,여진불교미술관(휴관),대전,유성구,0.0
1025,미술관,KCDMART25N000000129,엠엠아트센터(휴관),경기,평택시,0.0
1057,미술관,KCDMART25N000000161,월산미술관,강원,동해시,0.0
1069,미술관,KCDMART25N000000173,성마루미술관,충북,충주시,0.0
1080,미술관,KCDMART25N000000184,서해미술관,충남,서산시,0.0
1112,미술관,KCDMART25N000000216,아산조방원미술관(휴관),전남,곡성군,0.0
1129,미술관,KCDMART25N000000233,섬in섬 연홍미술관,전남,고흥군,0.0
1140,미술관,KCDMART25N000000244,장전미술관(휴관),전남,진도군,0.0
1146,미술관,KCDMART25N000000250,회정미술관,전남,고흥군,0.0
1151,미술관,KCDMART25N000000255,김천시립미술관,경북,김천시,0.0
1157,미술관,KCDMART25N000000261,향암미술관,경북,울진군,0.0

[QUALF_HOLD_CO] 0 값 행 수: 240

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,QUALF_HOLD_CO
901,미술관,KCDMART25N000000005,DDP디자인뮤지엄,서울,중구,0.0
902,미술관,KCDMART25N000000006,겸재정선미술관,서울,강서구,0.0
905,미술관,KCDMART25N000000009,종로구립 박노수미술관,서울,종로구,0.0
906,미술관,KCDMART25N000000010,JCC아트센터,서울,종로구,0.0
907,미술관,KCDMART25N000000011,K현대미술관,서울,강남구,0.0
908,미술관,KCDMART25N000000012,OCI미술관,서울,종로구,0.0
909,미술관,KCDMART25N000000013,금호미술관,서울,종로구,0.0
910,미술관,KCDMART25N000000014,김세중미술관,서울,용산구,0.0
911,미술관,KCDMART25N000000015,대림미술관,서울,종로구,0.0
912,미술관,KCDMART25N000000016,디뮤지엄(대림미술관 분관),서울,성동구,0.0
913,미술관,KCDMART25N000000017,롯데뮤지엄,서울,송파구,0.0
914,미술관,KCDMART25N000000018,리움미술관,서울,용산구,0.0
915,미술관,KCDMART25N000000019,밀알미술관,서울,강남구,0.0
916,미술관,KCDMART25N000000020,사비나미술관,서울,은평구,0.0
917,미술관,KCDMART25N000000021,상원미술관(휴관),서울,종로구,0.0
918,미술관,KCDMART25N000000022,서울서예박물관,서울,서초구,0.0
919,미술관,KCDMART25N000000023,성곡미술관,서울,종로구,0.0
920,미술관,KCDMART25N000000024,세종문화회관 미술관,서울,종로구,0.0
921,미술관,KCDMART25N000000025,세화미술관,서울,종로구,0.0
922,미술관,KCDMART25N000000026,소마미술관,서울,송파구,0.0

[ARTGR_EMP_CO] 0 값 행 수: 16

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,ARTGR_EMP_CO
942,미술관,KCDMART25N000000046,서울과학기술대학교 미술관,서울,노원구,0.0
943,미술관,KCDMART25N000000047,서울대학교미술관,서울,관악구,0.0
950,미술관,KCDMART25N000000054,한광미술관(휴관),부산,중구,0.0
958,미술관,KCDMART25N000000062,경북대학교미술관,대구,북구,0.0
966,미술관,KCDMART25N000000070,경인교육대학교 미술관 지누지움,인천,계양구,0.0
983,미술관,KCDMART25N000000087,남철미술관(휴관),대전,서구,0.0
985,미술관,KCDMART25N000000089,여진불교미술관(휴관),대전,유성구,0.0
1025,미술관,KCDMART25N000000129,엠엠아트센터(휴관),경기,평택시,0.0
1057,미술관,KCDMART25N000000161,월산미술관,강원,동해시,0.0
1069,미술관,KCDMART25N000000173,성마루미술관,충북,충주시,0.0
1080,미술관,KCDMART25N000000184,서해미술관,충남,서산시,0.0
1106,미술관,KCDMART25N000000210,국립군산대학교미술관,전북,군산시,0.0
1129,미술관,KCDMART25N000000233,섬in섬 연홍미술관,전남,고흥군,0.0
1140,미술관,KCDMART25N000000244,장전미술관(휴관),전남,진도군,0.0
1146,미술관,KCDMART25N000000250,회정미술관,전남,고흥군,0.0
1157,미술관,KCDMART25N000000261,향암미술관,경북,울진군,0.0

[TOT_PROGRM_CO] 0 값 행 수: 1

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,TOT_PROGRM_CO
1147,미술관,KCDMART25N000000251,동암미술관,전남,화순군,0.0

In [248]:
# 06.4 IQR 기준 이상치 후보 요약
# 이상치를 제거하지 않고, 후보 개수와 비율만 확인한다.
# 좌표 컬럼은 별도 범위 검증을 했으므로 IQR 이상치 확인 대상에서 제외한다.

iqr_outlier_cols = [
    col for col in numeric_cols_for_outlier
    if col not in ["FCLTY_LO", "FCLTY_LA"]
]

def iqr_outlier_summary(df, cols):
    rows = []
    
    for col in cols:
        s = df[col].dropna()
        
        if len(s) == 0:
            continue
        
        q1 = s.quantile(0.25)
        q3 = s.quantile(0.75)
        iqr = q3 - q1
        
        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr
        
        outlier_mask = (df[col] < lower_bound) | (df[col] > upper_bound)
        outlier_count = outlier_mask.sum()
        non_missing_count = df[col].notna().sum()
        
        rows.append({
            "column": col,
            "non_missing_count": non_missing_count,
            "q1": q1,
            "median": s.median(),
            "q3": q3,
            "iqr": iqr,
            "lower_bound": lower_bound,
            "upper_bound": upper_bound,
            "min": s.min(),
            "max": s.max(),
            "outlier_count": outlier_count,
            "outlier_rate": round(outlier_count / non_missing_count * 100, 2)
        })
    
    return pd.DataFrame(rows).sort_values(
        by="outlier_rate",
        ascending=False
    )


iqr_outlier_result = iqr_outlier_summary(
    facility_common,
    iqr_outlier_cols
)

display(iqr_outlier_result)

,column,non_missing_count,q1,median,q3,iqr,lower_bound,upper_bound,min,max,outlier_count,outlier_rate
8,PUBLIC_VLNTER_CO,183,6.50,18.00,55.0000,48.5000,-66.25000,127.75000,1.000,3499.0,33,18.03
11,PRVATE_VLNTER_CO,117,2.00,3.00,15.0000,13.0000,-17.50000,34.50000,1.000,920.0,18,15.38
5,QUALF_HOLD_CO,436,0.00,0.00,1.0000,1.0000,-1.50000,2.50000,0.000,63.0,61,13.99
1,LND_AR_VALUE,1177,1625.60,5634.00,17179.0000,15553.4000,-21704.50000,40509.10000,3.853,3872931.0,161,13.68
15,DAY_AVRG_VIEWNG_NMPR_CO,1137,19.00,69.00,216.0000,197.0000,-276.50000,511.50000,0.400,11612.0,141,12.40
14,VIEWNG_NMPR_CO,1137,5167.00,20000.00,64484.0000,59317.0000,-83808.50000,153459.50000,68.000,4180285.0,139,12.23
12,DATA_CO,663,600.00,2000.00,7901.0000,7301.0000,-10351.50000,18852.50000,10.000,157323.0,72,10.86
4,NMPR_CO,650,2.00,4.00,10.0000,8.0000,-10.00000,22.00000,0.000,1852.0,70,10.77
3,DATA_SPCE_AR_VALUE,681,26.00,50.00,100.0000,74.0000,-85.00000,211.00000,2.600,5321.0,72,10.57
9,ARTGR_EMP_CO,543,1.00,2.00,4.0000,3.0000,-3.50000,8.50000,0.000,926.0,53,9.76
10,PRFSN_CO,208,1.00,1.00,2.0000,1.0000,-0.50000,3.50000,1.000,58.0,19,9.13
2,EDC_FCLTY_AR_VALUE,860,75.00,141.08,272.3925,197.3925,-221.08875,568.48125,1.000,5641.0,71,8.26
6,GNRL_GVRNM_EMP_CO,290,2.00,3.00,8.0000,6.0000,-7.00000,17.00000,1.000,128.0,21,7.24
7,CNTRCT_EMP_CO,172,1.00,2.00,4.0000,3.0000,-3.50000,8.50000,1.000,128.0,12,6.98
13,TOT_PROGRM_CO,907,3.00,6.00,12.0000,9.0000,-10.50000,25.50000,0.000,122.0,59,6.50
0,OPNNG_DAY_CO,1150,253.25,306.00,312.0000,58.7500,165.12500,400.12500,0.000,365.0,71,6.17

In [249]:
# 06.5 주요 이상치 후보 상세 확인
# IQR 기준 이상치 후보가 많은 컬럼 중 분석적으로 중요한 컬럼을 우선 확인한다.
# 여기서도 제거하지 않고, 어떤 시설이 극단값을 가지는지만 확인한다.

important_outlier_cols = [
    "LND_AR_VALUE",
    "EDC_FCLTY_AR_VALUE",
    "DATA_SPCE_AR_VALUE",
    "NMPR_CO",
    "PUBLIC_VLNTER_CO",
    "ARTGR_EMP_CO",
    "DATA_CO",
    "TOT_PROGRM_CO",
    "VIEWNG_NMPR_CO",
    "DAY_AVRG_VIEWNG_NMPR_CO"
]

important_outlier_cols = [
    col for col in important_outlier_cols
    if col in facility_common.columns
]

def show_top_values(df, col, n=10):
    check_cols = [
        "facility_type", "ID", "FCLTY_NM", "CTPRVN_NM", "SIGNGU_NM", col
    ]
    
    print(f"[{col}] 상위 {n}개 값")
    display(
        df[check_cols]
        .dropna(subset=[col])
        .sort_values(col, ascending=False)
        .head(n)
    )


for col in important_outlier_cols:
    show_top_values(facility_common, col, n=10)

[LND_AR_VALUE] 상위 10개 값

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,LND_AR_VALUE
562,박물관,KCDMMUS23N000000563,독립기념관,충남,천안시 동남구,3872931.0
15,박물관,KCDMMUS23N000000016,국립항공박물관,서울,강서구,3425949.9
844,박물관,KCDMMUS23N000000845,제주돌문화공원,제주특별자치도,제주시,3230000.0
624,박물관,KCDMMUS23N000000625,전북대학교박물관,전북특별자치도,전주시 덕진구,1320267.0
1042,미술관,KCDMART25N000000146,DIMA 아트센터,경기,안성시,1138050.0
851,박물관,KCDMMUS23N000000852,항몽유적지,제주특별자치도,제주시,1100559.0
373,박물관,KCDMMUS23N000000374,경희대학교 혜정박물관,경기,용인시 기흥구,1010005.0
519,박물관,KCDMMUS23N000000520,한국교원대학교 교육박물관,충북,청주시 흥덕구,784760.0
665,박물관,KCDMMUS23N000000666,해남공룡박물관,전남,해남군,748243.0
922,미술관,KCDMART25N000000026,소마미술관,서울,송파구,692367.0

[EDC_FCLTY_AR_VALUE] 상위 10개 값

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,EDC_FCLTY_AR_VALUE
898,미술관,KCDMART25N000000002,국립현대미술관(서울관),서울,종로구,5641.0
0,박물관,KCDMMUS23N000000001,국립중앙박물관,서울,용산구,4975.0
787,박물관,KCDMMUS23N000000788,산청한의학박물관,경남,산청군,3595.0
708,박물관,KCDMMUS23N000000709,삼성현역사문화관,경북,경산시,3595.0
285,박물관,KCDMMUS23N000000286,수원화성박물관,경기,수원시 팔달구,2959.0
557,박물관,KCDMMUS23N000000558,LX국토정보박물관,충남,공주시,2949.0
215,박물관,KCDMMUS23N000000216,국립광주박물관,광주,북구,1965.0
562,박물관,KCDMMUS23N000000563,독립기념관,충남,천안시 동남구,1876.0
752,박물관,KCDMMUS23N000000753,경북과학대학교박물관,경북,칠곡군,1800.0
901,미술관,KCDMART25N000000005,DDP디자인뮤지엄,서울,중구,1789.0

[DATA_SPCE_AR_VALUE] 상위 10개 값

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,DATA_SPCE_AR_VALUE
572,박물관,KCDMMUS23N000000573,한국도량형박물관,충남,당진시,5321.0
0,박물관,KCDMMUS23N000000001,국립중앙박물관,서울,용산구,1552.0
787,박물관,KCDMMUS23N000000788,산청한의학박물관,경남,산청군,1552.0
134,박물관,KCDMMUS23N000000135,국립해양박물관,부산,영도구,1459.0
82,박물관,KCDMMUS23N000000083,전쟁기념관,서울,용산구,1273.0
151,박물관,KCDMMUS23N000000152,오륜대한국순교자박물관(휴관),부산,금정구,1000.0
1068,미술관,KCDMART25N000000172,청주시한국공예관,충북,청주시,981.0
309,박물관,KCDMMUS23N000000310,한국만화박물관,경기,부천시 원미구,816.0
898,미술관,KCDMART25N000000002,국립현대미술관(서울관),서울,종로구,710.0
14,박물관,KCDMMUS23N000000015,한국영화박물관,서울,마포구,672.0

[NMPR_CO] 상위 10개 값

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,NMPR_CO
965,미술관,KCDMART25N000000069,경원미술관,인천,연수구,1852.0
991,미술관,KCDMART25N000000095,김홍도미술관,경기,안산시,1048.0
994,미술관,KCDMART25N000000098,수원시립미술관,경기,수원시,862.0
1115,미술관,KCDMART25N000000219,전남도립미술관,전남,광양시,727.0
1093,미술관,KCDMART25N000000197,W미술관,전북,익산시,560.0
1005,미술관,KCDMART25N000000109,근현대사미술관담다,경기,용인시,508.0
988,미술관,KCDMART25N000000092,경기도자미술관,경기,이천시,453.0
900,미술관,KCDMART25N000000004,국립현대미술관 미술품수장센터(청주관),충북,청주시,373.0
897,미술관,KCDMART25N000000001,국립현대미술관(과천관),경기,과천시,368.0
898,미술관,KCDMART25N000000002,국립현대미술관(서울관),서울,종로구,368.0

[PUBLIC_VLNTER_CO] 상위 10개 값

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,PUBLIC_VLNTER_CO
270,박물관,KCDMMUS23N000000271,고양어린이박물관,경기,고양시 덕양구,3499.0
15,박물관,KCDMMUS23N000000016,국립항공박물관,서울,강서구,2550.0
17,박물관,KCDMMUS23N000000018,둘리뮤지엄,서울,도봉구,2518.0
133,박물관,KCDMMUS23N000000134,국립일제강제동원역사관,부산,남구,2341.0
602,박물관,KCDMMUS23N000000603,부안청자박물관,전북특별자치도,부안군,1450.0
991,미술관,KCDMART25N000000095,김홍도미술관,경기,안산시,1038.0
248,박물관,KCDMMUS23N000000249,울산옹기박물관,울산,울주군,875.0
994,미술관,KCDMART25N000000098,수원시립미술관,경기,수원시,831.0
1115,미술관,KCDMART25N000000219,전남도립미술관,전남,광양시,700.0
6,박물관,KCDMMUS23N000000007,국립극장 공연예술박물관,서울,중구,619.0

[ARTGR_EMP_CO] 상위 10개 값

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,ARTGR_EMP_CO
965,미술관,KCDMART25N000000069,경원미술관,인천,연수구,926.0
1093,미술관,KCDMART25N000000197,W미술관,전북,익산시,280.0
1005,미술관,KCDMART25N000000109,근현대사미술관담다,경기,용인시,254.0
914,미술관,KCDMART25N000000018,리움미술관,서울,용산구,145.0
922,미술관,KCDMART25N000000026,소마미술관,서울,송파구,108.0
957,미술관,KCDMART25N000000061,권정호미술관,대구,동구,88.0
82,박물관,KCDMMUS23N000000083,전쟁기념관,서울,용산구,52.0
1053,미술관,KCDMART25N000000157,뮤지엄 산(청조갤러리),강원,원주시,51.0
925,미술관,KCDMART25N000000029,아모레퍼시픽미술관,서울,용산구,41.0
562,박물관,KCDMMUS23N000000563,독립기념관,충남,천안시 동남구,38.0

[DATA_CO] 상위 10개 값

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,DATA_CO
0,박물관,KCDMMUS23N000000001,국립중앙박물관,서울,용산구,157323.0
572,박물관,KCDMMUS23N000000573,한국도량형박물관,충남,당진시,154616.0
562,박물관,KCDMMUS23N000000563,독립기념관,충남,천안시 동남구,103000.0
362,박물관,KCDMMUS23N000000363,한국기독교역사박물관,경기,이천시,98049.0
1,박물관,KCDMMUS23N000000002,국립민속박물관,서울,종로구,92786.0
5,박물관,KCDMMUS23N000000006,국립국악원 국악박물관,서울,서초구,84732.0
633,박물관,KCDMMUS23N000000634,고흥분청문화박물관,전남,고흥군,80000.0
691,박물관,KCDMMUS23N000000692,국립경주박물관,경북,경주시,75199.0
897,미술관,KCDMART25N000000001,국립현대미술관(과천관),경기,과천시,69358.0
216,박물관,KCDMMUS23N000000217,아시아문화박물관,광주,동구,69000.0

[TOT_PROGRM_CO] 상위 10개 값

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,TOT_PROGRM_CO
101,박물관,KCDMMUS23N000000102,혜곡최순우기념관,서울,성북구,122.0
364,박물관,KCDMMUS23N000000365,한국민속촌 박물관,경기,용인시 기흥구,114.0
23,박물관,KCDMMUS23N000000024,서울상상나라,서울,광진구,101.0
828,박물관,KCDMMUS23N000000829,해금강테마박물관,경남,거제시,100.0
898,미술관,KCDMART25N000000002,국립현대미술관(서울관),서울,종로구,88.0
927,미술관,KCDMART25N000000031,아트센터나비미술관,서울,종로구,86.0
884,박물관,KCDMMUS23N000000885,제주항공우주박물관,제주특별자치도,서귀포시,79.0
1,박물관,KCDMMUS23N000000002,국립민속박물관,서울,종로구,70.0
270,박물관,KCDMMUS23N000000271,고양어린이박물관,경기,고양시 덕양구,70.0
107,박물관,KCDMMUS23N000000108,건국대학교 박물관,서울,광진구,68.0

[VIEWNG_NMPR_CO] 상위 10개 값

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,VIEWNG_NMPR_CO
0,박물관,KCDMMUS23N000000001,국립중앙박물관,서울,용산구,4180285.0
534,박물관,KCDMMUS23N000000535,백제군사박물관,충남,논산시,2917684.0
82,박물관,KCDMMUS23N000000083,전쟁기념관,서울,용산구,2863317.0
903,미술관,KCDMART25N000000007,서울시립미술관,서울,중구,1918799.0
898,미술관,KCDMART25N000000002,국립현대미술관(서울관),서울,종로구,1655834.0
562,박물관,KCDMMUS23N000000563,독립기념관,충남,천안시 동남구,1601941.0
691,박물관,KCDMMUS23N000000692,국립경주박물관,경북,경주시,1340032.0
13,박물관,KCDMMUS23N000000014,석조전 대한제국역사관,서울,중구,1335076.0
1,박물관,KCDMMUS23N000000002,국립민속박물관,서울,종로구,1307690.0
889,박물관,KCDMMUS23N000000890,카멜리아힐,제주특별자치도,서귀포시,1020700.0

[DAY_AVRG_VIEWNG_NMPR_CO] 상위 10개 값

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,DAY_AVRG_VIEWNG_NMPR_CO
0,박물관,KCDMMUS23N000000001,국립중앙박물관,서울,용산구,11612.0
534,박물관,KCDMMUS23N000000535,백제군사박물관,충남,논산시,9412.0
82,박물관,KCDMMUS23N000000083,전쟁기념관,서울,용산구,9177.0
903,미술관,KCDMART25N000000007,서울시립미술관,서울,중구,5959.0
562,박물관,KCDMMUS23N000000563,독립기념관,충남,천안시 동남구,5038.0
898,미술관,KCDMART25N000000002,국립현대미술관(서울관),서울,종로구,4574.0
13,박물관,KCDMMUS23N000000014,석조전 대한제국역사관,서울,중구,4265.0
185,박물관,KCDMMUS23N000000186,국립세계문자박물관,인천,연수구,3770.0
691,박물관,KCDMMUS23N000000692,국립경주박물관,경북,경주시,3702.0
1,박물관,KCDMMUS23N000000002,국립민속박물관,서울,종로구,3612.0

좌표 범위:
- FCLTY_LO: 125.43 ~ 130.90
- FCLTY_LA: 33.24 ~ 38.58
- 국내 범위를 벗어나는 좌표 없음

0 값:
- OPNNG_DAY_CO 0값 12개 → 대부분 시설명에 휴관/폐관 포함
- NMPR_CO 0값 13개 → 일부 휴관 시설 + 일부 일반 시설
- QUALF_HOLD_CO 0값 240개 → 자격 보유 인력 없음으로 해석 가능
- ARTGR_EMP_CO 0값 16개 → 미술관 중심
- TOT_PROGRM_CO 0값 1개

IQR 이상치:
- PUBLIC_VLNTER_CO, PRVATE_VLNTER_CO, QUALF_HOLD_CO, LND_AR_VALUE, VIEWNG_NMPR_CO 등에서 이상치 후보가 많음
- 하지만 대부분 규모가 큰 정상 시설일 가능성이 높음
- 따라서 현재 단계에서는 제거하지 않고, 이상치 플래그만 만드는 방향이 적절함

In [250]:
# 06.6 이상치 처리 방향 1차 정리
# 현재 단계에서는 이상치를 제거하지 않고, 처리 방향만 정리한다.

outlier_decision_summary = pd.DataFrame([
    {
        "category": "좌표",
        "columns": "FCLTY_LO, FCLTY_LA",
        "finding": "국내 시설 좌표 범위에서 벗어나는 값 없음",
        "decision": "유지"
    },
    {
        "category": "0 값",
        "columns": "OPNNG_DAY_CO",
        "finding": "0 값은 대부분 휴관/폐관 시설에서 발생",
        "decision": "유지하되, 운영일수 분석 시 별도 확인"
    },
    {
        "category": "0 값",
        "columns": "NMPR_CO, QUALF_HOLD_CO, ARTGR_EMP_CO, TOT_PROGRM_CO",
        "finding": "0 값이 존재하지만 실제 0명/0개일 가능성이 있음",
        "decision": "현재 단계에서는 유지"
    },
    {
        "category": "IQR 이상치",
        "columns": "LND_AR_VALUE, DATA_CO, VIEWNG_NMPR_CO 등",
        "finding": "규모가 큰 시설에서 큰 값이 관측됨",
        "decision": "제거하지 않고 플래그 생성"
    },
    {
        "category": "모델링 주의",
        "columns": "DAY_AVRG_VIEWNG_NMPR_CO",
        "finding": "관람객 수와 직접적으로 연결되는 파생 성과 변수",
        "decision": "EDA에서는 참고 가능하나, 관람객 수 예측 모델 입력 변수 사용 주의"
    }
])

display(outlier_decision_summary)

,category,columns,finding,decision
0,좌표,"FCLTY_LO, FCLTY_LA",국내 시설 좌표 범위에서 벗어나는 값 없음,유지
1,0 값,OPNNG_DAY_CO,0 값은 대부분 휴관/폐관 시설에서 발생,"유지하되, 운영일수 분석 시 별도 확인"
2,0 값,"NMPR_CO, QUALF_HOLD_CO, ARTGR_EMP_CO, TOT_PROG...",0 값이 존재하지만 실제 0명/0개일 가능성이 있음,현재 단계에서는 유지
3,IQR 이상치,"LND_AR_VALUE, DATA_CO, VIEWNG_NMPR_CO 등",규모가 큰 시설에서 큰 값이 관측됨,제거하지 않고 플래그 생성
4,모델링 주의,DAY_AVRG_VIEWNG_NMPR_CO,관람객 수와 직접적으로 연결되는 파생 성과 변수,"EDA에서는 참고 가능하나, 관람객 수 예측 모델 입력 변수 사용 주의"

In [251]:
# IQR 이상치 플래그 데이터 생성
# 원본 facility_common은 그대로 유지하고, 플래그가 추가된 별도 데이터셋을 생성한다.

facility_outlier_flagged = facility_common.copy()

outlier_flag_cols = []

for col in iqr_outlier_cols:
    s = facility_outlier_flagged[col].dropna()
    
    if len(s) == 0:
        continue
    
    q1 = s.quantile(0.25)
    q3 = s.quantile(0.75)
    iqr = q3 - q1
    
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    
    flag_col = f"{col}_IQR_OUTLIER"
    
    facility_outlier_flagged[flag_col] = (
        (facility_outlier_flagged[col] < lower_bound) |
        (facility_outlier_flagged[col] > upper_bound)
    )
    
    outlier_flag_cols.append(flag_col)

print("IQR 이상치 플래그 생성 완료")
print("생성된 플래그 컬럼 수:", len(outlier_flag_cols))
print(outlier_flag_cols)

IQR 이상치 플래그 생성 완료
생성된 플래그 컬럼 수: 16
['OPNNG_DAY_CO_IQR_OUTLIER', 'LND_AR_VALUE_IQR_OUTLIER', 'EDC_FCLTY_AR_VALUE_IQR_OUTLIER', 'DATA_SPCE_AR_VALUE_IQR_OUTLIER', 'NMPR_CO_IQR_OUTLIER', 'QUALF_HOLD_CO_IQR_OUTLIER', 'GNRL_GVRNM_EMP_CO_IQR_OUTLIER', 'CNTRCT_EMP_CO_IQR_OUTLIER', 'PUBLIC_VLNTER_CO_IQR_OUTLIER', 'ARTGR_EMP_CO_IQR_OUTLIER', 'PRFSN_CO_IQR_OUTLIER', 'PRVATE_VLNTER_CO_IQR_OUTLIER', 'DATA_CO_IQR_OUTLIER', 'TOT_PROGRM_CO_IQR_OUTLIER', 'VIEWNG_NMPR_CO_IQR_OUTLIER', 'DAY_AVRG_VIEWNG_NMPR_CO_IQR_OUTLIER']

In [252]:
# 이상치 플래그별 True 개수 확인

outlier_flag_summary = []

for flag_col in outlier_flag_cols:
    original_col = flag_col.replace("_IQR_OUTLIER", "")
    
    outlier_flag_summary.append({
        "column": original_col,
        "flag_column": flag_col,
        "outlier_count": facility_outlier_flagged[flag_col].sum(),
        "outlier_rate": round(facility_outlier_flagged[flag_col].mean() * 100, 2)
    })

outlier_flag_summary = pd.DataFrame(outlier_flag_summary).sort_values(
    "outlier_rate",
    ascending=False
)

display(outlier_flag_summary)

,column,flag_column,outlier_count,outlier_rate
8,PUBLIC_VLNTER_CO,PUBLIC_VLNTER_CO_IQR_OUTLIER,33,18.03
11,PRVATE_VLNTER_CO,PRVATE_VLNTER_CO_IQR_OUTLIER,18,15.38
5,QUALF_HOLD_CO,QUALF_HOLD_CO_IQR_OUTLIER,61,13.99
1,LND_AR_VALUE,LND_AR_VALUE_IQR_OUTLIER,161,13.68
15,DAY_AVRG_VIEWNG_NMPR_CO,DAY_AVRG_VIEWNG_NMPR_CO_IQR_OUTLIER,141,12.40
14,VIEWNG_NMPR_CO,VIEWNG_NMPR_CO_IQR_OUTLIER,139,12.23
12,DATA_CO,DATA_CO_IQR_OUTLIER,72,10.86
4,NMPR_CO,NMPR_CO_IQR_OUTLIER,70,10.77
3,DATA_SPCE_AR_VALUE,DATA_SPCE_AR_VALUE_IQR_OUTLIER,72,10.57
9,ARTGR_EMP_CO,ARTGR_EMP_CO_IQR_OUTLIER,53,9.76
10,PRFSN_CO,PRFSN_CO_IQR_OUTLIER,19,9.13
2,EDC_FCLTY_AR_VALUE,EDC_FCLTY_AR_VALUE_IQR_OUTLIER,71,8.26
6,GNRL_GVRNM_EMP_CO,GNRL_GVRNM_EMP_CO_IQR_OUTLIER,21,7.24
7,CNTRCT_EMP_CO,CNTRCT_EMP_CO_IQR_OUTLIER,12,6.98
13,TOT_PROGRM_CO,TOT_PROGRM_CO_IQR_OUTLIER,59,6.50
0,OPNNG_DAY_CO,OPNNG_DAY_CO_IQR_OUTLIER,71,6.17

In [253]:
# 시설별로 몇 개 컬럼에서 IQR 이상치 후보로 잡혔는지 확인한다.
# 여러 컬럼에서 동시에 이상치로 잡히는 시설은 대형 시설일 가능성이 높다.

facility_outlier_flagged["IQR_OUTLIER_FLAG_COUNT"] = (
    facility_outlier_flagged[outlier_flag_cols].sum(axis=1)
)

print("[시설별 IQR 이상치 플래그 개수 상위 20개]")
display(
    facility_outlier_flagged[
        [
            "facility_type", "ID", "FCLTY_NM", "CTPRVN_NM", "SIGNGU_NM",
            "IQR_OUTLIER_FLAG_COUNT"
        ]
    ]
    .sort_values("IQR_OUTLIER_FLAG_COUNT", ascending=False)
    .head(20)
)

print("[IQR 이상치 플래그 개수 분포]")
display(
    facility_outlier_flagged["IQR_OUTLIER_FLAG_COUNT"]
    .value_counts()
    .sort_index()
    .to_frame("facility_count")
)

[시설별 IQR 이상치 플래그 개수 상위 20개]

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,IQR_OUTLIER_FLAG_COUNT
897,미술관,KCDMART25N000000001,국립현대미술관(과천관),경기,과천시,11
0,박물관,KCDMMUS23N000000001,국립중앙박물관,서울,용산구,10
898,미술관,KCDMART25N000000002,국립현대미술관(서울관),서울,종로구,10
35,박물관,KCDMMUS23N000000036,한성백제박물관,서울,송파구,9
562,박물관,KCDMMUS23N000000563,독립기념관,충남,천안시 동남구,9
4,박물관,KCDMMUS23N000000005,국립한글박물관,서울,용산구,9
1,박물관,KCDMMUS23N000000002,국립민속박물관,서울,종로구,8
26,박물관,KCDMMUS23N000000027,서울역사박물관,서울,종로구,8
82,박물관,KCDMMUS23N000000083,전쟁기념관,서울,용산구,8
1040,미술관,KCDMART25N000000144,현대어린이책미술관 MOKA GARDEN,경기,남양주시,7
483,박물관,KCDMMUS23N000000484,국립청주박물관,충북,청주시 상당구,7
691,박물관,KCDMMUS23N000000692,국립경주박물관,경북,경주시,7
8,박물관,KCDMMUS23N000000009,국립고궁박물관,서울,종로구,7
215,박물관,KCDMMUS23N000000216,국립광주박물관,광주,북구,7
914,미술관,KCDMART25N000000018,리움미술관,서울,용산구,7
899,미술관,KCDMART25N000000003,국립현대미술관(덕수궁관),서울,중구,6
955,미술관,KCDMART25N000000059,대구미술관,대구,수성구,6
185,박물관,KCDMMUS23N000000186,국립세계문자박물관,인천,연수구,6
903,미술관,KCDMART25N000000007,서울시립미술관,서울,중구,6
967,미술관,KCDMART25N000000071,광주시립미술관,광주,북구,6

[IQR 이상치 플래그 개수 분포]

                        facility_count
IQR_OUTLIER_FLAG_COUNT
0                                  696
1                                  244
2                                  109
3                                   62
4                                   38
5                                   13
6                                   14
7                                    6
8                                    3
9                                    3
10                                   2
11                                   1

In [254]:
# 로그 변환 후보 컬럼 확인
# 오른쪽 꼬리가 긴 규모/관람객/자료 수 변수는 이후 EDA나 모델링에서 log1p 변환을 고려할 수 있다.

log_transform_candidate_cols = [
    "LND_AR_VALUE",
    "EDC_FCLTY_AR_VALUE",
    "DATA_SPCE_AR_VALUE",
    "NMPR_CO",
    "DATA_CO",
    "TOT_PROGRM_CO",
    "VIEWNG_NMPR_CO",
    "DAY_AVRG_VIEWNG_NMPR_CO"
]

log_transform_candidate_cols = [
    col for col in log_transform_candidate_cols
    if col in facility_common.columns
]

log_candidate_summary = []

for col in log_transform_candidate_cols:
    s = facility_common[col].dropna()
    
    log_candidate_summary.append({
        "column": col,
        "non_missing_count": s.count(),
        "min": s.min(),
        "median": s.median(),
        "max": s.max(),
        "skew": round(s.skew(), 3)
    })

log_candidate_summary = pd.DataFrame(log_candidate_summary).sort_values(
    "skew",
    ascending=False
)

display(log_candidate_summary)

,column,non_missing_count,min,median,max,skew
0,LND_AR_VALUE,1177,3.853,5634.00,3872931.0,14.390
2,DATA_SPCE_AR_VALUE,681,2.600,50.00,5321.0,13.838
3,NMPR_CO,650,0.000,4.00,1852.0,10.908
6,VIEWNG_NMPR_CO,1137,68.000,20000.00,4180285.0,9.619
7,DAY_AVRG_VIEWNG_NMPR_CO,1137,0.400,69.00,11612.0,8.931
1,EDC_FCLTY_AR_VALUE,860,1.000,141.08,5641.0,6.891
4,DATA_CO,663,10.000,2000.00,157323.0,4.811
5,TOT_PROGRM_CO,907,0.000,6.00,122.0,4.223

- 좌표 범위 이상 없음
- 음수 값 없음
- 0 값은 일부 존재하지만 대부분 의미 있는 0 또는 휴관/폐관 시설과 관련
- IQR 이상치 후보는 많지만, 대부분 대형 시설 특성으로 보여 삭제하면 왜곡 발생
  - 국립현대박물관, 국립중앙박물관, 국립현대미술관, 독립기념관 등
- 따라서 이상치는 제거하지 않고 플래그만 생성하는 방향이 적절
- 로그 변환 후보 컬럼도 확인 완료

### 06. 이상치 확인 결과

#### 1) 좌표값 확인

- 시설 위치 좌표인 `FCLTY_LO`, `FCLTY_LA`의 범위를 확인하였다.
- 경도 `FCLTY_LO`는 약 125.43 ~ 130.90 범위로 나타났다.
- 위도 `FCLTY_LA`는 약 33.24 ~ 38.58 범위로 나타났다.
- 국내 시설 좌표 범위를 크게 벗어나는 값은 확인되지 않았다.

#### 2) 음수 값 확인

- 숫자형 컬럼 전체에서 음수 값은 확인되지 않았다.
- 면적, 인력 수, 자료 수, 프로그램 수, 관람객 수 등에서 음수 값이 없으므로 기본적인 수치 입력 오류 가능성은 낮다.

#### 3) 0 값 확인

- `OPNNG_DAY_CO`에서 0 값이 12개 확인되었다.
- 해당 시설은 대부분 시설명에 휴관 또는 폐관 정보가 포함되어 있어, 단순 오류라기보다 운영 상태와 관련된 값으로 판단된다.
- `NMPR_CO`, `QUALF_HOLD_CO`, `ARTGR_EMP_CO`, `TOT_PROGRM_CO`에서도 0 값이 확인되었다.
- 이 값들은 실제 인력 없음 또는 프로그램 없음일 가능성이 있으므로 현재 단계에서는 제거하지 않는다.

#### 4) IQR 기준 이상치 확인

- IQR 기준으로 여러 숫자형 컬럼에서 이상치 후보가 확인되었다.
- 이상치 후보가 많은 컬럼은 `PUBLIC_VLNTER_CO`, `PRVATE_VLNTER_CO`, `QUALF_HOLD_CO`, `LND_AR_VALUE`, `VIEWNG_NMPR_CO`, `DAY_AVRG_VIEWNG_NMPR_CO`, `DATA_CO` 등이다.
- 그러나 상위 이상치 시설을 확인한 결과, 국립중앙박물관, 국립현대미술관, 독립기념관 등 대형 시설이 주로 포함되어 있었다.
- 따라서 해당 값들은 단순 오류라기보다 시설 규모 차이에서 발생한 정상적인 극단값일 가능성이 높다.

#### 5) 이상치 처리 방향

- 현재 단계에서는 이상치를 제거하지 않는다.
- 원본 통합 데이터인 `facility_common`은 그대로 유지한다.
- IQR 기준 이상치 여부를 나타내는 플래그 컬럼을 추가한 `facility_outlier_flagged` 데이터셋을 별도로 생성하였다.
- 시설별 이상치 플래그 개수인 `IQR_OUTLIER_FLAG_COUNT`를 생성하였다.
- 이후 EDA에서 대형 시설 여부를 해석하거나, 모델링 단계에서 이상치 영향도를 확인할 때 활용할 수 있다.

#### 6) 로그 변환 후보

- 오른쪽 꼬리가 긴 분포를 보이는 컬럼은 로그 변환 후보로 정리하였다.
- 로그 변환 후보 컬럼은 다음과 같다.
  - `LND_AR_VALUE`
  - `EDC_FCLTY_AR_VALUE`
  - `DATA_SPCE_AR_VALUE`
  - `NMPR_CO`
  - `DATA_CO`
  - `TOT_PROGRM_CO`
  - `VIEWNG_NMPR_CO`
  - `DAY_AVRG_VIEWNG_NMPR_CO`
- 단, `DAY_AVRG_VIEWNG_NMPR_CO`는 관람객 수 예측 모델에서 데이터 누수 가능성이 있으므로 입력 변수 사용에 주의한다.

#### 07. 파생변수 생성

In [255]:
# 07.1 파생변수 생성용 데이터 복사
# 이상치 플래그가 포함된 데이터를 기반으로 EDA용 파생변수를 생성한다.
# 원본 통합 데이터 facility_common은 그대로 보존한다.

facility_eda = facility_outlier_flagged.copy()

print("EDA용 데이터 크기:", facility_eda.shape)
print("원본 통합 데이터 크기:", facility_common.shape)

EDA용 데이터 크기: (1191, 51)
원본 통합 데이터 크기: (1191, 34)

In [256]:
# 개관일 기반 파생변수 생성
# OPNNG_DE를 활용해 개관연도와 운영연수를 만든다.
# BASE_DE 기준 연도를 사용해 데이터 기준 시점의 운영연수를 계산한다.

facility_eda["OPNNG_YEAR"] = facility_eda["OPNNG_DE"].dt.year
facility_eda["BASE_YEAR"] = facility_eda["BASE_DE"].dt.year

facility_eda["OPERATING_YEARS"] = (
    facility_eda["BASE_YEAR"] - facility_eda["OPNNG_YEAR"]
)

print("개관연도 / 기준연도 / 운영연수 파생변수 생성 완료")

display(
    facility_eda[
        ["facility_type", "FCLTY_NM", "OPNNG_DE", "OPNNG_DE_PRECISION", "BASE_DE", "OPNNG_YEAR", "BASE_YEAR", "OPERATING_YEARS"]
    ].head()
)

개관연도 / 기준연도 / 운영연수 파생변수 생성 완료

,facility_type,FCLTY_NM,OPNNG_DE,OPNNG_DE_PRECISION,BASE_DE,OPNNG_YEAR,BASE_YEAR,OPERATING_YEARS
0,박물관,국립중앙박물관,1945-12-03,day,2025-03-27,1945,2025,80
1,박물관,국립민속박물관,1946-04-25,day,2025-03-27,1946,2025,79
2,박물관,국립민속박물관 파주\n(개방형 수장고 및 정보센터),2021-07-23,day,2025-03-27,2021,2025,4
3,박물관,대한민국역사박물관,2012-12-26,day,2025-03-27,2012,2025,13
4,박물관,국립한글박물관,2014-10-09,day,2025-03-27,2014,2025,11

In [257]:
# 운영연수 파생변수 검증
# 음수 운영연수나 비정상적으로 큰 값이 있는지 확인한다.

operating_years_check = pd.DataFrame([
    {
        "check_item": "OPERATING_YEARS 결측치 수",
        "value": facility_eda["OPERATING_YEARS"].isna().sum()
    },
    {
        "check_item": "OPERATING_YEARS 음수 값 수",
        "value": (facility_eda["OPERATING_YEARS"] < 0).sum()
    },
    {
        "check_item": "OPERATING_YEARS 최솟값",
        "value": facility_eda["OPERATING_YEARS"].min()
    },
    {
        "check_item": "OPERATING_YEARS 중앙값",
        "value": facility_eda["OPERATING_YEARS"].median()
    },
    {
        "check_item": "OPERATING_YEARS 최댓값",
        "value": facility_eda["OPERATING_YEARS"].max()
    }
])

display(operating_years_check)

print("[운영연수 상위 20개 시설]")
display(
    facility_eda[
        ["facility_type", "ID", "FCLTY_NM", "CTPRVN_NM", "SIGNGU_NM", "OPNNG_DE_RAW", "OPNNG_DE", "OPERATING_YEARS"]
    ]
    .sort_values("OPERATING_YEARS", ascending=False)
    .head(20)
)

               check_item  value
0   OPERATING_YEARS 결측치 수    0.0
1  OPERATING_YEARS 음수 값 수    0.0
2     OPERATING_YEARS 최솟값    1.0
3     OPERATING_YEARS 중앙값   18.0
4     OPERATING_YEARS 최댓값   97.0

[운영연수 상위 20개 시설]

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,OPNNG_DE_RAW,OPNNG_DE,OPERATING_YEARS
129,박물관,KCDMMUS23N000000130,연세대학교박물관,서울,서대문구,1928,1928-01-01,97
111,박물관,KCDMMUS23N000000112,고려대학교박물관,서울,성북구,1934,1934-01-01,91
130,박물관,KCDMMUS23N000000131,이화여자대학교박물관,서울,서대문구,1935.04.06,1935-04-06,90
677,박물관,KCDMMUS23N000000678,송광사성보박물관,전남,순천시,1936.10.04,1936-10-04,89
40,박물관,KCDMMUS23N000000041,간송박물관,서울,성북구,1938.07.05,1938-07-05,87
522,박물관,KCDMMUS23N000000523,국립부여박물관,충남,부여군,1945.10.13,1945-10-13,80
691,박물관,KCDMMUS23N000000692,국립경주박물관,경북,경주시,1945.10.07,1945-10-07,80
0,박물관,KCDMMUS23N000000001,국립중앙박물관,서울,용산구,1945.12.03,1945-12-03,80
521,박물관,KCDMMUS23N000000522,국립공주박물관,충남,공주시,1946.04.01,1946-04-01,79
1,박물관,KCDMMUS23N000000002,국립민속박물관,서울,종로구,1946.04.25,1946-04-25,79
197,박물관,KCDMMUS23N000000198,인천광역시립박물관,인천,연수구,1946.04.01,1946-04-01,79
109,박물관,KCDMMUS23N000000110,경희대학교 중앙박물관,서울,동대문구,1955.10.01,1955-10-01,70
225,박물관,KCDMMUS23N000000226,전남대학교박물관,광주,북구,1957.04.15,1957-04-15,68
181,박물관,KCDMMUS23N000000182,경북대학교박물관,대구,북구,1959.05.28,1959-05-28,66
156,박물관,KCDMMUS23N000000157,동아대학교 박물관,부산,서구,1959.11.01,1959-11-01,66
624,박물관,KCDMMUS23N000000625,전북대학교박물관,전북특별자치도,전주시 덕진구,1961.05.01,1961-05-01,64
107,박물관,KCDMMUS23N000000108,건국대학교 박물관,서울,광진구,1963.03.01,1963-03-01,62
114,박물관,KCDMMUS23N000000115,동국대학교박물관,서울,중구,1963.09.01,1963-09-01,62
121,박물관,KCDMMUS23N000000122,성균관대학교박물관,서울,종로구,1964.06.22,1964-06-22,61
514,박물관,KCDMMUS23N000000515,한독의약박물관,충북,음성군,1964.04.27,1964-04-27,61

In [258]:
# 07.2 지역 변수 정리
# 시도명 표기가 통합 분석에서 일관적인지 확인한다.

print("[시도명 고유값]")
print(sorted(facility_eda["CTPRVN_NM"].dropna().unique()))

print("\n[시도별 시설 수]")
display(
    facility_eda["CTPRVN_NM"]
    .value_counts()
    .rename_axis("CTPRVN_NM")
    .reset_index(name="facility_count")
)

[시도명 고유값]
['강원', '강원특별자치도', '경기', '경남', '경북', '광주', '대구', '대전', '부산', '서울', '세종특별자치시', '울산', '인천', '전남', '전북', '전북특별자치도', '제주', '제주특별자치도', '충남', '충북']

[시도별 시설 수]

   CTPRVN_NM  facility_count
0         경기             186
1         서울             178
2         전남             105
3    강원특별자치도              99
4         경남              85
5         경북              82
6         충남              75
7    제주특별자치도              61
8         충북              50
9         부산              42
10   전북특별자치도              42
11        인천              37
12        광주              27
13        대구              25
14        전북              21
15        제주              21
16        대전              20
17        강원              19
18        울산              11
19   세종특별자치시               5

In [259]:
# 시도명을 기반으로 권역 변수를 생성한다.
# Tableau 대시보드나 지역별 비교 분석에서 활용하기 위한 파생변수이다.

region_group_map = {
    # 수도권
    "서울": "수도권",
    "경기": "수도권",
    "인천": "수도권",
    
    # 강원권
    "강원": "강원권",
    "강원특별자치도": "강원권",
    
    # 충청권
    "대전": "충청권",
    "세종": "충청권",
    "충북": "충청권",
    "충남": "충청권",
    
    # 전라권
    "광주": "전라권",
    "전북": "전라권",
    "전북특별자치도": "전라권",
    "전남": "전라권",
    
    # 경상권
    "부산": "경상권",
    "대구": "경상권",
    "울산": "경상권",
    "경북": "경상권",
    "경남": "경상권",
    
    # 제주권
    "제주": "제주권",
    "제주특별자치도": "제주권"
}

facility_eda["REGION_GROUP"] = facility_eda["CTPRVN_NM"].map(region_group_map)

print("권역 파생변수 생성 완료")

print("\n[권역 결측 확인]")
display(
    facility_eda[
        facility_eda["REGION_GROUP"].isna()
    ][["facility_type", "ID", "FCLTY_NM", "CTPRVN_NM", "SIGNGU_NM"]]
)

print("\n[권역별 시설 수]")
display(
    facility_eda["REGION_GROUP"]
    .value_counts()
    .rename_axis("REGION_GROUP")
    .reset_index(name="facility_count")
)

권역 파생변수 생성 완료

[권역 결측 확인]

    facility_type                   ID    FCLTY_NM CTPRVN_NM SIGNGU_NM
253           박물관  KCDMMUS23N000000254     국립조세박물관   세종특별자치시       세종시
254           박물관  KCDMMUS23N000000255   세종시립민속박물관   세종특별자치시       세종시
255           박물관  KCDMMUS23N000000256   충청남도산림박물관   세종특별자치시       세종시
256           박물관  KCDMMUS23N000000257      교과서박물관   세종특별자치시       세종시
257           박물관  KCDMMUS23N000000258  한국여인생활사박물관   세종특별자치시       세종시

[권역별 시설 수]

  REGION_GROUP  facility_count
0          수도권             401
1          경상권             245
2          전라권             195
3          충청권             145
4          강원권             118
5          제주권              82

In [260]:
# 시도 + 시군구 조합 변수를 생성한다.
# 지역 단위 집계나 지도/대시보드에서 활용할 수 있다.

facility_eda["SIDO_SIGUNGU"] = (
    facility_eda["CTPRVN_NM"].astype("string").str.strip()
    + " "
    + facility_eda["SIGNGU_NM"].astype("string").str.strip()
)

print("지역 조합 변수 생성 완료")

display(
    facility_eda[
        ["facility_type", "FCLTY_NM", "CTPRVN_NM", "SIGNGU_NM", "REGION_GROUP", "SIDO_SIGUNGU"]
    ].head()
)

지역 조합 변수 생성 완료

,facility_type,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,REGION_GROUP,SIDO_SIGUNGU
0,박물관,국립중앙박물관,서울,용산구,수도권,서울 용산구
1,박물관,국립민속박물관,서울,종로구,수도권,서울 종로구
2,박물관,국립민속박물관 파주\n(개방형 수장고 및 정보센터),경기,파주시,수도권,경기 파주시
3,박물관,대한민국역사박물관,서울,종로구,수도권,서울 종로구
4,박물관,국립한글박물관,서울,용산구,수도권,서울 용산구

In [261]:
# 07.3 로그 변환 파생변수 생성
# 오른쪽 꼬리가 긴 숫자형 변수에 대해 log1p 변환 컬럼을 생성한다.
# log1p는 log(1+x)이므로 0 값이 있어도 변환 가능하다.

log_transform_cols = [
    "LND_AR_VALUE",
    "EDC_FCLTY_AR_VALUE",
    "DATA_SPCE_AR_VALUE",
    "NMPR_CO",
    "DATA_CO",
    "TOT_PROGRM_CO",
    "VIEWNG_NMPR_CO",
    "DAY_AVRG_VIEWNG_NMPR_CO"
]

log_transform_cols = [
    col for col in log_transform_cols
    if col in facility_eda.columns
]

for col in log_transform_cols:
    facility_eda[f"LOG1P_{col}"] = np.log1p(facility_eda[col])

print("로그 변환 파생변수 생성 완료")
print("생성 컬럼 수:", len(log_transform_cols))
print([f"LOG1P_{col}" for col in log_transform_cols])

로그 변환 파생변수 생성 완료
생성 컬럼 수: 8
['LOG1P_LND_AR_VALUE', 'LOG1P_EDC_FCLTY_AR_VALUE', 'LOG1P_DATA_SPCE_AR_VALUE', 'LOG1P_NMPR_CO', 'LOG1P_DATA_CO', 'LOG1P_TOT_PROGRM_CO', 'LOG1P_VIEWNG_NMPR_CO', 'LOG1P_DAY_AVRG_VIEWNG_NMPR_CO']

In [262]:
# 로그 변환 전후 왜도 비교
# 왜도 감소 여부를 확인해 로그 변환의 효과를 검토한다.

log_skew_compare_rows = []

for col in log_transform_cols:
    original_s = facility_eda[col].dropna()
    log_s = facility_eda[f"LOG1P_{col}"].dropna()
    
    log_skew_compare_rows.append({
        "column": col,
        "original_skew": round(original_s.skew(), 3),
        "log1p_skew": round(log_s.skew(), 3),
        "skew_reduction": round(abs(original_s.skew()) - abs(log_s.skew()), 3)
    })

log_skew_compare = pd.DataFrame(log_skew_compare_rows).sort_values(
    "skew_reduction",
    ascending=False
)

display(log_skew_compare)

                    column  original_skew  log1p_skew  skew_reduction
0             LND_AR_VALUE         14.390       0.217          14.173
2       DATA_SPCE_AR_VALUE         13.838       0.486          13.351
6           VIEWNG_NMPR_CO          9.619      -0.127           9.493
3                  NMPR_CO         10.908       1.536           9.372
7  DAY_AVRG_VIEWNG_NMPR_CO          8.931       0.098           8.833
1       EDC_FCLTY_AR_VALUE          6.891       0.233           6.658
4                  DATA_CO          4.811      -0.117           4.693
5            TOT_PROGRM_CO          4.223       0.421           3.802

In [263]:
# 파생변수 생성 후 데이터 크기와 추가된 컬럼 확인

derived_cols = [
    "OPNNG_YEAR",
    "BASE_YEAR",
    "OPERATING_YEARS",
    "REGION_GROUP",
    "SIDO_SIGUNGU"
] + [f"LOG1P_{col}" for col in log_transform_cols]

print("파생변수 생성 후 facility_eda 크기:", facility_eda.shape)

print("\n[생성된 주요 파생변수]")
print(derived_cols)

print("\n[파생변수 미리보기]")
display(
    facility_eda[
        ["facility_type", "FCLTY_NM"] + derived_cols
    ].head()
)

파생변수 생성 후 facility_eda 크기: (1191, 64)

[생성된 주요 파생변수]
['OPNNG_YEAR', 'BASE_YEAR', 'OPERATING_YEARS', 'REGION_GROUP', 'SIDO_SIGUNGU', 'LOG1P_LND_AR_VALUE', 'LOG1P_EDC_FCLTY_AR_VALUE', 'LOG1P_DATA_SPCE_AR_VALUE', 'LOG1P_NMPR_CO', 'LOG1P_DATA_CO', 'LOG1P_TOT_PROGRM_CO', 'LOG1P_VIEWNG_NMPR_CO', 'LOG1P_DAY_AVRG_VIEWNG_NMPR_CO']

[파생변수 미리보기]

,facility_type,FCLTY_NM,OPNNG_YEAR,BASE_YEAR,OPERATING_YEARS,REGION_GROUP,SIDO_SIGUNGU,LOG1P_LND_AR_VALUE,LOG1P_EDC_FCLTY_AR_VALUE,LOG1P_DATA_SPCE_AR_VALUE,LOG1P_NMPR_CO,LOG1P_DATA_CO,LOG1P_TOT_PROGRM_CO,LOG1P_VIEWNG_NMPR_CO,LOG1P_DAY_AVRG_VIEWNG_NMPR_CO
0,박물관,국립중앙박물관,1945,2025,80,수도권,서울 용산구,12.563719,8.512382,7.347944,4.49981,11.966063,2.833213,15.24589,9.35988
1,박물관,국립민속박물관,1946,2025,79,수도권,서울 종로구,10.587282,7.228156,5.783825,4.077537,11.438062,4.26268,14.083774,8.192294
2,박물관,국립민속박물관 파주\n(개방형 수장고 및 정보센터),2021,2025,4,수도권,경기 파주시,11.005655,5.629382,<NA>,<NA>,<NA>,2.397895,11.330288,5.587249
3,박물관,대한민국역사박물관,2012,2025,13,수도권,서울 종로구,8.771215,6.20859,4.406719,4.025352,9.801787,3.555348,13.577695,7.686621
4,박물관,국립한글박물관,2014,2025,11,수도권,서울 용산구,12.563719,5.937536,5.398163,3.526361,10.310951,3.526361,12.891964,7.001246

- 세종, 세종특별자치시를 둘다 적용하지 않음 (추가)

In [264]:
# REGION_GROUP 결측 수정
# 세종특별자치시가 매핑되지 않아 결측으로 남아 있었으므로 충청권으로 보정한다.

facility_eda.loc[
    facility_eda["CTPRVN_NM"] == "세종특별자치시",
    "REGION_GROUP"
] = "충청권"

print("[REGION_GROUP 결측 재확인]")
display(
    facility_eda[
        facility_eda["REGION_GROUP"].isna()
    ][["facility_type", "ID", "FCLTY_NM", "CTPRVN_NM", "SIGNGU_NM"]]
)

print("[권역별 시설 수 재확인]")
display(
    facility_eda["REGION_GROUP"]
    .value_counts()
    .rename_axis("REGION_GROUP")
    .reset_index(name="facility_count")
)

[REGION_GROUP 결측 재확인]

Empty DataFrame
Columns: [facility_type, ID, FCLTY_NM, CTPRVN_NM, SIGNGU_NM]
Index: []

[권역별 시설 수 재확인]

  REGION_GROUP  facility_count
0          수도권             401
1          경상권             245
2          전라권             195
3          충청권             150
4          강원권             118
5          제주권              82

### 07. 파생변수 생성 결과

#### 1) 파생변수 생성용 데이터 구성

- 이상치 플래그가 포함된 `facility_outlier_flagged` 데이터를 복사하여 EDA용 데이터셋 `facility_eda`를 생성하였다.
- 원본 통합 데이터인 `facility_common`은 그대로 보존하였다.
- 파생변수 생성 후 `facility_eda`의 크기는 `(1191, 64)`이다.

#### 2) 개관일 기반 파생변수

- `OPNNG_DE`와 `BASE_DE`를 활용해 개관연도, 기준연도, 운영연수 변수를 생성하였다.
- 생성한 변수는 다음과 같다.
  - `OPNNG_YEAR`: 개관연도
  - `BASE_YEAR`: 기준연도
  - `OPERATING_YEARS`: 기준연도 기준 운영연수

- `OPERATING_YEARS` 검증 결과는 다음과 같다.
  - 결측치 수: 0개
  - 음수 값 수: 0개
  - 최솟값: 1년
  - 중앙값: 18년
  - 최댓값: 97년

- 운영연수 최댓값은 오래된 대학 박물관 등에서 나타나므로 비정상 값으로 보지 않았다.

#### 3) 지역 파생변수

- 시도명 `CTPRVN_NM`을 기반으로 권역 변수 `REGION_GROUP`을 생성하였다.
- 시도와 시군구를 결합한 지역 조합 변수 `SIDO_SIGUNGU`를 생성하였다.
- `세종특별자치시`는 최초 매핑에서 누락되어 있었으나, 추가 보정하여 `충청권`으로 분류하였다.
- 권역 변수의 결측치는 최종적으로 0개이다.

권역별 시설 수는 다음과 같다.

| 권역 | 시설 수 |
|---|---:|
| 수도권 | 401 |
| 경상권 | 245 |
| 전라권 | 195 |
| 충청권 | 150 |
| 강원권 | 118 |
| 제주권 | 82 |

#### 4) 로그 변환 파생변수

- 오른쪽 꼬리가 긴 분포를 보이는 숫자형 변수에 대해 `log1p` 변환 컬럼을 생성하였다.
- 로그 변환은 0 값이 포함된 변수에도 적용할 수 있도록 `np.log1p()`를 사용하였다.
- 생성한 로그 변환 컬럼은 다음과 같다.
  - `LOG1P_LND_AR_VALUE`
  - `LOG1P_EDC_FCLTY_AR_VALUE`
  - `LOG1P_DATA_SPCE_AR_VALUE`
  - `LOG1P_NMPR_CO`
  - `LOG1P_DATA_CO`
  - `LOG1P_TOT_PROGRM_CO`
  - `LOG1P_VIEWNG_NMPR_CO`
  - `LOG1P_DAY_AVRG_VIEWNG_NMPR_CO`

#### 5) 로그 변환 효과

- 로그 변환 후 주요 규모 변수와 관람객 수 변수의 왜도가 크게 감소하였다.
- 특히 `LND_AR_VALUE`, `DATA_SPCE_AR_VALUE`, `VIEWNG_NMPR_CO`, `DAY_AVRG_VIEWNG_NMPR_CO`에서 로그 변환 효과가 뚜렷하게 나타났다.
- 따라서 이후 EDA에서는 원본 변수와 로그 변환 변수를 함께 비교할 수 있다.
- 모델링 단계에서는 분포 왜곡이 큰 변수에 대해 로그 변환 변수 사용을 고려할 수 있다.

#### 6) 주의 사항

- `DAY_AVRG_VIEWNG_NMPR_CO`와 `LOG1P_DAY_AVRG_VIEWNG_NMPR_CO`는 관람객 수와 직접적으로 연결된 성과 변수이다.
- 이후 관람객 수 예측 모델에서는 데이터 누수 가능성이 있으므로 입력 변수로 사용할 때 주의가 필요하다.
- 현재 단계에서는 파생변수 생성까지만 진행했으며, 최종 분석용 변수 선택은 이후 EDA와 모델링 단계에서 다시 판단한다.

## 전처리 전체 정리 및 EDA 준비

### 1. 프로젝트 개요

본 프로젝트의 주제는 **문화시설 활성화에 대한 운영·이용 현황 성과 분석**이다.

분석 대상 데이터는 다음 두 가지이다.

- 국내 문화체육관광 분야 박물관 시설 및 소장자료 통계 데이터
- 국내 문화체육관광 분야 미술관 시설 및 현황통계 데이터

분석 목적은 박물관과 미술관의 운영 현황, 시설 규모, 인력, 자료/프로그램, 이용 성과 등을 비교하여 문화시설 활성화와 관련된 주요 요인을 탐색하는 것이다.

---

### 2. 데이터 로드 및 기본 확인

- 박물관 데이터와 미술관 데이터를 각각 로드하였다.
- 박물관 데이터에서 `ID`가 없는 1개 행을 확인하였다.
- 해당 행은 완전한 빈 행은 아니었지만, 시설 단위 분석에 필요한 시설 정보가 없고 메타데이터만 남아 있는 행으로 판단하였다.
- 따라서 시설 단위 분석에 적합하지 않다고 보고 제거하였다.

최종 기본 데이터 크기는 다음과 같다.

| 데이터 | 행 수 | 컬럼 수 |
|---|---:|---:|
| 박물관 | 897 | 94 |
| 미술관 | 294 | 79 |

---

### 3. 분석 후보 컬럼 선정

- 컬럼 정의서는 코드에서 직접 사용하지 않고, 사람이 참고하는 용도로만 활용하였다.
- 원본 데이터의 컬럼을 직접 확인한 뒤, 분석에 사용할 후보 컬럼을 코드에 직접 작성하였다.
- 박물관과 미술관 각각에서 분석 후보 컬럼을 선정하여 `museum_basic`, `art_basic` 데이터를 생성하였다.
- 시설 유형 구분을 위해 `facility_type` 컬럼을 추가하였다.
  - 박물관 데이터: `"박물관"`
  - 미술관 데이터: `"미술관"`

분석 후보 컬럼 선정 후 데이터 크기는 다음과 같다.

| 데이터 | 행 수 | 컬럼 수 |
|---|---:|---:|
| `museum_basic` | 897 | 77 |
| `art_basic` | 294 | 64 |

---

### 4. 중복 컬럼명 확인

박물관 데이터에서 pandas가 자동으로 `.1`을 붙인 중복 컬럼명을 확인하였다.

- `DSPY_AR_CN.1`
- `CNTRCT_EMP_CO.1`

해당 컬럼들은 분석 핵심 변수가 아니므로 별도로 컬럼명을 수정하지 않고, 발견 사항으로만 기록하였다.  
또한 `.1` 컬럼은 분석용 데이터셋에 포함하지 않았다.

---

### 5. 결측치 구조 확인

박물관과 미술관의 결측치 비율을 확인하고, 컬럼별로 결측 처리 기준을 정리하였다.

박물관 결측 처리 기준 결과는 다음과 같다.

| 처리 기준 | 컬럼 수 |
|---|---:|
| 결측 처리 후 사용 가능 | 23 |
| 보류/제거 후보 | 20 |
| 유지 가능 | 20 |
| 의미 검토 필요 | 14 |

미술관 결측 처리 기준 결과는 다음과 같다.

| 처리 기준 | 컬럼 수 |
|---|---:|
| 유지 가능 | 30 |
| 의미 검토 필요 | 15 |
| 보류/제거 후보 | 10 |
| 결측 처리 후 사용 가능 | 8 |
| 제거 후보 | 1 |

특히 `AR_CN` 컬럼은 미술관에서 결측치가 100%로 나타나 통합 분석에서는 제거하는 방향으로 판단하였다.

---

### 6. 자료형 변환

숫자형과 날짜형 컬럼을 구분하여 자료형 변환을 진행하였다.

#### 숫자형 변환

- 쉼표가 포함된 숫자 문자열은 쉼표를 제거한 뒤 숫자형으로 변환하였다.
- 변환 전후 `dtype`을 비교하여 정상 변환 여부를 확인하였다.
- 숫자형 변환 가능 비율이 100%인 컬럼을 우선 변환하였다.
- 일부 비숫자 값이 섞여 있더라도 컬럼 의미상 숫자형으로 보는 것이 적절한 컬럼은 숫자형으로 변환하였다.
- 설명형 값, 복합 가격 정보, 문자 혼합 값이 많은 컬럼은 무리하게 변환하지 않고 보류하였다.

#### 날짜형 변환

- `BASE_DE`, `LAST_CHG_DE`, `OPNNG_DE` 컬럼을 날짜형으로 변환하였다.
- `OPNNG_DE`는 연도만 있는 값, 연월만 있는 값, 복수 날짜가 포함된 값, 설명이 함께 적힌 값이 존재하였다.
- 따라서 `OPNNG_DE`의 원본 값은 `OPNNG_DE_RAW` 컬럼으로 보존하였다.
- 날짜로 해석 가능한 첫 번째 날짜 패턴을 추출하여 `OPNNG_DE`를 변환하였다.
- 날짜 정확도 수준을 구분하기 위해 `OPNNG_DE_PRECISION` 컬럼을 추가하였다.

`OPNNG_DE_PRECISION`의 의미는 다음과 같다.

| 값 | 의미 |
|---|---|
| `day` | 연월일 수준 |
| `month` | 연월 수준 |
| `year` | 연도 수준 |

---

### 7. 박물관/미술관 통합 전 컬럼 정리

박물관과 미술관의 컬럼 구조를 비교하였다.

| 구분 | 컬럼 수 |
|---|---:|
| 박물관 전체 컬럼 수 | 79 |
| 미술관 전체 컬럼 수 | 66 |
| 공통 컬럼 수 | 57 |
| 박물관에만 있는 컬럼 수 | 22 |
| 미술관에만 있는 컬럼 수 | 9 |

통합 분석에서는 박물관과 미술관에 모두 존재하고, 공통적으로 해석 가능한 컬럼을 중심으로 34개 컬럼을 선정하였다.

- 식별 정보
- 지역 정보
- 위치 정보
- 운영 정보
- 시설 규모
- 인력
- 자료/프로그램
- 이용 성과
- 접근성/편의 정보

통합 전 숫자형 컬럼은 박물관과 미술관 모두 `Float64`로 통일하였다.  
dtype 통일 후 박물관과 미술관의 통합 기준 컬럼 자료형은 모두 일치하였다.

---

### 8. 박물관/미술관 데이터 통합

박물관 통합 기준 데이터와 미술관 통합 기준 데이터를 행 기준으로 결합하여 `facility_common` 데이터를 생성하였다.

통합 결과는 다음과 같다.

| 구분 | 값 |
|---|---:|
| 통합 데이터 행 수 | 1191 |
| 통합 데이터 컬럼 수 | 34 |
| 박물관 행 수 | 897 |
| 미술관 행 수 | 294 |
| `ID` 결측치 | 0 |
| `ID` 중복값 | 0 |
| 시설명 결측치 | 0 |

`facility_type` 값은 `"박물관"`, `"미술관"`으로 정상 구분되어 있다.

---

### 9. 통합 데이터 결측치 구조

통합 데이터에서 결측률이 높은 컬럼은 주로 인력 관련 컬럼으로 나타났다.

결측률이 높은 주요 컬럼은 다음과 같다.

- `PRVATE_VLNTER_CO`
- `CNTRCT_EMP_CO`
- `PUBLIC_VLNTER_CO`
- `PRFSN_CO`
- `GNRL_GVRNM_EMP_CO`
- `QUALF_HOLD_CO`
- `ARTGR_EMP_CO`
- `NMPR_CO`
- `DATA_CO`
- `DATA_SPCE_AR_VALUE`

반면 관람객 수 관련 컬럼인 `VIEWNG_NMPR_CO`, `DAY_AVRG_VIEWNG_NMPR_CO`의 결측률은 약 4.53%로 비교적 낮게 나타났다.

현재 단계에서는 결측치를 대체하거나 제거하지 않았다.

---

### 10. 이상치 확인

숫자형 컬럼을 대상으로 이상치 구조를 확인하였다.

#### 좌표값 확인

- `FCLTY_LO`, `FCLTY_LA`의 범위를 확인하였다.
- 국내 시설 좌표 범위를 크게 벗어나는 값은 확인되지 않았다.

#### 음수 값 확인

- 숫자형 컬럼 전체에서 음수 값은 확인되지 않았다.

#### 0 값 확인

- `OPNNG_DAY_CO`에서 0 값이 일부 확인되었다.
- 대부분 시설명에 휴관 또는 폐관 정보가 포함되어 있어 단순 오류라기보다 운영 상태와 관련된 값으로 판단하였다.
- 인력 수, 프로그램 수 관련 컬럼에서도 0 값이 확인되었지만 실제 0명 또는 0개일 가능성이 있으므로 현재 단계에서는 유지하였다.

#### IQR 기준 이상치 확인

- IQR 기준으로 여러 숫자형 컬럼에서 이상치 후보가 확인되었다.
- 그러나 상위 이상치 시설을 확인한 결과, 국립중앙박물관, 국립현대미술관, 독립기념관 등 대형 시설이 주로 포함되어 있었다.
- 따라서 해당 값들은 단순 오류라기보다 시설 규모 차이에서 발생한 정상적인 극단값일 가능성이 높다고 판단하였다.

현재 단계에서는 이상치를 제거하지 않고, IQR 기준 이상치 여부를 나타내는 플래그 컬럼을 생성하였다.  
또한 시설별 이상치 플래그 개수인 `IQR_OUTLIER_FLAG_COUNT`를 생성하였다.

---

### 11. 파생변수 생성

이상치 플래그가 포함된 `facility_outlier_flagged` 데이터를 복사하여 EDA용 데이터셋 `facility_eda`를 생성하였다.

#### 개관일 기반 파생변수

다음 변수를 생성하였다.

| 변수명 | 의미 |
|---|---|
| `OPNNG_YEAR` | 개관연도 |
| `BASE_YEAR` | 기준연도 |
| `OPERATING_YEARS` | 기준연도 기준 운영연수 |

`OPERATING_YEARS` 검증 결과는 다음과 같다.

| 항목 | 값 |
|---|---:|
| 결측치 수 | 0 |
| 음수 값 수 | 0 |
| 최솟값 | 1년 |
| 중앙값 | 18년 |
| 최댓값 | 97년 |

운영연수 최댓값은 오래된 대학 박물관 등에서 나타난 값이므로 비정상 값으로 보지 않았다.

#### 지역 파생변수

다음 지역 파생변수를 생성하였다.

| 변수명 | 의미 |
|---|---|
| `REGION_GROUP` | 시도 기반 권역 |
| `SIDO_SIGUNGU` | 시도 + 시군구 조합 |

`세종특별자치시`는 최초 매핑에서 누락되어 있었으나, 추가 보정하여 `충청권`으로 분류하였다.  
권역 변수의 결측치는 최종적으로 0개이다.

권역별 시설 수는 다음과 같다.

| 권역 | 시설 수 |
|---|---:|
| 수도권 | 401 |
| 경상권 | 245 |
| 전라권 | 195 |
| 충청권 | 150 |
| 강원권 | 118 |
| 제주권 | 82 |

#### 로그 변환 파생변수

오른쪽 꼬리가 긴 분포를 보이는 숫자형 변수에 대해 `log1p` 변환 컬럼을 생성하였다.

생성한 로그 변환 컬럼은 다음과 같다.

- `LOG1P_LND_AR_VALUE`
- `LOG1P_EDC_FCLTY_AR_VALUE`
- `LOG1P_DATA_SPCE_AR_VALUE`
- `LOG1P_NMPR_CO`
- `LOG1P_DATA_CO`
- `LOG1P_TOT_PROGRM_CO`
- `LOG1P_VIEWNG_NMPR_CO`
- `LOG1P_DAY_AVRG_VIEWNG_NMPR_CO`

로그 변환 후 주요 규모 변수와 관람객 수 변수의 왜도가 크게 감소하였다.

---

### 12. EDA 진행 시 주의 사항

- `facility_common`은 박물관/미술관 통합 기본 데이터이다.
- `facility_eda`는 이상치 플래그와 파생변수가 포함된 EDA용 데이터이다.
- 이후 EDA는 `facility_eda`를 기준으로 진행한다.
- 현재 단계에서는 결측치 대체, 이상치 제거, 모델링용 변수 선택은 아직 진행하지 않았다.
- `DAY_AVRG_VIEWNG_NMPR_CO`와 `LOG1P_DAY_AVRG_VIEWNG_NMPR_CO`는 관람객 수와 직접적으로 연결된 성과 변수이다.
- 이후 관람객 수 예측 모델에서는 데이터 누수 가능성이 있으므로 입력 변수로 사용할 때 주의가 필요하다.

---

### 13. 최종 산출물

EDA를 별도 노트북에서 진행하기 위해 전처리 완료 데이터를 CSV 파일로 저장한다.

저장 대상 데이터는 다음과 같다.

- `facility_eda`: EDA용 최종 전처리 데이터
- 필요 시 `facility_common`: 파생변수 생성 전 통합 기본 데이터

다음 단계에서는 저장된 CSV 파일을 새 EDA 노트북에서 불러와 시설 유형별, 권역별, 시도별 기초 분석부터 진행한다.

In [265]:
# 전처리 완료 데이터 CSV 저장
# EDA는 별도 노트북에서 진행할 예정이므로, 현재까지 전처리한 데이터를 CSV로 저장한다.

import os

processed_dir = "data/processed"
os.makedirs(processed_dir, exist_ok=True)

facility_eda_path = os.path.join(processed_dir, "facility_eda_preprocessed.csv")
facility_common_path = os.path.join(processed_dir, "facility_common_base.csv")

# EDA용 최종 데이터 저장
facility_eda.to_csv(
    facility_eda_path,
    index=False,
    encoding="utf-8-sig",
    date_format="%Y-%m-%d"
)

# 파생변수 생성 전 통합 기본 데이터도 함께 저장
facility_common.to_csv(
    facility_common_path,
    index=False,
    encoding="utf-8-sig",
    date_format="%Y-%m-%d"
)

print("CSV 저장 완료")
print("EDA용 전처리 데이터:", facility_eda_path)
print("통합 기본 데이터:", facility_common_path)

CSV 저장 완료
EDA용 전처리 데이터: data/processed\facility_eda_preprocessed.csv
통합 기본 데이터: data/processed\facility_common_base.csv

In [266]:
# 저장된 CSV 파일이 정상적으로 생성되었는지 확인한다.

saved_files = pd.DataFrame([
    {
        "file_name": "facility_eda_preprocessed.csv",
        "path": facility_eda_path,
        "exists": os.path.exists(facility_eda_path),
        "file_size_mb": round(os.path.getsize(facility_eda_path) / (1024 ** 2), 3) if os.path.exists(facility_eda_path) else None
    },
    {
        "file_name": "facility_common_base.csv",
        "path": facility_common_path,
        "exists": os.path.exists(facility_common_path),
        "file_size_mb": round(os.path.getsize(facility_common_path) / (1024 ** 2), 3) if os.path.exists(facility_common_path) else None
    }
])

display(saved_files)

,file_name,path,exists,file_size_mb
0,facility_eda_preprocessed.csv,data/processed\facility_eda_preprocessed.csv,True,0.551
1,facility_common_base.csv,data/processed\facility_common_base.csv,True,0.305

In [267]:
# 저장한 CSV를 다시 불러와 형태를 확인한다.
# 실제 EDA 노트북에서 사용할 파일이 정상적으로 읽히는지 확인하는 단계이다.

facility_eda_check = pd.read_csv(
    facility_eda_path,
    encoding="utf-8-sig"
)

facility_common_check = pd.read_csv(
    facility_common_path,
    encoding="utf-8-sig"
)

print("facility_eda 저장 전 크기:", facility_eda.shape)
print("facility_eda 저장 후 다시 불러온 크기:", facility_eda_check.shape)

print("\nfacility_common 저장 전 크기:", facility_common.shape)
print("facility_common 저장 후 다시 불러온 크기:", facility_common_check.shape)

print("\nEDA용 데이터 미리보기")
display(facility_eda_check.head())

facility_eda 저장 전 크기: (1191, 64)
facility_eda 저장 후 다시 불러온 크기: (1191, 64)

facility_common 저장 전 크기: (1191, 34)
facility_common 저장 후 다시 불러온 크기: (1191, 34)

EDA용 데이터 미리보기

,facility_type,ID,FCLTY_NM,CTPRVN_NM,SIGNGU_NM,LEGALDONG_NM,ADSTRD_NM,FCLTY_LO,FCLTY_LA,OPNNG_DE,...,REGION_GROUP,SIDO_SIGUNGU,LOG1P_LND_AR_VALUE,LOG1P_EDC_FCLTY_AR_VALUE,LOG1P_DATA_SPCE_AR_VALUE,LOG1P_NMPR_CO,LOG1P_DATA_CO,LOG1P_TOT_PROGRM_CO,LOG1P_VIEWNG_NMPR_CO,LOG1P_DAY_AVRG_VIEWNG_NMPR_CO
0,박물관,KCDMMUS23N000000001,국립중앙박물관,서울,용산구,용산동6가,한강로동,126.977740,37.524702,1945-12-03,...,수도권,서울 용산구,12.563719,8.512382,7.347944,4.499810,11.966063,2.833213,15.245890,9.359880
1,박물관,KCDMMUS23N000000002,국립민속박물관,서울,종로구,세종로,청운효자동,126.978890,37.581675,1946-04-25,...,수도권,서울 종로구,10.587282,7.228156,5.783825,4.077537,11.438062,4.262680,14.083774,8.192294
2,박물관,KCDMMUS23N000000003,국립민속박물관 파주\n(개방형 수장고 및 정보센터),경기,파주시,탄현면 법흥리,탄현면,126.693918,37.786670,2021-07-23,...,수도권,경기 파주시,11.005655,5.629382,NaN,NaN,NaN,2.397895,11.330288,5.587249
3,박물관,KCDMMUS23N000000004,대한민국역사박물관,서울,종로구,세종로,종로1.2.3.4가동,126.978339,37.573714,2012-12-26,...,수도권,서울 종로구,8.771215,6.208590,4.406719,4.025352,9.801787,3.555348,13.577695,7.686621
4,박물관,KCDMMUS23N000000005,국립한글박물관,서울,용산구,용산동6가,서빙고동,126.980486,37.521069,2014-10-09,...,수도권,서울 용산구,12.563719,5.937536,5.398163,3.526361,10.310951,3.526361,12.891964,7.001246